### ISSUE TITLE
Problem with MyPet MySQL

### ISSUE THREAD

**Issue by SkyceDE** [xXKeyleXx/MyPet#1017]
Please provide the following info.

**Bukkit/Spigot/Bungee Build/Version:**
Spigot: version 1.8.8-R0.1-Snapshot
BungeeBuild: BungeeCord-Bootstrap:1.12-Snapshot

**MyPet Build/Version:**
2.3.5 - Dev Build

**Do you use the premium version? (this wont change anything for you)**
Yes

**What is the expected result?**
Sucessful connection to MySQL

**What happens instead of that?**
No Connection to MySQL - ALL OTHER PLUGINS CAN CONNECT - Password is not wrong, on some servers MyPet can connect, but on some servers this error results

**Error:**
[12:30:50] [Server thread/WARN]: RepositoryInitException{exception=de.Keyle.MyPet.util.hikari.pool.HikariPool$PoolInitializationException: Exception during pool initialization: HikariPool-0 - Connection is not available, request timed out after 30001ms.}
[12:30:50] [Server thread/WARN]: 	at de.Keyle.MyPet.repository.types.MySqlRepository.init(MySqlRepository.java:92)
[12:30:50] [Server thread/WARN]: 	at de.Keyle.MyPet.MyPetPlugin.onEnable(MyPetPlugin.java:277)
[12:30:50] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
[12:30:50] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
[12:30:50] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[12:30:50] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357)
[12:30:50] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317)
[12:30:50] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414)
[12:30:50] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378)
[12:30:50] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333)
[12:30:50] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263)
[12:30:50] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:524)
[12:30:50] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)

**Comment by xXKeyleXx** [comment]
What is the MaxConnections config option is set to for you?
