### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by Tomodu** [xXKeyleXx/MyPet#1038]
Please provide the following info.

**Bukkit/Spigot/Bungee Build/Version:** Spigot

**MyPet Build/Version:** 2.3.5

**Do you use the premium version? (this wont change anything for you)** Yes but that wrong ;) we are donator

**What is the expected result?** compatible

**What happens instead of that?** search the solution

**Error:**
[MyPet] ###########################################

[16:26:31] [Server thread/WARN]: [MyPet] This version of MyPet is not compatible with "v1_12_R1".

[16:26:31] [Server thread/WARN]: [MyPet] But there should be an update (see below).

[16:26:31] [Thread-49/INFO]: [MyPet] Start update download: 2.3.5 #491

[16:26:31] [Server thread/INFO]: [MyPet] Wait for the update download to finish...

[16:26:32] [Thread-49/WARN]: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

[16:26:32] [Thread-49/WARN]: 	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)

[16:26:32] [Thread-49/WARN]: 	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1949)

[16:26:32] [Thread-49/WARN]: 	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:302)

[16:26:32] [Thread-49/WARN]: 	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:296)

[16:26:32] [Thread-49/WARN]: 	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1509)

[16:26:32] [Thread-49/WARN]: 	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:216)

[16:26:32] [Thread-49/WARN]: 	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:979)

[16:26:32] [Thread-49/WARN]: 	at sun.security.ssl.Handshaker.process_record(Handshaker.java:914)

[16:26:32] [Thread-49/WARN]: 	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1062)

**Comment by xXKeyleXx** [comment]
Update your java or download the latest version from here: https://mypet-plugin.de/download

**Comment by Tomodu** [comment]
ths but Mypet prevents build on server can you help me? please

think you for you answer rapide
