### ISSUE TITLE
problem with world

### ISSUE THREAD

**Issue by Tomodu** [xXKeyleXx/MyPet#1039]
Please provide the following info.

**Bukkit/Spigot/Bungee Build/Version:** Spigot

**MyPet Build/Version:** 2.3.5

**Do you use the premium version? (this wont change anything for you)** Yes but that wrong ;) we are donator

**What is the expected result?** The plug in works well, I no longer have compatibility problem, however it prevents my players from breaking / destroying etc

**What happens instead of that?** search the solution

**Error:**

**Comment by xXKeyleXx** [comment]
i have no idea what your problem is.

**Comment by Tomodu** [comment]
When I put the plug in on the server the players no longer have access to anything

**Comment by xXKeyleXx** [comment]
I doubt that MyPet is the cause and I would like to see some server logs.

**Comment by Tomodu** [comment]
[14:43:01] [Server thread/INFO]: [MineWeb_BukkitBridge] No update found.

[14:43:01] [Server thread/INFO]: [EssentialsProtect] Enabling EssentialsProtect v2.0.1-b496

[14:43:01] [Server thread/ERROR]: Essentials not installed or failed to load. Essenials Protect is in emergency mode now.

[14:43:01] [Server thread/INFO]: [EXPBottles] Enabling EXPBottles v1.1.4

[14:43:01] [Server thread/INFO]: [Player Status Signs] Enabling PlayerStatusSigns v2.1.3

[14:43:01] [Server thread/INFO]: [Player Status Signs] Essentials was not found. Cannot determine AFK.

[14:43:01] [Server thread/INFO]: [Player Status Signs] Enabled player status signs successfully.

[14:43:01] [Server thread/INFO]: [MyPet] Enabling MyPet v2.3.5

[14:43:01] [Server thread/INFO]: [MyPet] ###########################################

[14:43:01] [Server thread/INFO]: [MyPet] #  A new version is available: 2.3.6 #511 #

[14:43:01] [Server thread/INFO]: [MyPet] #  https://mypet-plugin.de/download        #

[14:43:01] [Server thread/INFO]: [MyPet] ###########################################

[14:43:01] [Thread-49/INFO]: [MyPet] Start update download: 2.3.6 #511

[14:43:01] [Server thread/INFO]: [MyPet] Compat mode for v1_12_R1 loaded.

[14:43:01] [Thread-49/WARN]: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

[14:43:01] [Thread-49/WARN]: 	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)

[14:43:01] [Thread-49/WARN]: 	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1949)

[14:43:01] [Thread-49/WARN]: 	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:302)

[14:43:01] [Thread-49/WARN]: 	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:296)

[14:43:01] [Thread-49/WARN]: 	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1509)

[14:43:01] [Thread-49/WARN]: 	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:216)

[14:43:01] [Thread-49/WARN]: 	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:979)

[14:43:01] [Thread-49/WARN]: 	at sun.security.ssl.Handshaker.process_record(Handshaker.java:914)

[14:43:01] [Thread-49/WARN]: 	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1062)

[14:43:01] [Thread-49/WARN]: 	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)

[14:43:01] [Thread-49/WARN]: 	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)

[14:43:01] [Thread-49/WARN]: 	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)

[14:43:01] [Thread-49/WARN]: 	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)

[14:43:01] [Thread-49/WARN]: 	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)

[14:43:01] [Thread-49/WARN]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1513)

[14:43:01] [Thread-49/WARN]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)

[14:43:01] [Thread-49/WARN]: 	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)

[14:43:01] [Thread-49/WARN]: 	at java.net.URL.openStream(URL.java:1045)

[14:43:01] [Thread-49/WARN]: 	at de.Keyle.MyPet.util.Updater.lambda$download$0(Updater.java:146)

[14:43:01] [Thread-49/WARN]: 	at java.lang.Thread.run(Thread.java:745)

[14:43:01] [Thread-49/WARN]: Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

[14:43:01] [Thread-49/WARN]: 	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:387)

[14:43:01] [Thread-49/WARN]: 	at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:292)

[14:43:01] [Thread-49/WARN]: 	at sun.security.validator.Validator.validate(Validator.java:260)

[14:43:01] [Thread-49/WARN]: 	at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324)

[14:43:01] [Thread-49/WARN]: 	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:229)

[14:43:01] [Thread-49/WARN]: 	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124)

[14:43:01] [Thread-49/WARN]: 	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1491)

[14:43:01] [Thread-49/WARN]: 	... 15 more

[14:43:01] [Thread-49/WARN]: Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

[14:43:01] [Thread-49/WARN]: 	at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)

[14:43:01] [Thread-49/WARN]: 	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)

[14:43:01] [Thread-49/WARN]: 	at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280)

[14:43:01] [Thread-49/WARN]: 	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:382)

[14:43:01] [Thread-49/WARN]: 	... 21 more

[14:43:01] [Server thread/INFO]: [MyPet] --- Loading WorldGroups ---------------------------

[14:43:01] [Server thread/INFO]: [MyPet]    added 'world' to 'default'

[14:43:01] [Server thread/INFO]: [MyPet]    added 'world_nether' to 'default'

[14:43:01] [Server thread/INFO]: [MyPet]    added 'world_the_end' to 'default'

[14:43:01] [Server thread/INFO]: [MyPet]    added 'minijeu' to 'default'

[14:43:01] [Server thread/INFO]: [MyPet]    added 'spawn' to 'default'

[14:43:01] [Server thread/INFO]: [MyPet]    added 'projet' to 'default'

[14:43:01] [Server thread/INFO]: [MyPet]    added 'nouveau' to 'default'

[14:43:01] [Server thread/INFO]: [MyPet]    added 'jeu' to 'default'

[14:43:01] [Server thread/INFO]: [MyPet]    added 'ressources' to 'default'

[14:43:01] [Server thread/INFO]: [MyPet] -------------------------------------------------

[14:43:01] [Server thread/INFO]: [MyPet] Thank you for buying MyPet-Premium!

[14:43:01] [Server thread/INFO]: [MyPet] version 2.3.5-b491P ENABLED

[14:43:01] [Server thread/INFO]: [Essentials] Enabling Essentials v2.0.1-b496

[14:43:01] [Server thread/INFO]: [Essentials] Using 1.8.3+ BlockStateMeta provider as mob spawner provider.

[14:43:01] [Server thread/INFO]: [Essentials] Using Reflection based provider as spawn egg provider.

[14:43:01] [Server thread/INFO]: [Essentials] Using 1.9+ BasePotionData provider as potion meta provider.

[14:43:01] [Server thread/INFO]: Using locale fr_FR

[14:43:01] [Server thread/INFO]: [Essentials] Starting Metrics. Opt-out using the global bStats config.

[14:43:01] [Server thread/INFO]: [Vault][Economy] Essentials Economy hooked.

[14:43:01] [Server thread/INFO]: [Essentials] Using Vault based permissions (Permissio

**Comment by Tomodu** [comment]
The problem occurs when I put the plug in

**Comment by xXKeyleXx** [comment]
May this be the problem you are talking about?
- "Essentials not installed or failed to load. Essenials Protect is in emergency mode now."

**Comment by Tomodu** [comment]
I'll try to fix essentials see if that's it

**Comment by Tomodu** [comment]
it s essentials
