### ISSUE TITLE
When you ride a parrot , the server crashes .

### ISSUE THREAD

**Issue by luzhenbin** [xXKeyleXx/MyPet#1040]
Spigot Version:1.12.1
Mypet Version: 2.3.1

Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at de.Keyle.MyPet.compat.v1_12_R1.entity.EntityMyPet.a(EntityMyPet.java:1125)
	at de.Keyle.MyPet.compat.v1_12_R1.entity.EntityMyPet.n(EntityMyPet.java:949)
	at net.minecraft.server.v1_12_R1.EntityLiving.B_(EntityLiving.java:1939)
	at net.minecraft.server.v1_12_R1.EntityInsentient.B_(EntityInsentient.java:246)
	at de.Keyle.MyPet.compat.v1_12_R1.entity.EntityMyPet.B_(EntityMyPet.java:1150)
	at net.minecraft.server.v1_12_R1.World.entityJoinedWorld(World.java:1643)
	at net.minecraft.server.v1_12_R1.World.h(World.java:1613)
	at net.minecraft.server.v1_12_R1.World.tickEntities(World.java:1437)
	at net.minecraft.server.v1_12_R1.WorldServer.tickEntities(WorldServer.java:665)
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:817)
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at de.Keyle.MyPet.compat.v1_12_R1.entity.EntityMyPet.a(EntityMyPet.java:1125)
	at de.Keyle.MyPet.compat.v1_12_R1.entity.EntityMyPet.n(EntityMyPet.java:949)
	at net.minecraft.server.v1_12_R1.EntityLiving.B_(EntityLiving.java:1939)
	at net.minecraft.server.v1_12_R1.EntityInsentient.B_(EntityInsentient.java:246)
	at de.Keyle.MyPet.compat.v1_12_R1.entity.EntityMyPet.B_(EntityMyPet.java:1150)
	at net.minecraft.server.v1_12_R1.World.entityJoinedWorld(World.java:1643)
	at net.minecraft.server.v1_12_R1.World.h(World.java:1613)

-- Entity being ticked --
Details:
	Entity Type: null (de.Keyle.MyPet.compat.v1_12_R1.entity.types.EntityMyParrot)
	Entity ID: 1380
	Entity Name: Parrot
	Entity's Exact location: -8396.39, 64.00, 2130.15
	Entity's Block location: World: (-8397,64,2130), Chunk: (at 3,4,2 in -525,133; contains blocks -8400,0,2128 to -8385,255,2143), Region: (-17,4; contains chunks -544,128 to -513,159, blocks -8704,0,2048 to -8193,255,2559)
	Entity's Momentum: 0.20, -0.08, -0.13
	Entity's Passengers: [EntityPlayer['Eternally_'/571, l='world', x=-8396.77, y=64.32, z=2130.38](Eternally_ at -8396.766633464993,64.32499998211861,2130.379771101453)]
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.server.v1_12_R1.World.tickEntities(World.java:1437)
	at net.minecraft.server.v1_12_R1.WorldServer.tickEntities(WorldServer.java:665)

-- Affected level --
Details:
	Level name: world
	All players: 2 total; [EntityPlayer['Eternally_'/571, l='world', x=-8396.77, y=64.32, z=2130.38](Eternally_ at -8396.766633464993,64.32499998211861,2130.379771101453), EntityPlayer['gdgfty'/679, l='world', x=-8401.96, y=65.51, z=2127.53](gdgfty at -8401.95622470206,65.50624999552966,2127.534810501996)]
	Chunk stats: ServerChunkCache: 135 Drop: 0
	Level seed: 8461523036666223995
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-139,69,252), Chunk: (at 5,4,12 in -9,15; contains blocks -144,0,240 to -129,255,255), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 36958500 game time, 37175938 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 100814 (now: false), thunder time: 170961 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:817)
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
	at java.lang.Thread.run(Unknown Source)

**Comment by xXKeyleXx** [comment]
Could you tell me the build number of MyPet? It's the (-b_XXXX_) part when you start the server.

**Comment by luzhenbin** [comment]
2.3.1-b1176

**Comment by xXKeyleXx** [comment]
Did you change the skilltrees?

**Comment by luzhenbin** [comment]
No , maybe I can delete the skilltrees and try it again . Wait a second

**Comment by xXKeyleXx** [comment]
I don't think this will help. Do you use vanilla Spigot?

**Comment by luzhenbin** [comment]
Yes , I built it with BuildTools.

**Comment by luzhenbin** [comment]
Unbelievable, I restarted the server, and then rode on a parrot, and the server didn't crash , But……

**Comment by xXKeyleXx** [comment]
I don't know why but if it works now I'm happy :D

**Comment by luzhenbin** [comment]
:D

**Comment by luzhenbin** [comment]
Hello, maybe I found the reason . When the player ride the pet If his position changes suddenly , it will cause mistakes . A player use the  elevator plugin , then the server crashed . This problem could be a spigot problem .
