### ISSUE TITLE
crash again..

### ISSUE THREAD

**Issue by tygh78071388** [xXKeyleXx/MyPet#1042]
Please provide the following info.

**Bukkit/Spigot/Bungee Build/Version:**spigot-1.11.2

**MyPet Build/Version:**MyPet-2.3.2-SNAPSHOT

**Do you use the premium version? (this wont change anything for you)** no

**What is the expected result?**

**What happens instead of that?**

**Error:**

[crash-2017-08-25_15.18.06-server.txt](https://github.com/xXKeyleXx/MyPet/files/1251125/crash-2017-08-25_15.18.06-server.txt)
```
``Cause of unexpected exception was
java.lang.NullPointerException
	at de.Keyle.MyPet.compat.v1_11_R1.entity.EntityMyPet.g(EntityMyPet.java:1129) ~[?:?]
	at de.Keyle.MyPet.compat.v1_11_R1.entity.EntityMyPet.n(EntityMyPet.java:950) ~[?:?]
	at net.minecraft.server.v1_11_R1.EntityLiving.A_(EntityLiving.java:1893) ~[spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.EntityInsentient.A_(EntityInsentient.java:244) ~[spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at de.Keyle.MyPet.compat.v1_11_R1.entity.EntityMyPet.A_(EntityMyPet.java:1152) ~[?:?]
	at net.minecraft.server.v1_11_R1.World.entityJoinedWorld(World.java:1631) ~[spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.World.h(World.java:1606) ~[spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.World.tickEntities(World.java:1432) ~[spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.WorldServer.tickEntities(WorldServer.java:618) ~[spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:814) ~[spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) ~[spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) ~[spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_141]
```

```
Encountered an unexpected exception
net.minecraft.server.v1_11_R1.ReportedException: Ticking entity
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:825) ~[spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) ~[spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) ~[spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_141]
Caused by: java.lang.NullPointerException
	at de.Keyle.MyPet.compat.v1_11_R1.entity.EntityMyPet.g(EntityMyPet.java:1129) ~[?:?]
	at de.Keyle.MyPet.compat.v1_11_R1.entity.EntityMyPet.n(EntityMyPet.java:950) ~[?:?]
	at net.minecraft.server.v1_11_R1.EntityLiving.A_(EntityLiving.java:1893) ~[spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.EntityInsentient.A_(EntityInsentient.java:244) ~[spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at de.Keyle.MyPet.compat.v1_11_R1.entity.EntityMyPet.A_(EntityMyPet.java:1152) ~[?:?]
	at net.minecraft.server.v1_11_R1.World.entityJoinedWorld(World.java:1631) ~[spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.World.h(World.java:1606) ~[spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.World.tickEntities(World.java:1432) ~[spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.WorldServer.tickEntities(WorldServer.java:618) ~[spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:814) ~[spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	... 4 more
```

**Comment by xXKeyleXx** [comment]
I'm sorry that this happens but I hope I fixed it now... for real.

**Comment by tygh78071388** [comment]
THX!
