### ISSUE TITLE
Entity threw exception

### ISSUE THREAD

**Issue by andris155** [xXKeyleXx/MyPet#1045]
Please provide the following info.

**Bukkit/Spigot/Bungee Build/Version:**
git-Paper-1179 (MC: 1.12.1)

**MyPet Build/Version:**
MyPet-Premium-2.3.6

**Do you use the premium version? (this wont change anything for you)**
yes

**What is the expected result?**
MyPet no write error

**What happens instead of that?**
MyPet write error

**Error:**
```
[09:37:51] [Server thread/WARN]: Entity threw exception at plotworld:-569.4943729697646,65.0,1193.664889699911
[09:37:51] [Server thread/WARN]: java.lang.NullPointerException
[09:37:51] [Server thread/WARN]: 	at de.Keyle.MyPet.compat.v1_12_R1.entity.EntityMyPet.a(EntityMyPet.java:1151)
[09:37:51] [Server thread/WARN]: 	at de.Keyle.MyPet.compat.v1_12_R1.entity.EntityMyPet.n(EntityMyPet.java:952)
[09:37:51] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.EntityLiving.B_(EntityLiving.java:1960)
[09:37:51] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.EntityInsentient.B_(EntityInsentient.java:247)
[09:37:51] [Server thread/WARN]: 	at de.Keyle.MyPet.compat.v1_12_R1.entity.EntityMyPet.B_(EntityMyPet.java:1188)
[09:37:51] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.World.entityJoinedWorld(World.java:1753)
[09:37:51] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.World.h(World.java:1723)
[09:37:51] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.World.tickEntities(World.java:1538)
[09:37:51] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.WorldServer.tickEntities(WorldServer.java:675)
[09:37:51] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:913)
[09:37:51] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:424)
[09:37:51] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767)
[09:37:51] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665)
[09:37:51] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
```

```
[11:40:14] [Server thread/WARN]: Entity threw exception at world:7969.082509423936,66.0,-596.2000000029802
[11:40:14] [Server thread/WARN]: java.lang.NullPointerException
[11:40:14] [Server thread/WARN]: 	at de.Keyle.MyPet.compat.v1_12_R1.entity.EntityMyPet.a(EntityMyPet.java:1149)
[11:40:14] [Server thread/WARN]: 	at de.Keyle.MyPet.compat.v1_12_R1.entity.EntityMyPet.n(EntityMyPet.java:952)
[11:40:14] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.EntityLiving.B_(EntityLiving.java:1960)
[11:40:14] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.EntityInsentient.B_(EntityInsentient.java:247)
[11:40:14] [Server thread/WARN]: 	at de.Keyle.MyPet.compat.v1_12_R1.entity.EntityMyPet.B_(EntityMyPet.java:1188)
[11:40:14] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.World.entityJoinedWorld(World.java:1753)
[11:40:14] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.World.h(World.java:1723)
[11:40:14] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.World.tickEntities(World.java:1538)
[11:40:14] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.WorldServer.tickEntities(WorldServer.java:675)
[11:40:14] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:913)
[11:40:14] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:424)
[11:40:14] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767)
[11:40:14] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665)
[11:40:14] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by xXKeyleXx** [comment]
Please try the latest dev build: https://mypet-plugin.de/download

**Comment by Julianvand** [comment]
We had the same problem on our server were MyPet crashed it around 8 times in 2 days. Updating from 2.3.1 to the latest dev build has resolved it (we haven't had a crash in the past 24 hours).
