### ISSUE TITLE
when we ride our own pets, the error occurs

### ISSUE THREAD

**Issue by rirubear** [xXKeyleXx/MyPet#1071]
Please provide the following info.

**Bukkit/Spigot/Bungee Build/Version:**
Spigot 1.12.2

**MyPet Build/Version:**
MyPet-Premium-2.3.7

**Do you use the premium version? (this wont change anything for you)**
yes

**What is the expected result?**
We want to fix the error.

**What happens instead of that?**

**Error:**
`[18:53:06 ERROR]: Could not pass event PlayerInteractEvent to EasyCarts v1.12.2
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-93e20b3-31d3159]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-93e20b3-31d3159]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [spigot.jar:git-Spigot-93e20b3-31d3159]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [spigot.jar:git-Spigot-93e20b3-31d3159]
        at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:234) [spigot.jar:git-Spigot-93e20b3-31d3159]
        at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:201) [spigot.jar:git-Spigot-93e20b3-31d3159]
        at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:197) [spigot.jar:git-Spigot-93e20b3-31d3159]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:989) [spigot.jar:git-Spigot-93e20b3-31d3159]
        at net.minecraft.server.v1_12_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:26) [spigot.jar:git-Spigot-93e20b3-31d3159]
        at net.minecraft.server.v1_12_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:1) [spigot.jar:git-Spigot-93e20b3-31d3159]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-93e20b3-31d3159]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_151]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_151]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot.jar:git-Spigot-93e20b3-31d3159]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot.jar:git-Spigot-93e20b3-31d3159]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot.jar:git-Spigot-93e20b3-31d3159]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot.jar:git-Spigot-93e20b3-31d3159]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot.jar:git-Spigot-93e20b3-31d3159]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]
Caused by: java.lang.ClassCastException: de.Keyle.MyPet.compat.v1_12_R1.entity.CraftMyPet cannot be cast to org.bukkit.entity.Vehicle
        at com.github.xericore.easycarts.PlayerClickListener.onMyPlayerInteract(PlayerClickListener.java:39) ~[EasyCarts.jar:?]
        at sun.reflect.GeneratedMethodAccessor184.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_151]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_151]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot.jar:git-Spigot-93e20b3-31d3159]
        ... 18 more`

**Comment by xXKeyleXx** [comment]
Problem is not cause by MyPet but EasyCarts.
