### ISSUE TITLE
Riding pet crashes server.

### ISSUE THREAD

**Issue by velmeran** [xXKeyleXx/MyPet#1074]
Please provide the following info.

**Bukkit/Spigot/Bungee Build/Version:**
 This server is running CraftBukkit version git-Spigot-65e8124-79e55b6 (MC: 1.12.1) (Implementing API version 1.12.1-R0.1-SNAPSHOT)

**MyPet Build/Version:**
2.3.1
**Do you use the premium version? (this wont change anything for you)**
No, just free at the moment.
**What is the expected result?**
Server doesn't crash due to riding pets.
**What happens instead of that?**
One players pet chicken, looks to be crashing the whole server hard while being ridden.
**Error:**
---- Minecraft Crash Report ----
// There are four lights!

Time: 11/15/17 4:02 PM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at de.Keyle.MyPet.compat.v1_12_R1.entity.EntityMyPet.a(EntityMyPet.java:1125)
	at de.Keyle.MyPet.compat.v1_12_R1.entity.EntityMyPet.n(EntityMyPet.java:949)
	at net.minecraft.server.v1_12_R1.EntityLiving.B_(EntityLiving.java:1939)
	at net.minecraft.server.v1_12_R1.EntityInsentient.B_(EntityInsentient.java:246)
	at de.Keyle.MyPet.compat.v1_12_R1.entity.EntityMyPet.B_(EntityMyPet.java:1150)
	at net.minecraft.server.v1_12_R1.World.entityJoinedWorld(World.java:1643)
	at net.minecraft.server.v1_12_R1.World.h(World.java:1613)
	at net.minecraft.server.v1_12_R1.World.tickEntities(World.java:1437)
	at net.minecraft.server.v1_12_R1.WorldServer.tickEntities(WorldServer.java:665)
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:817)
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at de.Keyle.MyPet.compat.v1_12_R1.entity.EntityMyPet.a(EntityMyPet.java:1125)
	at de.Keyle.MyPet.compat.v1_12_R1.entity.EntityMyPet.n(EntityMyPet.java:949)
	at net.minecraft.server.v1_12_R1.EntityLiving.B_(EntityLiving.java:1939)
	at net.minecraft.server.v1_12_R1.EntityInsentient.B_(EntityInsentient.java:246)
	at de.Keyle.MyPet.compat.v1_12_R1.entity.EntityMyPet.B_(EntityMyPet.java:1150)
	at net.minecraft.server.v1_12_R1.World.entityJoinedWorld(World.java:1643)
	at net.minecraft.server.v1_12_R1.World.h(World.java:1613)

-- Entity being ticked --
Details:
	Entity Type: null (de.Keyle.MyPet.compat.v1_12_R1.entity.types.EntityMyChicken)
	Entity ID: 2453
	Entity Name: §5Seedo§r
	Entity's Exact location: -251.51, 64.00, 478.40
	Entity's Block location: World: (-252,64,478), Chunk: (at 4,4,14 in -16,29; contains blocks -256,0,464 to -241,255,479), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Entity's Momentum: 0.06, -0.08, 0.25
	Entity's Passengers: [EntityPlayer['KittyCandy83'/1827, l='world', x=-251.62, y=64.17, z=477.95](KittyCandy83 at -251.61949079690686,64.17499999105931,477.9509844689724)]
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.server.v1_12_R1.World.tickEntities(World.java:1437)
	at net.minecraft.server.v1_12_R1.WorldServer.tickEntities(WorldServer.java:665)

[2017-11-15-3.log](https://github.com/xXKeyleXx/MyPet/files/1483593/2017-11-15-3.log)
[2017-11-15-1.log](https://github.com/xXKeyleXx/MyPet/files/1483594/2017-11-15-1.log)
[MyPet.log](https://github.com/xXKeyleXx/MyPet/files/1483595/MyPet.log)
[crash-2017-11-15_15.59.51-server.txt](https://github.com/xXKeyleXx/MyPet/files/1483596/crash-2017-11-15_15.59.51-server.txt)
[crash-2017-11-15_16.02.41-server.txt](https://github.com/xXKeyleXx/MyPet/files/1483597/crash-2017-11-15_16.02.41-server.txt)
[crash-2017-11-15_16.04.59-server.txt](https://github.com/xXKeyleXx/MyPet/files/1483598/crash-2017-11-15_16.04.59-server.txt)
[2017-11-15-2.log](https://github.com/xXKeyleXx/MyPet/files/1483599/2017-11-15-2.log)

**Comment by xXKeyleXx** [comment]
Update to the latest version please.
