### ISSUE TITLE
 [Server thread/ERROR]

### ISSUE THREAD

**Issue by nungsorb** [xXKeyleXx/MyPet#1128]
Please provide the following info.

**Bukkit/Spigot/Bungee Build/Version:**
1.12.2
**MyPet Build/Version:**
D1
**Do you use the premium version? (this wont change anything for you)**
yep
**What is the expected result?**
/mypet 
**What happens instead of that?**
Error
**Error:**
[21:14:04] [Server thread/INFO]: Chuvy issued server command: /mypet
[21:14:04] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Cannot execute command 'mypet' in plugin MyPet v2.3.4 - plugin is disabled.
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:36) ~[spigot-1.12.2.jar:git-Spigot-2086bb0-8cc5a7e]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.12.2.jar:git-Spigot-2086bb0-8cc5a7e]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:648) ~[spigot-1.12.2.jar:git-Spigot-2086bb0-8cc5a7e]
	at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1397) [spigot-1.12.2.jar:git-Spigot-2086bb0-8cc5a7e]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1232) [spigot-1.12.2.jar:git-Spigot-2086bb0-8cc5a7e]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.12.2.jar:git-Spigot-2086bb0-8cc5a7e]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.12.2.jar:git-Spigot-2086bb0-8cc5a7e]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.12.2.jar:git-Spigot-2086bb0-8cc5a7e]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_161]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_161]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot-1.12.2.jar:git-Spigot-2086bb0-8cc5a7e]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot-1.12.2.jar:git-Spigot-2086bb0-8cc5a7e]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-2086bb0-8cc5a7e]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-2086bb0-8cc5a7e]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-2086bb0-8cc5a7e]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
[21:14:07] [Server thread/INFO]: Chuvy issued server command: /mypets

**Comment by xXKeyleXx** [comment]
The plugin is not enabled. I need the error when the plugin gets loaded.

**Comment by zerafox** [comment]
2.3.4 is also a Free Version of the plugin as well. Not Premium.

**Comment by nungsorb** [comment]
It is free version ??
![image](https://user-images.githubusercontent.com/40270785/41464595-183981ee-70c5-11e8-8da1-38b6679060c0.png)

**Comment by nungsorb** [comment]
For 1.11.2
![image](https://user-images.githubusercontent.com/40270785/41464728-81c9b21e-70c5-11e8-859c-0fb94c058d65.png)

**Comment by xXKeyleXx** [comment]
The latest premium version is  2.3.9. You can only download it from this page: https://mypet-plugin.de/download
If you bought premium you got a key that allows you to download the latest version.
If the problem persists please show me the fill server log (pastebin)
