### ISSUE TITLE
MyPet bug while taking pet back from the storage

### ISSUE THREAD

**Issue by JackWisdom** [xXKeyleXx/MyPet#1148]
Please provide the following info.

**Bukkit/Spigot/Bungee Build/Version:**
1.13
**MyPet Build/Version:**
3.0 b587p
**Do you use the premium version? (this wont change anything for you)**
yes
**What is the expected result?**
I'm using mypet-npc to storge my pet,
I should have get mypet back after I click the "PET-TAKING" wool
**What happens instead of that?**
I did't get my pet back and errors in console
**Error:**
rg.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:308) ~[mc.jar:git-Spigot-69774b3-ec2095d]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[mc.jar:git-Spigot-69774b3-ec2095d]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) ~[mc.jar:git-Spigot-69774b3-ec2095d]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) ~[mc.jar:git-Spigot-69774b3-ec2095d]
        at net.minecraft.server.v1_13_R1.PlayerConnection.a(PlayerConnection.java:2130) ~[mc.jar:git-Spigot-69774b3-ec2095d]
        at net.minecraft.server.v1_13_R1.PacketPlayInWindowClick.a(SourceFile:33) ~[mc.jar:git-Spigot-69774b3-ec2095d]
        at net.minecraft.server.v1_13_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[mc.jar:git-Spigot-69774b3-ec2095d]
        at net.minecraft.server.v1_13_R1.PlayerConnectionUtils.a(SourceFile:10) ~[mc.jar:git-Spigot-69774b3-ec2095d]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_181]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_181]
        at net.minecraft.server.v1_13_R1.SystemUtils.a(SourceFile:198) [mc.jar:git-Spigot-69774b3-ec2095d]
        at net.minecraft.server.v1_13_R1.MinecraftServer.w(MinecraftServer.java:884) [mc.jar:git-Spigot-69774b3-ec2095d]
        at net.minecraft.server.v1_13_R1.DedicatedServer.w(DedicatedServer.java:411) [mc.jar:git-Spigot-69774b3-ec2095d]
        at net.minecraft.server.v1_13_R1.MinecraftServer.v(MinecraftServer.java:819) [mc.jar:git-Spigot-69774b3-ec2095d]
        at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:717) [mc.jar:git-Spigot-69774b3-ec2095d]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.NoSuchMethodError: de.Keyle.MyPet.api.repository.MyPetManager.activateMyPet(Lde/Keyle/MyPet/api/entity/StoredMyPet;)Lcom/google/common/base/Optional;
        at de.keyle.mypet.npc.traits.StorageTrait$2$1.callback(StorageTrait.java:217) ~[?:?]
        at de.keyle.mypet.npc.traits.StorageTrait$2$1.callback(StorageTrait.java:214) ~[?:?]
        at de.Keyle.MyPet.gui.selectionmenu.MyPetSelectionGui.lambda$open$0(MyPetSelectionGui.java:114) ~[?:?]
        at de.Keyle.MyPet.api.gui.IconMenu.on(IconMenu.java:144) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_181]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304) ~[mc.jar:git-Spigot-69774b3-ec2095d]
        ... 15 more

**Comment by xXKeyleXx** [comment]
Latest dev build of MyPet-NPC has the fix
