### ISSUE TITLE
Paper 1.13.1 petcall error

### ISSUE THREAD

**Issue by MimacalMi** [xXKeyleXx/MyPet#1162]
[16:16:56] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'petcall' in plugin MyPet v3.0
	
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[patched_1.13.1.jar:git-Paper-258]
	
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151) ~[patched_1.13.1.jar:git-Paper-258]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:726) ~[patched_1.13.1.jar:git-Paper-258]
	
at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1768) ~[patched_1.13.1.jar:git-Paper-258]
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1572) ~[patched_1.13.1.jar:git-Paper-258]
	
at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[patched_1.13.1.jar:git-Paper-258]
	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.13.1.jar:git-Paper-258]
	
at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:12) ~[patched_1.13.1.jar:git-Paper-258]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_181]
	
at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_181]
	at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) ~[patched_1.13.1.jar:git-Paper-258]
	
at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1014) ~[patched_1.13.1.jar:git-Paper-258]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:428) ~[patched_1.13.1.jar:git-Paper-258]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:941) ~[patched_1.13.1.jar:git-Paper-258]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:839) ~[patched_1.13.1.jar:git-Paper-258]
	
at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]
Caused by: java.lang.NullPointerException
	
at de.Keyle.MyPet.entity.MyPet.createEntity(MyPet.java:514) ~[?:?]
	
at de.Keyle.MyPet.commands.CommandCall.onCommand(CommandCall.java:45) ~[?:?]
	
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[patched_1.13.1.jar:git-Paper-258]
	... 15 more

**Comment by xXKeyleXx** [comment]
The template is there for a reason 😞

**Comment by xXKeyleXx** [comment]
Did you do a restart or a reload of the server?

**Comment by MimacalMi** [comment]
>           Did you do a restart or a reload of the server?
No. It's in a running time

**Comment by MimacalMi** [comment]
Ah Now solved that update to paper build.
Sorry :D
