### ISSUE TITLE
Mysql cannot load, compatibility issue between Hikari lib and paperspigot

### ISSUE THREAD

**Issue by tianji1993** [xXKeyleXx/MyPet#1194]
Please provide the following info.

**Bukkit/Spigot/Bungee Build/Version:**
Spigot git-Spigot-a1f2566-282dad1 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
PaperSpigot 1.13.2 build#469
**MyPet Build/Version:**
3.0
**Do you use the premium version? (this wont change anything for you)**
yes
**What is the expected result?**
sql shoule works
**What happens instead of that?**
sql cannot load under PaperSpigot but can be load under Spigot.
**Error:**
 I wonder if there have some compatibility issue between Hikari lib and paperspigot.
**under paperspigot:**
[03:08:08] [Server thread/INFO]: [de.Keyle.MyPet.MyPetPlugin] [MyPet] Connect to MySQL database...
[03:08:38] [Server thread/WARN]: java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30000ms.
[03:08:38] [Server thread/WARN]: at de.Keyle.MyPet.util.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:676)
[03:08:38] [Server thread/WARN]: at de.Keyle.MyPet.util.hikari.pool.HikariPool.getConnection(HikariPool.java:190)
[03:08:38] [Server thread/WARN]: at de.Keyle.MyPet.util.hikari.pool.HikariPool.getConnection(HikariPool.java:155)
[03:08:38] [Server thread/WARN]: at de.Keyle.MyPet.util.hikari.HikariDataSource.getConnection(HikariDataSource.java:128)
[03:08:38] [Server thread/WARN]: at de.Keyle.MyPet.repository.types.MySqlRepository.updateInfo(MySqlRepository.java:337)
[03:08:38] [Server thread/WARN]: at de.Keyle.MyPet.repository.types.MySqlRepository.init(MySqlRepository.java:86)
[03:08:38] [Server thread/WARN]: at de.Keyle.MyPet.MyPetPlugin.onEnable(MyPetPlugin.java:313)
[03:08:38] [Server thread/WARN]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254)
[03:08:38] [Server thread/WARN]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:325)
[03:08:38] [Server thread/WARN]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[03:08:38] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:441)
[03:08:38] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:355)
[03:08:38] [Server thread/WARN]: at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:613)
[03:08:38] [Server thread/WARN]: at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:575)
[03:08:38] [Server thread/WARN]: at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:435)
[03:08:38] [Server thread/WARN]: at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:316)
[03:08:38] [Server thread/WARN]: at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:791)
[03:08:38] [Server thread/WARN]: at java.lang.Thread.run(Thread.java:748)
**under spigot:**
[03:11:34] [Server thread/INFO]: [[0;32;22mMyPet[m] [mEnabling MyPet v3.0[m
[03:11:40] [Server thread/INFO]: [[0;32;22mMyPet[m] [m################################################[m
[03:11:40] [Server thread/INFO]: [[0;32;22mMyPet[m] [m# A new build is available: 3.0-SNAPSHOT #641 #[m
[03:11:40] [Server thread/INFO]: [[0;32;22mMyPet[m] [m# https://mypet-plugin.de/download #[m
[03:11:40] [Server thread/INFO]: [[0;32;22mMyPet[m] [m################################################[m
[03:11:40] [Server thread/INFO]: [[0;32;22mMyPet[m] [mCompat mode for v1_13_R2 loaded.[m
[03:11:41] [Server thread/INFO]: [[0;32;22mMyPet[m] [mExp calculation mode: MyPet[m
[03:11:41] [Server thread/INFO]: [[0;32;22mMyPet[m] [mConnect to MySQL database...[m
[03:11:41] [Server thread/INFO]: [[0;32;22mMyPet[m] [mMySQL connection successful.[m

**Comment by tianji1993** [comment]
BTW, I found the same problem in another plugin called LuckPerms, hope this could help you: https://github.com/lucko/LuckPerms/issues/1295
the same Hikari lib is using and the same problem happens.

**Comment by xXKeyleXx** [comment]
I will wait and see what happens in https://github.com/PaperMC/Paper/issues/1715
