### ISSUE TITLE
Contents in shulker boxes in pet backpacks lost after data conversion

### ISSUE THREAD

**Issue by Akiranya** [xXKeyleXx/MyPet#1206]
Please provide the following info.

Please use the `/petadmin ticket` command and attach the generated `ticket.zip` to this issue.

**Bukkit/Spigot/Bungee Build/Version:**
`git-Paper-498 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)`

**MyPet Build/Version:**
`MyPet-3.0-SNAPSHOT-b#697`

**Do you use the premium version? (this wont change anything for you)**
Yes

**What is the expected result?**
shulker boxes in pet backpack should retain their contents after data conversion (SQLite -> MySQL)

**What happens instead of that?**
shulker boxes do not retain their contents after data conversion. They lost all of contents when I convert SQLite to MySQL. It was just the contents which lost. Shulker boxes themselves did not. Players still could see shulker boxes in their pet backpack after data conversion.

**Error:**
No errors seen in console.

[ticket.zip](https://github.com/xXKeyleXx/MyPet/files/2751881/ticket.zip)

**Comment by xXKeyleXx** [comment]
I just tried it and it converted fine for me. Everything was there after conversion.

Did you also upgrade your MC version?

**Comment by Akiranya** [comment]
No, but I upgraded paper and mypet.

And here is what I did literally from beginning to end:

At the very beginning, mypet threw errors below when a player started a trade with others:

```
[22:23:34] [Craft Scheduler Thread - 567/WARN]: org.sqlite.SQLiteException: [SQLITE_READONLY]  Attempt to write a readonly database (attempt to write a readonly database)
[22:23:34] [Craft Scheduler Thread - 567/WARN]: 	at org.sqlite.core.DB.newSQLException(DB.java:941)
[22:23:34] [Craft Scheduler Thread - 567/WARN]: 	at org.sqlite.core.DB.newSQLException(DB.java:953)
[22:23:34] [Craft Scheduler Thread - 567/WARN]: 	at org.sqlite.core.DB.execute(DB.java:857)
[22:23:34] [Craft Scheduler Thread - 567/WARN]: 	at org.sqlite.core.DB.executeUpdate(DB.java:895)
[22:23:34] [Craft Scheduler Thread - 567/WARN]: 	at org.sqlite.jdbc3.JDBC3PreparedStatement.executeUpdate(JDBC3PreparedStatement.java:102)
[22:23:34] [Craft Scheduler Thread - 567/WARN]: 	at de.Keyle.MyPet.repository.types.SqLiteRepository.updatePlayer(SqLiteRepository.java:901)
[22:23:34] [Craft Scheduler Thread - 567/WARN]: 	at de.Keyle.MyPet.repository.types.SqLiteRepository$13.run(SqLiteRepository.java:861)
[22:23:34] [Craft Scheduler Thread - 567/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:82)
[22:23:34] [Craft Scheduler Thread - 567/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[22:23:34] [Craft Scheduler Thread - 567/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[22:23:34] [Craft Scheduler Thread - 567/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[22:23:34] [Craft Scheduler Thread - 567/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[22:23:34] [Craft Scheduler Thread - 567/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[22:23:34] [Craft Scheduler Thread - 563/WARN]: org.sqlite.SQLiteException: [SQLITE_READONLY]  Attempt to write a readonly database (attempt to write a readonly database)
[22:23:34] [Craft Scheduler Thread - 563/WARN]: 	at org.sqlite.core.DB.newSQLException(DB.java:941)
[22:23:34] [Craft Scheduler Thread - 563/WARN]: 	at org.sqlite.core.DB.newSQLException(DB.java:953)
[22:23:34] [Craft Scheduler Thread - 563/WARN]: 	at org.sqlite.core.DB.execute(DB.java:857)
[22:23:34] [Craft Scheduler Thread - 563/WARN]: 	at org.sqlite.core.DB.executeUpdate(DB.java:895)
[22:23:34] [Craft Scheduler Thread - 563/WARN]: 	at org.sqlite.jdbc3.JDBC3PreparedStatement.executeUpdate(JDBC3PreparedStatement.java:102)
[22:23:34] [Craft Scheduler Thread - 563/WARN]: 	at de.Keyle.MyPet.repository.types.SqLiteRepository$9.run(SqLiteRepository.java:701)
[22:23:34] [Craft Scheduler Thread - 563/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:82)
[22:23:34] [Craft Scheduler Thread - 563/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[22:23:34] [Craft Scheduler Thread - 563/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[22:23:34] [Craft Scheduler Thread - 563/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[22:23:34] [Craft Scheduler Thread - 563/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[22:23:34] [Craft Scheduler Thread - 563/WARN]: 	at java.lang.Thread.run(Thread.java:748)
```

(Below was actually another bug, but I managed to fix it myself by switching to MySQL)

That is, when player A sold a pet to player B, player B could receive the pet, but player A didn't lose that which is still in player A's backpack. Player A still had the amount of pets as he already had before. Meanwhile, player B didn't have any pet when they were doing the trade (I am not sure if it could be considered as a prerequisite, but I think it's better let you know).

Because apparently it was a error about SQLite, so I switched to MySQL.

Then I stopped my server and upgraded paper and mypet, meanwhile I edited the config of mypet to switch to MySQL, and started the server. After that, everything seemed fine until a player told me that he lost all of his items in shulker boxes which were in pet's backpacks.

Sorry for such a messy bug report...

The good news is that with MySQL the 'trade bug' has been fixed and have worked really well.

**Comment by xXKeyleXx** [comment]
Did this always happen when you trade and only when you trade?

In theory it shouldn't matter if the pet is in an SQLite or MySQL database and the transfer should never have these result.

**Comment by Akiranya** [comment]
Sorry but I am not quite sure. It was a player who told me that he found a bug, so I just started watching the console where these errors were just keeping coming up when they were trading. At that time, it was using SQLite.

**Comment by xXKeyleXx** [comment]
Yeah I guess that's what I will do 🤷‍♂️
