### ISSUE TITLE
MyPet doesn't work

### ISSUE THREAD

**Issue by JohnStriker** [xXKeyleXx/MyPet#1207]
Hi there, I have problem with MyPet plugin. Plugin is displayed like active in /pl but i doesn't work. I can't use any command and any feature of this plugin. Can you help me?

As I said I can't use any commands, so I couldn't use /petadmin ticket so there are 2 logs from console.

`[23:28:21 INFO]: [MyPet] Loading MyPet v2.3.5
[23:28:22 ERROR]: sun.reflect.annotation.EnumConstantNotPresentExceptionProxy initializing MyPet v2.3.5 (Is it up to date?)
java.lang.ArrayStoreException: sun.reflect.annotation.EnumConstantNotPresentExceptionProxy
at sun.reflect.annotation.AnnotationParser.parseEnumArray(AnnotationParser.java:744) ~[?:1.8.0_152]
at sun.reflect.annotation.AnnotationParser.parseArray(AnnotationParser.java:533) ~[?:1.8.0_152]
at sun.reflect.annotation.AnnotationParser.parseMemberValue(AnnotationParser.java:355) ~[?:1.8.0_152]
at sun.reflect.annotation.AnnotationParser.parseAnnotation2(AnnotationParser.java:286) ~[?:1.8.0_152]
at sun.reflect.annotation.AnnotationParser.parseAnnotations2(AnnotationParser.java:120) ~[?:1.8.0_152]
at sun.reflect.annotation.AnnotationParser.parseAnnotations(AnnotationParser.java:72) ~[?:1.8.0_152]
at java.lang.Class.createAnnotationData(Class.java:3521) ~[?:1.8.0_152]
at java.lang.Class.annotationData(Class.java:3510) ~[?:1.8.0_152]
at java.lang.Class.getAnnotation(Class.java:3415) ~[?:1.8.0_152]
at de.Keyle.MyPet.util.ConfigurationLoader.setDefault(ConfigurationLoader.java:193) ~[?:?]
at de.Keyle.MyPet.MyPetPlugin.onLoad(MyPetPlugin.java:110) ~[?:?]
at org.bukkit.craftbukkit.v1_13_R2.CraftServer.loadPlugins(CraftServer.java:328) [minecraft_server.jar:git-Spigot-a1f2566-6a398ac]
at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:213) [minecraft_server.jar:git-Spigot-a1f2566-6a398ac]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:702) [minecraft_server.jar:git-Spigot-a1f2566-6a398ac]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]`

`[23:28:41 INFO]: [MyPet] Enabling MyPet v2.3.5
[23:28:41 INFO]: [MyPet] No Update available.
[23:28:41 ERROR]: Error occurred while enabling MyPet v2.3.5 (Is it up to date?)
java.lang.NullPointerException: null
at de.Keyle.MyPet.MyPetPlugin.onEnable(MyPetPlugin.java:143) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254) ~[minecraft_server.jar:git-Spigot-a1f2566-6a398ac]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:339) [minecraft_server.jar:git-Spigot-a1f2566-6a398ac]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [minecraft_server.jar:git-Spigot-a1f2566-6a398ac]
at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:434) [minecraft_server.jar:git-Spigot-a1f2566-6a398ac]
at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:348) [minecraft_server.jar:git-Spigot-a1f2566-6a398ac]
at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:584) [minecraft_server.jar:git-Spigot-a1f2566-6a398ac]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:546) [minecraft_server.jar:git-Spigot-a1f2566-6a398ac]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:424) [minecraft_server.jar:git-Spigot-a1f2566-6a398ac]
at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:294) [minecraft_server.jar:git-Spigot-a1f2566-6a398ac]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:702) [minecraft_server.jar:git-Spigot-a1f2566-6a398ac]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]`

Spigot 1.13.2 

MyPet 2.3.5

**Comment by zerafox** [comment]
You need to use 3.0 Dev Build to run on a 1.13 server.
Update MyPet

**Comment by JohnStriker** [comment]
Ok, I'll try it. Thanks.
 What about MyPet-NPC? It's included in MyPet now? So I don't need to dowland MyPet-NPC?

**Comment by xXKeyleXx** [comment]
That's correct. Please delete MyPet-NPC from your server.
