### ISSUE TITLE
SQlite DB Exception

### ISSUE THREAD

**Issue by Sn0wStorm** [xXKeyleXx/MyPet#1212]
**Bukkit/Spigot/Bungee Build/Version:**
Newest Spigot as of 03.Feb.19

**MyPet Build/Version:**
v3.0 b1383

**Do you use the premium version? (this wont change anything for you)**
No

**What is the expected result?**
All Pets keeping their name and Level, */petlist Player* showing Pets of the Player

**What happens instead of that?**
*/petlist Player* shows Player doesnt have a Pet and an exception is generated
All Level and Names of Pets are reset

This Happened when updating from build 1349 to 1383
Issue still persists right after converting from old nbt database, which completes without error

**Error:**
`[13:58:18 WARN]: org.sqlite.SQLiteException: [SQLITE_CONSTRAINT]  Abort due to constraint violation (UNIQUE constraint failed: players.name)
[13:58:18 WARN]: 	at org.sqlite.core.DB.newSQLException(DB.java:941)
[13:58:18 WARN]: 	at org.sqlite.core.DB.newSQLException(DB.java:953)
[13:58:18 WARN]: 	at org.sqlite.core.DB.execute(DB.java:854)
[13:58:18 WARN]: 	at org.sqlite.core.DB.executeUpdate(DB.java:895)
[13:58:18 WARN]: 	at org.sqlite.jdbc3.JDBC3PreparedStatement.executeUpdate(JDBC3PreparedStatement.java:102)
[13:58:18 WARN]: 	at de.Keyle.MyPet.repository.types.SqLiteRepository$14.run(SqLiteRepository.java:953)
[13:58:18 WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:81)
[13:58:18 WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[13:58:18 WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[13:58:18 WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[13:58:18 WARN]: 	at java.lang.Thread.run(Thread.java:748)`

**Comment by xXKeyleXx** [comment]
Could you attach your pets.db file please.

**Comment by Sn0wStorm** [comment]
Here you go
[pets.db.zip](https://github.com/xXKeyleXx/MyPet/files/2832298/pets.db.zip)

**Comment by xXKeyleXx** [comment]
Could I get the full serverlog?

**Comment by Sn0wStorm** [comment]
No other Errors appear related to that and the same db works fine in b1349

[2019-02-03-3.log.gz](https://github.com/xXKeyleXx/MyPet/files/2832357/2019-02-03-3.log.gz)

**Comment by xXKeyleXx** [comment]
I pushed some changes that will tell me more info when the error happens again. Could you please put that version (latest dev build) on your server and show me the logs again when it happens.

**Comment by Sn0wStorm** [comment]
This was in the Log now, but i cant reproduce it on my test server properly

`[16:50:32 WARN]: org.sqlite.SQLiteException: [SQLITE_CONSTRAINT]  Abort due to constraint violation (UNIQUE constraint failed: players.name)
[16:50:32 WARN]: 	at org.sqlite.core.DB.newSQLException(DB.java:941)
[16:50:32 WARN]: 	at org.sqlite.core.DB.newSQLException(DB.java:953)
[16:50:32 WARN]: 	at org.sqlite.core.DB.execute(DB.java:854)
[16:50:32 WARN]: 	at org.sqlite.core.DB.executeUpdate(DB.java:895)
[16:50:32 WARN]: 	at org.sqlite.jdbc3.JDBC3PreparedStatement.executeUpdate(JDBC3PreparedStatement.java:102)
[16:50:32 WARN]: 	at de.Keyle.MyPet.repository.types.SqLiteRepository$14.run(SqLiteRepository.java:955)
[16:50:32 WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:81)
[16:50:32 WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[16:50:32 WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[16:50:32 WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[16:50:32 WARN]: 	at java.lang.Thread.run(Thread.java:748)
[16:50:32 INFO]: [MyPet] Exception Info: org.sqlite.jdbc4.JDBC4PreparedStatement@25889868
[16:50:32 INFO]: [MyPet] UUID: cd079884-ee6a-4a5a-bad6-2d6bf97cc3fd
[16:50:32 INFO]: [MyPet] Name: Flyero
[16:50:32 INFO]: [MyPet] Mojang: aa990b42-a120-4051-ad25-81707cc9d044
[16:50:32 INFO]: [MyPet] callback: null`
