### ISSUE TITLE
plugman eror

### ISSUE THREAD

**Issue by successed** [xXKeyleXx/MyPet#1220]
[12:38:19 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'plugman' in plugin PlugMan v2.1.5
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[patched_1.13.2.jar:git-Paper-525]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[patched_1.13.2.jar:git-Paper-525]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:734) ~[patched_1.13.2.jar:git-Paper-525]
        at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1797) ~[patched_1.13.2.jar:git-Paper-525]
        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1605) ~[patched_1.13.2.jar:git-Paper-525]
        at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[patched_1.13.2.jar:git-Paper-525]
        at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.13.2.jar:git-Paper-525]
        at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:15) ~[patched_1.13.2.jar:git-Paper-525]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_191]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_191]
        at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108) ~[patched_1.13.2.jar:git-Paper-525]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1011) ~[patched_1.13.2.jar:git-Paper-525]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-525]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:938) ~[patched_1.13.2.jar:git-Paper-525]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:836) ~[patched_1.13.2.jar:git-Paper-525]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
Caused by: java.lang.ArrayStoreException: sun.reflect.annotation.EnumConstantNotPresentExceptionProxy
        at sun.reflect.annotation.AnnotationParser.parseEnumArray(AnnotationParser.java:744) ~[?:1.8.0_191]
        at sun.reflect.annotation.AnnotationParser.parseArray(AnnotationParser.java:533) ~[?:1.8.0_191]
        at sun.reflect.annotation.AnnotationParser.parseMemberValue(AnnotationParser.java:355) ~[?:1.8.0_191]
        at sun.reflect.annotation.AnnotationParser.parseAnnotation2(AnnotationParser.java:286) ~[?:1.8.0_191]
        at sun.reflect.annotation.AnnotationParser.parseAnnotations2(AnnotationParser.java:120) ~[?:1.8.0_191]
        at sun.reflect.annotation.AnnotationParser.parseAnnotations(AnnotationParser.java:72) ~[?:1.8.0_191]
        at java.lang.Class.createAnnotationData(Class.java:3521) ~[?:1.8.0_191]
        at java.lang.Class.annotationData(Class.java:3510) ~[?:1.8.0_191]
        at java.lang.Class.getAnnotation(Class.java:3415) ~[?:1.8.0_191]
        at de.Keyle.MyPet.util.ConfigurationLoader.setDefault(ConfigurationLoader.java:193) ~[?:?]
        at de.Keyle.MyPet.MyPetPlugin.onLoad(MyPetPlugin.java:110) ~[?:?]
        at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:365) ~[?:?]
        at com.rylinaux.plugman.command.LoadCommand.execute(LoadCommand.java:114) ~[?:?]
        at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:95) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[patched_1.13.2.jar:git-Paper-525]
        ... 15 more

**Comment by xXKeyleXx** [comment]
MyPet simply doesn't support Pluginman.
