### ISSUE TITLE
loading eror

### ISSUE THREAD

**Issue by successed** [xXKeyleXx/MyPet#1221]
[12:44:08] [Server thread/INFO]: [MyPet] Loading MyPet v2.3.5
[12:44:08] [Server thread/ERROR]: [org.bukkit.craftbukkit.v1_13_R2.CraftServer] sun.reflect.annotation.EnumConstantNotPresentExceptionProxy initializing MyPet v2.3.5 (Is it up to date?)
java.lang.ArrayStoreException: sun.reflect.annotation.EnumConstantNotPresentExceptionProxy
	at sun.reflect.annotation.AnnotationParser.parseEnumArray(AnnotationParser.java:744) ~[?:1.8.0_191]
	at sun.reflect.annotation.AnnotationParser.parseArray(AnnotationParser.java:533) ~[?:1.8.0_191]
	at sun.reflect.annotation.AnnotationParser.parseMemberValue(AnnotationParser.java:355) ~[?:1.8.0_191]
	at sun.reflect.annotation.AnnotationParser.parseAnnotation2(AnnotationParser.java:286) ~[?:1.8.0_191]
	at sun.reflect.annotation.AnnotationParser.parseAnnotations2(AnnotationParser.java:120) ~[?:1.8.0_191]
	at sun.reflect.annotation.AnnotationParser.parseAnnotations(AnnotationParser.java:72) ~[?:1.8.0_191]
	at java.lang.Class.createAnnotationData(Class.java:3521) ~[?:1.8.0_191]
	at java.lang.Class.annotationData(Class.java:3510) ~[?:1.8.0_191]
	at java.lang.Class.getAnnotation(Class.java:3415) ~[?:1.8.0_191]
	at de.Keyle.MyPet.util.ConfigurationLoader.setDefault(ConfigurationLoader.java:193) ~[?:?]
	at de.Keyle.MyPet.MyPetPlugin.onLoad(MyPetPlugin.java:110) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.loadPlugins(CraftServer.java:336) ~[patched_1.13.2.jar:git-Paper-529]
	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:235) ~[patched_1.13.2.jar:git-Paper-529]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:786) ~[patched_1.13.2.jar:git-Paper-529]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]

**Comment by xXKeyleXx** [comment]
Either it's the same as #1220 or the plugin got not loaded correctly by the server.
