### ISSUE TITLE
server start eror

### ISSUE THREAD

**Issue by successed** [xXKeyleXx/MyPet#1222]
[12:44:34] [Server thread/ERROR]: Error occurred while enabling MyPet v2.3.5 (Is it up to date?)
java.lang.NullPointerException: null
	at de.Keyle.MyPet.MyPetPlugin.onEnable(MyPetPlugin.java:143) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254) ~[patched_1.13.2.jar:git-Paper-529]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:326) ~[patched_1.13.2.jar:git-Paper-529]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:406) ~[patched_1.13.2.jar:git-Paper-529]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:443) ~[patched_1.13.2.jar:git-Paper-529]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:357) ~[patched_1.13.2.jar:git-Paper-529]
	at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:608) ~[patched_1.13.2.jar:git-Paper-529]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:570) ~[patched_1.13.2.jar:git-Paper-529]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:431) ~[patched_1.13.2.jar:git-Paper-529]
	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:316) ~[patched_1.13.2.jar:git-Paper-529]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:786) ~[patched_1.13.2.jar:git-Paper-529]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
[12:44:34] [Server thread/INFO]: [de.Keyle.MyPet.MyPetPlugin] [MyPet] Disabling MyPet v2.3.5
[12:44:34] [Server thread/ERROR]: Error occurred while disabling MyPet v2.3.5 (Is it up to date?)
java.lang.NullPointerException: null
	at de.Keyle.MyPet.MyPetPlugin.onDisable(MyPetPlugin.java:98) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:256) ~[patched_1.13.2.jar:git-Paper-529]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:360) ~[patched_1.13.2.jar:git-Paper-529]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:438) ~[patched_1.13.2.jar:git-Paper-529]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:330) ~[patched_1.13.2.jar:git-Paper-529]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:406) ~[patched_1.13.2.jar:git-Paper-529]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:443) ~[patched_1.13.2.jar:git-Paper-529]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:357) ~[patched_1.13.2.jar:git-Paper-529]
	at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:608) ~[patched_1.13.2.jar:git-Paper-529]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:570) ~[patched_1.13.2.jar:git-Paper-529]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:431) ~[patched_1.13.2.jar:git-Paper-529]
	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:316) ~[patched_1.13.2.jar:git-Paper-529]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:786) ~[patched_1.13.2.jar:git-Paper-529]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]

**Comment by xXKeyleXx** [comment]
MyPet 2.3.5 does NOT support MC 1.13+

**Comment by successed** [comment]
> MyPet 2.3.5 does NOT support MC 1.13+

Which version should I use?

**Comment by xXKeyleXx** [comment]
The latest dev build

**Comment by xXKeyleXx** [comment]
https://mypet-plugin.de/download

**Comment by successed** [comment]
[16:21:54 ERROR]: Could not pass event CreatureSpawnEvent to WorldGuard v7.0.0-SNAPSHOT;0dc5781
java.lang.NullPointerException: null
        at com.sk89q.worldedit.bukkit.adapter.IBukkitAdapter.adapt(IBukkitAdapter.java:224) ~[?:?]
        at com.sk89q.worldedit.bukkit.BukkitAdapter.adapt(BukkitAdapter.java:116) ~[?:?]
        at com.sk89q.worldguard.bukkit.listener.WorldGuardEntityListener.onCreatureSpawn(WorldGuardEntityListener.java:635) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor453.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:67) ~[patched_1.13.2.jar:git-Paper-529]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.13.2.jar:git-Paper-529]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.13.2.jar:git-Paper-529]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:514) ~[patched_1.13.2.jar:git-Paper-529]
        at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callCreatureSpawnEvent(CraftEventFactory.java:479) ~[patched_1.13.2.jar:git-Paper-529]
        at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.doEntityAddEventCalling(CraftEventFactory.java:399) ~[patched_1.13.2.jar:git-Paper-529]
        at net.minecraft.server.v1_13_R2.World.addEntity(World.java:1081) ~[patched_1.13.2.jar:git-Paper-529]
        at net.minecraft.server.v1_13_R2.WorldServer.addEntity(WorldServer.java:942) ~[patched_1.13.2.jar:git-Paper-529]
        at de.Keyle.MyPet.compat.v1_13_R2.entity.EntityRegistry.spawnMinecraftEntity(EntityRegistry.java:128) ~[?:?]
        at de.Keyle.MyPet.entity.MyPet.createEntity(MyPet.java:536) ~[?:?]
        at de.Keyle.MyPet.util.player.MyPetPlayerImpl.schedule(MyPetPlayerImpl.java:436) ~[?:?]
        at de.Keyle.MyPet.api.util.Timer.lambda$startTimer$2(Timer.java:62) ~[?:?]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:82) ~[patched_1.13.2.jar:git-Paper-529]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:449) ~[patched_1.13.2.jar:git-Paper-529]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1003) ~[patched_1.13.2.jar:git-Paper-529]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-529]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:938) ~[patched_1.13.2.jar:git-Paper-529]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:836) ~[patched_1.13.2.jar:git-Paper-529]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]

**Comment by successed** [comment]
http://prntscr.com/mpeknk

NPC is attached to the vine.

**Comment by successed** [comment]
auto loot is not work.
http://prntscr.com/mpelxq
default config and skill tree files...
