### ISSUE TITLE
auto loot is not work.

### ISSUE THREAD

**Issue by successed** [xXKeyleXx/MyPet#1225]
auto loot is not work.
http://prntscr.com/mpelxq
default config and skill tree files...

version deweloper

**Comment by xXKeyleXx** [comment]
You have to activeate it with the `/petpickup command`

**Comment by successed** [comment]
[20:46:38 ERROR]: Could not pass event EntityDeathEvent to Jobs v4.10.1
java.lang.NoClassDefFoundError: de/Keyle/MyPet/api/entity/MyPetBukkitEntity
        at com.gamingmesh.jobs.MyPet.MyPetManager.isMyPet(MyPetManager.java:28) ~[?:?]
        at com.gamingmesh.jobs.listeners.JobsPaymentListener.onEntityDeath(JobsPaymentListener.java:1090) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor675.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:67) ~[patched_1.13.2.jar:git-Paper-529]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.13.2.jar:git-Paper-529]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.13.2.jar:git-Paper-529]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:514) ~[patched_1.13.2.jar:git-Paper-529]
        at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:607) ~[patched_1.13.2.jar:git-Paper-529]
        at net.minecraft.server.v1_13_R2.EntityLiving.die(EntityLiving.java:1243) ~[patched_1.13.2.jar:git-Paper-529]
        at net.minecraft.server.v1_13_R2.EntityVillager.die(EntityVillager.java:343) ~[patched_1.13.2.jar:git-Paper-529]
        at net.minecraft.server.v1_13_R2.EntityLiving.damageEntity(EntityLiving.java:1088) ~[patched_1.13.2.jar:git-Paper-529]
        at net.minecraft.server.v1_13_R2.EntityInsentient.B(EntityInsentient.java:1247) ~[patched_1.13.2.jar:git-Paper-529]
        at net.minecraft.server.v1_13_R2.EntityZombie.B(EntityZombie.java:315) ~[patched_1.13.2.jar:git-Paper-529]
        at net.minecraft.server.v1_13_R2.PathfinderGoalMeleeAttack.a(SourceFile:124) ~[patched_1.13.2.jar:git-Paper-529]
        at net.minecraft.server.v1_13_R2.PathfinderGoalMeleeAttack.e(SourceFile:116) ~[patched_1.13.2.jar:git-Paper-529]
        at net.minecraft.server.v1_13_R2.PathfinderGoalZombieAttack.e(SourceFile:28) ~[patched_1.13.2.jar:git-Paper-529]
        at net.minecraft.server.v1_13_R2.PathfinderGoalSelector.doTick(PathfinderGoalSelector.java:108) ~[patched_1.13.2.jar:git-Paper-529]
        at net.minecraft.server.v1_13_R2.EntityInsentient.doTick(EntityInsentient.java:685) ~[patched_1.13.2.jar:git-Paper-529]
        at net.minecraft.server.v1_13_R2.EntityLiving.movementTick(EntityLiving.java:2337) ~[patched_1.13.2.jar:git-Paper-529]
        at net.minecraft.server.v1_13_R2.EntityInsentient.movementTick(EntityInsentient.java:523) ~[patched_1.13.2.jar:git-Paper-529]
        at net.minecraft.server.v1_13_R2.EntityMonster.movementTick(EntityMonster.java:24) ~[patched_1.13.2.jar:git-Paper-529]
        at net.minecraft.server.v1_13_R2.EntityZombie.movementTick(EntityZombie.java:211) ~[patched_1.13.2.jar:git-Paper-529]
        at net.minecraft.server.v1_13_R2.EntityLiving.tick(EntityLiving.java:2134) ~[patched_1.13.2.jar:git-Paper-529]
        at net.minecraft.server.v1_13_R2.EntityInsentient.tick(EntityInsentient.java:261) ~[patched_1.13.2.jar:git-Paper-529]
        at net.minecraft.server.v1_13_R2.EntityMonster.tick(EntityMonster.java:28) ~[patched_1.13.2.jar:git-Paper-529]
        at net.minecraft.server.v1_13_R2.EntityZombie.tick(EntityZombie.java:185) ~[patched_1.13.2.jar:git-Paper-529]
        at net.minecraft.server.v1_13_R2.EntityZombieVillager.tick(EntityZombieVillager.java:76) ~[patched_1.13.2.jar:git-Paper-529]
        at net.minecraft.server.v1_13_R2.World.entityJoinedWorld(World.java:1556) ~[patched_1.13.2.jar:git-Paper-529]
        at net.minecraft.server.v1_13_R2.World.g(World.java:1523) ~[patched_1.13.2.jar:git-Paper-529]
        at net.minecraft.server.v1_13_R2.World.tickEntities(World.java:1330) ~[patched_1.13.2.jar:git-Paper-529]
        at net.minecraft.server.v1_13_R2.WorldServer.tickEntities(WorldServer.java:598) ~[patched_1.13.2.jar:git-Paper-529]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1099) ~[patched_1.13.2.jar:git-Paper-529]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-529]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:938) ~[patched_1.13.2.jar:git-Paper-529]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:836) ~[patched_1.13.2.jar:git-Paper-529]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]

**Comment by xXKeyleXx** [comment]
Don't post errors unrelated to the topic everywhere please...
The error is not MyPets fault. The Jobs needs to be updated.
