### ISSUE TITLE
/petinventory not work 1.14.1

### ISSUE THREAD

**Issue by andris155** [xXKeyleXx/MyPet#1250]
Please provide the following info.

Please use the `/petadmin ticket` command and attach the generated `ticket.zip` to this issue.

**Bukkit/Spigot/Bungee Build/Version:**
This server is running Paper version git-Paper-42 (MC: 1.14.1) (Implementing API version 1.14.1-R0.1-SNAPSHOT)

**MyPet Build/Version:**
[MyPet] MyPet-3.1-SNAPSHOT-b#1423

**What is the expected result?**
petinventory open

**What happens instead of that?**
petinventory not open

**Error:**
```
[14:07:36] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'peti' in plugin MyPet v3.1
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.14.1.jar:git-Paper-42]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.14.1.jar:git-Paper-42]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:736) ~[patched_1.14.1.jar:git-Paper-42]
	at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1826) ~[patched_1.14.1.jar:git-Paper-42]
	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1634) ~[patched_1.14.1.jar:git-Paper-42]
	at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.14.1.jar:git-Paper-42]
	at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.14.1.jar:git-Paper-42]
	at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:18) ~[patched_1.14.1.jar:git-Paper-42]
	at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.1.jar:git-Paper-42]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:127) ~[patched_1.14.1.jar:git-Paper-42]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.1.jar:git-Paper-42]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:105) ~[patched_1.14.1.jar:git-Paper-42]
	at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:998) ~[patched_1.14.1.jar:git-Paper-42]
	at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:991) ~[patched_1.14.1.jar:git-Paper-42]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:91) ~[patched_1.14.1.jar:git-Paper-42]
	at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:974) ~[patched_1.14.1.jar:git-Paper-42]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:908) ~[patched_1.14.1.jar:git-Paper-42]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.IllegalArgumentException: Unsupported custom inventory size 63
	at org.bukkit.craftbukkit.v1_14_R1.entity.CraftHumanEntity.openInventory(CraftHumanEntity.java:371) ~[patched_1.14.1.jar:git-Paper-42]
	at de.Keyle.MyPet.compat.v1_14_R1.util.inventory.CustomInventory.open(CustomInventory.java:264) ~[?:?]
	at de.Keyle.MyPet.skill.skills.BackpackImpl.openInventory(BackpackImpl.java:103) ~[?:?]
	at de.Keyle.MyPet.skill.skills.BackpackImpl.activate(BackpackImpl.java:89) ~[?:?]
	at de.Keyle.MyPet.commands.CommandInventory.onCommand(CommandInventory.java:64) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.14.1.jar:git-Paper-42]
	... 17 more
```

**Comment by andris155** [comment]
Thanks!
