### ISSUE TITLE
Not work with latest 1.14.2 server file builds

### ISSUE THREAD

**Issue by andris155** [xXKeyleXx/MyPet#1255]
# Bug report

* [x] I have checked other issues to make sure this is not a duplicate.

## Describe the bug

_A clear and concise description of what the bug is._
Not work with latest 1.14.2 server file builds

## To Reproduce

_Steps to reproduce the behavior, please provide code snippets or a repository:_
Start server with latest 1.14.2 server file and use MyPet.

...

## Expected behavior
_A clear and concise description of what you expected to happen._
MyPet works perfectly with latest server files builds

## Actual behaviour
_If applicable, add screenshots to help explain your problem._
MyPet not works perfectly with latest server files builds

## Additional context

> Please use the `/petadmin ticket` command and attach the generated `ticket.zip` from the MyPet folder to this issue.

**Bukkit/Spigot/Bungee Build/Version:** 
This server is running Paper version git-Paper-65 (MC: 1.14.2) (Implementing API version 1.14.2-R0.1-SNAPSHOT)

**MyPet Build/Version:** 
MyPet-3.1-SNAPSHOT-b#1437

**Error:**
```
[17:09:31] [Server thread/WARN]: [de.Keyle.MyPet.MyPetPlugin] [MyPet] Task #170 for MyPet v3.1 generated an exception
java.lang.IllegalAccessError: class de.Keyle.MyPet.compat.v1_14_R1.entity.EntityMyPet tried to access private field net.minecraft.server.v1_14_R1.Entity.bukkitEntity (de.Keyle.MyPet.compat.v1_14_R1.entity.EntityMyPet is in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @4b9f0d8c; net.minecraft.server.v1_14_R1.Entity is in unnamed module of loader 'app')
	at de.Keyle.MyPet.compat.v1_14_R1.entity.EntityMyPet.getBukkitEntity(EntityMyPet.java:387) ~[?:?]
	at de.Keyle.MyPet.compat.v1_14_R1.entity.EntityMyPet.getBukkitEntity(EntityMyPet.java:79) ~[?:?]
	at de.Keyle.MyPet.entity.MyPet.createEntity(MyPet.java:474) ~[?:?]
	at de.Keyle.MyPet.util.player.MyPetPlayerImpl.schedule(MyPetPlayerImpl.java:464) ~[?:?]
	at de.Keyle.MyPet.api.util.Timer.lambda$startTimer$2(Timer.java:62) ~[?:?]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.2.jar:git-Paper-65]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.14.2.jar:git-Paper-65]
	at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1114) ~[patched_1.14.2.jar:git-Paper-65]
	at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:418) ~[patched_1.14.2.jar:git-Paper-65]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1060) ~[patched_1.14.2.jar:git-Paper-65]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:904) ~[patched_1.14.2.jar:git-Paper-65]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by TakoidGit** [comment]
I brought this same issue up on the Paper Discord and got the following reply explaining how to fix:

https://i.imgur.com/vcKEqNE.png
