### ISSUE TITLE
Not Compatible with 1.14.4?

### ISSUE THREAD

**Issue by TripleDGames** [xXKeyleXx/MyPet#1281]
[11:50:57] [Server thread/ERROR]: Error occurred while enabling MyPet v3.5 (Is it up to date?)
java.lang.NoSuchMethodError: net.minecraft.server.v1_14_R1.EntityTypes.j()Lnet/minecraft/server/v1_14_R1/EntitySize;
	at de.Keyle.MyPet.compat.v1_14_R1.entity.EntityRegistry.registerEntityType(EntityRegistry.java:52) ~[?:?]
	at de.Keyle.MyPet.compat.v1_14_R1.entity.EntityRegistry.registerEntity(EntityRegistry.java:62) ~[?:?]
	at de.Keyle.MyPet.compat.v1_14_R1.entity.EntityRegistry.registerEntityTypes(EntityRegistry.java:98) ~[?:?]
	at de.Keyle.MyPet.MyPetPlugin.onEnable(MyPetPlugin.java:192) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.14.4.jar:git-Paper-135]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338) ~[patched_1.14.4.jar:git-Paper-135]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420) ~[patched_1.14.4.jar:git-Paper-135]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:467) ~[patched_1.14.4.jar:git-Paper-135]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:381) ~[patched_1.14.4.jar:git-Paper-135]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:474) ~[patched_1.14.4.jar:git-Paper-135]
	at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:282) ~[patched_1.14.4.jar:git-Paper-135]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:871) ~[patched_1.14.4.jar:git-Paper-135]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]
[11:50:57] [Server thread/INFO]: [de.Keyle.MyPet.MyPetPlugin] [MyPet] Disabling MyPet v3.5

Getting this after updating to 1.14.4, Paper Version 135. Happens on both MyPet 3.4 and the latest Dev build.

**Comment by AccioAce** [comment]
Hello, I am having the same issue as well. Hopefully it gets updated soon!
