### ISSUE TITLE
Update Lands hook

### ISSUE THREAD

**Issue by Corenb** [xXKeyleXx/MyPet#1357]
# Bug report

[*] I have checked other issues to make sure this is not a duplicate.

## Describe the bug

Lands Hook needs yet another update.
Upon Server Startup with MyPet 3.9-SNAPSHOT-B1527 an error is posted to console.

## To Reproduce

1. Run MyPets and Lands
[ticket.zip](https://github.com/xXKeyleXx/MyPet/files/4242702/ticket.zip)

2. Hurt a pet

## Actual behaviour

Error in console.

**Bukkit/Spigot/Bungee Build/Version:**
Paper v1.15.2

**MyPet Build/Version:**
MyPet 3.9-SNAPSHOT-B1527

**Error:**
```
[00:26:11 WARN]: java.lang.IllegalAccessException: The getLandChunk method is not supported anymore. Please contact the developer, who uses the LandsAPI.
[00:26:11 WARN]:        at me.angeschossen.lands.api.integration.LandsIntegration.getLandChunk(?:94)
[00:26:11 WARN]:        at de.Keyle.MyPet.util.hooks.LandsHook.canHurt(LandsHook.java:58)
[00:26:11 WARN]:        at de.Keyle.MyPet.util.HookHelper.canHurt(HookHelper.java:84)
[00:26:11 WARN]:        at de.Keyle.MyPet.util.player.MyPetPlayerImpl.schedule(MyPetPlayerImpl.java:507)
[00:26:11 WARN]:        at de.Keyle.MyPet.api.util.Timer.lambda$startTimer$2(Timer.java:62)
[00:26:11 WARN]:        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84)
[00:26:11 WARN]:        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452)
[00:26:11 WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1185)
[00:26:11 WARN]:        at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430)
[00:26:11 WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1112)
[00:26:11 WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:934)
[00:26:11 WARN]:        at java.lang.Thread.run(Thread.java:748)
```

**Comment by zerafox** [comment]
Update your MyPet
