### ISSUE TITLE
Mypet API

### ISSUE THREAD

**Issue by zephirox58** [xXKeyleXx/MyPet#1365]
# Bug report
## Describe the bug

Spam console for API error

**paper-125 1.15.2**

**3.9**

**Error:**
```
[17:28:09] [Server thread/WARN]: java.lang.IllegalAccessException: The getLandChunk method is not supported anymore. Please contact the developer, who uses the LandsAPI.
[17:28:09] [Server thread/WARN]: 	at me.angeschossen.lands.api.integration.LandsIntegration.getLandChunk(?:94)
[17:28:09] [Server thread/WARN]: 	at de.Keyle.MyPet.util.hooks.LandsHook.canHurt(LandsHook.java:58)
[17:28:09] [Server thread/WARN]: 	at de.Keyle.MyPet.util.HookHelper.canHurt(HookHelper.java:84)
[17:28:09] [Server thread/WARN]: 	at de.Keyle.MyPet.util.player.MyPetPlayerImpl.schedule(MyPetPlayerImpl.java:507)
[17:28:09] [Server thread/WARN]: 	at de.Keyle.MyPet.api.util.Timer.lambda$startTimer$2(Timer.java:62)
```
He says : contact you  ^^'

**Comment by xXKeyleXx** [comment]
Update to the latest dev build of MyPet

**Comment by zephirox58** [comment]
Kk i try it =) thanks for the fast reply.

I can just switch .jar and my player keep there data ?

**Comment by xXKeyleXx** [comment]
sure
