### ISSUE TITLE
Server Warnings when using mypet commands

### ISSUE THREAD

**Issue by burnthippie** [xXKeyleXx/MyPet#1371]
# Bug report

* [ x] I have checked other issues to make sure this is not a duplicate.

## Describe the bug

When any player uses a mypet command it produces an error that says to contact the devoloper

## To Reproduce

_Steps to reproduce the behavior, please provide code snippets or a repository:_
Lands 4.5.81,mypet 3.10 , warnings happen usually on the first person to use the commands then seem to go away for a bit then t
1. Do any mypet command, I used /PCH and /petsummon
2. see the server log
...

## Expected behavior

Not to get 100's of lines of server warnings when using mypet commands

## Actual behaviour

Included a list of errors [below](url)

## Additional context

> Please use the `/petadmin ticket` command and attach the generated `ticket.zip` from the MyPet folder to this issue.
[ticket.zip](https://github.com/xXKeyleXx/MyPet/files/4552700/ticket.zip)

**Bukkit/Spigot/Bungee Build/Version:**
1.15.2
git-Spigot-e7dc2f5-ce66f69 
**MyPet Build/Version:**
3.10
**What is the expected result?**
I
**What happens instead of that?**
Just a wall of server errors, the plugin seems to still function

**Error:**
```
[11:15:10] [Server thread/WARN]: java.lang.IllegalAccessException: The getLandChunk method is not supported anymore. Please contact the developer, who uses the LandsAPI. Use getLand or getArea instead.
[11:15:10] [Server thread/WARN]:        at me.angeschossen.lands.api.integration.LandsIntegration.getLandChunk(?:94)
[11:15:10] [Server thread/WARN]:        at de.Keyle.MyPet.util.hooks.LandsHook.canHurt(LandsHook.java:58)
[11:15:10] [Server thread/WARN]:        at de.Keyle.MyPet.util.HookHelper.canHurt(HookHelper.java:84)
[11:15:10] [Server thread/WARN]:        at de.Keyle.MyPet.util.player.MyPetPlayerImpl.schedule(MyPetPlayerImpl.java:507)
[11:15:10] [Server thread/WARN]:        at de.Keyle.MyPet.api.util.Timer.lambda$startTimer$2(Timer.java:62)
[11:15:10] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:81)
[11:15:10] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:400)
[11:15:10] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1036)
[11:15:10] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:406)
[11:15:10] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:984)
[11:15:10] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:824)
[11:15:10] [Server thread/WARN]:        at java.lang.Thread.run(Unknown Source)
[11:15:11] [Server thread/WARN]: java.lang.IllegalAccessException: The getLandChunk method is not supported anymore. Please contact the developer, who uses the LandsAPI. Use getLand or getArea instead.
```

**Comment by xXKeyleXx** [comment]
Land changes their API every two weeks... Have to fix that when I got time. You can simply ignore it for the time beeing.

**Comment by burnthippie** [comment]
Okay just giving you a heads up, doesnt seem to effect how the plugin works.

**Comment by xXKeyleXx** [comment]
Man the problem is on your end, not Lands or mine. You are simply NOT on the version you said you are. Update the plugin and everything magically starts to working 😱
