### ISSUE TITLE
How can I solve this problem?

### ISSUE THREAD

**Issue by x458** [xXKeyleXx/MyPet#1374]
> [15:07:26 ERROR]: Could not pass event EntityInteractEvent to MyPet v3.1
org.bukkit.event.EventException: null
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-3d850ec-809c399]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-3d850ec-809c399]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot.jar:git-Spigot-3d850ec-809c399]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot.jar:git-Spigot-3d850ec-809c399]
at net.minecraft.server.v1_12_R1.BlockPressurePlateBinary.e(BlockPressurePlateBinary.java:78) [spigot.jar:git-Spigot-3d850ec-809c399]
at net.minecraft.server.v1_12_R1.BlockPressurePlateAbstract.a(BlockPressurePlateAbstract.java:96) [spigot.jar:git-Spigot-3d850ec-809c399]
at net.minecraft.server.v1_12_R1.BlockPressurePlateAbstract.a(BlockPressurePlateAbstract.java:89) [spigot.jar:git-Spigot-3d850ec-809c399]
at net.minecraft.server.v1_12_R1.Entity.checkBlockCollisions(Entity.java:961) [spigot.jar:git-Spigot-3d850ec-809c399]
at net.minecraft.server.v1_12_R1.Entity.move(Entity.java:542) [spigot.jar:git-Spigot-3d850ec-809c399]
at net.minecraft.server.v1_12_R1.EntityLiving.a(EntityLiving.java:1811) [spigot.jar:git-Spigot-3d850ec-809c399]
at net.minecraft.server.v1_12_R1.EntityHuman.a(EntityHuman.java:1416) [spigot.jar:git-Spigot-3d850ec-809c399]
at net.minecraft.server.v1_12_R1.EntityLiving.n(EntityLiving.java:2122) [spigot.jar:git-Spigot-3d850ec-809c399]
at net.minecraft.server.v1_12_R1.EntityHuman.n(EntityHuman.java:348) [spigot.jar:git-Spigot-3d850ec-809c399]
at net.minecraft.server.v1_12_R1.EntityLiving.B_(EntityLiving.java:1944) [spigot.jar:git-Spigot-3d850ec-809c399]
at net.minecraft.server.v1_12_R1.EntityHuman.B_(EntityHuman.java:145) [spigot.jar:git-Spigot-3d850ec-809c399]
at net.minecraft.server.v1_12_R1.EntityPlayer.playerTick(EntityPlayer.java:304) [spigot.jar:git-Spigot-3d850ec-809c399]
at net.minecraft.server.v1_12_R1.PlayerConnection.e(PlayerConnection.java:139) [spigot.jar:git-Spigot-3d850ec-809c399]
at net.minecraft.server.v1_12_R1.NetworkManager.a(NetworkManager.java:233) [spigot.jar:git-Spigot-3d850ec-809c399]
at net.minecraft.server.v1_12_R1.ServerConnection.c(ServerConnection.java:140) [spigot.jar:git-Spigot-3d850ec-809c399]
at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:845) [spigot.jar:git-Spigot-3d850ec-809c399]
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot.jar:git-Spigot-3d850ec-809c399]
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot.jar:git-Spigot-3d850ec-809c399]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot.jar:git-Spigot-3d850ec-809c399]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
Caused by: java.lang.NoSuchFieldError: INTERACT
at de.Keyle.MyPet.util.hooks.WorldGuardHook.on(WorldGuardHook.java:301) ~[?:?]
at sun.reflect.GeneratedMethodAccessor364.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_242]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_242]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot.jar:git-Spigot-3d850ec-809c399]
... 23 more
> [15:07:27 INFO]: [Matrix] drago_2000 tried to place/break a block too quickly (FastPlace/FastBreak)
> [15:07:29 INFO]: Banan4icik issued server command: /warp pvp
> [15:07:56 INFO]: Malenkay issued server command: /tp Stimpy
> [15:07:58 ERROR]: Could not pass event EntityInteractEvent to MyPet v3.1
org.bukkit.event.EventException: null
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-3d850ec-809c399]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-3d850ec-809c399]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot.jar:git-Spigot-3d850ec-809c399]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot.jar:git-Spigot-3d850ec-809c399]
at net.minecraft.server.v1_12_R1.BlockPressurePlateBinary.e(BlockPressurePlateBinary.java:78) [spigot.jar:git-Spigot-3d850ec-809c399]
at net.minecraft.server.v1_12_R1.BlockPressurePlateAbstract.a(BlockPressurePlateAbstract.java:96) [spigot.jar:git-Spigot-3d850ec-809c399]
at net.minecraft.server.v1_12_R1.BlockPressurePlateAbstract.a(BlockPressurePlateAbstract.java:89) [spigot.jar:git-Spigot-3d850ec-809c399]
at net.minecraft.server.v1_12_R1.Entity.checkBlockCollisions(Entity.java:961) [spigot.jar:git-Spigot-3d850ec-809c399]
at net.minecraft.server.v1_12_R1.Entity.move(Entity.java:542) [spigot.jar:git-Spigot-3d850ec-809c399]
at net.minecraft.server.v1_12_R1.EntityLiving.a(EntityLiving.java:1811) [spigot.jar:git-Spigot-3d850ec-809c399]
at de.Keyle.MyPet.compat.v1_12_R1.entity.EntityMyPet.a(EntityMyPet.java:1096) [MyPet-3.10.jar:?]
at de.Keyle.MyPet.compat.v1_12_R1.entity.EntityMyPet.n(EntityMyPet.java:970) [MyPet-3.10.jar:?]
at net.minecraft.server.v1_12_R1.EntityLiving.B_(EntityLiving.java:1944) [spigot.jar:git-Spigot-3d850ec-809c399]
at net.minecraft.server.v1_12_R1.EntityInsentient.B_(EntityInsentient.java:246) [spigot.jar:git-Spigot-3d850ec-809c399]
at de.Keyle.MyPet.compat.v1_12_R1.entity.EntityMyPet.B_(EntityMyPet.java:1240) [MyPet-3.10.jar:?]
at net.minecraft.server.v1_12_R1.World.entityJoinedWorld(World.java:1633) [spigot.jar:git-Spigot-3d850ec-809c399]
at net.minecraft.server.v1_12_R1.World.h(World.java:1603) [spigot.jar:git-Spigot-3d850ec-809c399]
at net.minecraft.server.v1_12_R1.World.tickEntities(World.java:1437) [spigot.jar:git-Spigot-3d850ec-809c399]
at net.minecraft.server.v1_12_R1.WorldServer.tickEntities(WorldServer.java:665) [spigot.jar:git-Spigot-3d850ec-809c399]
at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:817) [spigot.jar:git-Spigot-3d850ec-809c399]
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot.jar:git-Spigot-3d850ec-809c399]
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot.jar:git-Spigot-3d850ec-809c399]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot.jar:git-Spigot-3d850ec-809c399]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
Caused by: java.lang.NoSuchFieldError: INTERACT
at de.Keyle.MyPet.util.hooks.WorldGuardHook.on(WorldGuardHook.java:301) ~[?:?]
at sun.reflect.GeneratedMethodAccessor364.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_242]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_242]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot.jar:git-Spigot-3d850ec-809c399]
... 23 more
> [15:07:58 ERROR]: Could not pass event EntityInteractEvent to MyPet v3.1
org.bukkit.event.EventException: null
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-3d850ec-809c399]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-3d850ec-809c399]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot.jar:git-Spigot-3d850ec-809c399]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot.jar:git-Spigot-3d850ec-809c399]
at net.minecraft.server.v1_12_R1.BlockPressurePlateBinary.e(BlockPressurePlateBinary.java:78) [spigot.jar:git-Spigot-3d850ec-809c399]
at net.minecraft.server.v1_12_R1.BlockPressurePlateAbstract.a(BlockPressurePlateAbstract.java:96) [spigot.jar:git-Spigot-3d850ec-809c399]
at net.minecraft.server.v1_12_R1.BlockPressurePlateAbstract.a(BlockPressurePlateAbstract.java:89) [spigot.jar:git-Spigot-3d850ec-809c399]
at net.minecraft.server.v1_12_R1.Entity.checkBlockCollisions(Entity.java:961) [spigot.jar:git-Spigot-3d850ec-809c399]
at net.minecraft.server.v1_12_R1.Entity.move(Entity.java:542) [spigot.jar:git-Spigot-3d850ec-809c399]
at net.minecraft.server.v1_12_R1.EntityItem.B_(EntityItem.java:86) [spigot.jar:git-Spigot-3d850ec-809c399]
at net.minecraft.server.v1_12_R1.World.entityJoinedWorld(World.java:1633) [spigot.jar:git-Spigot-3d850ec-809c399]
at net.minecraft.server.v1_12_R1.World.h(World.java:1603) [spigot.jar:git-Spigot-3d850ec-809c399]
at net.minecraft.server.v1_12_R1.World.tickEntities(World.java:1437) [spigot.jar:git-Spigot-3d850ec-809c399]
at net.minecraft.server.v1_12_R1.WorldServer.tickEntities(WorldServer.java:665) [spigot.jar:git-Spigot-3d850ec-809c399]
at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:817) [spigot.jar:git-Spigot-3d850ec-809c399]
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot.jar:git-Spigot-3d850ec-809c399]
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot.jar:git-Spigot-3d850ec-809c399]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot.jar:git-Spigot-3d850ec-809c399]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
Caused by: java.lang.NoSuchFieldError: INTERACT
at de.Keyle.MyPet.util.hooks.WorldGuardHook.on(WorldGuardHook.java:301) ~[?:?]
at sun.reflect.GeneratedMethodAccessor364.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_242]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_242]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot.jar:git-Spigot-3d850ec-809c399]
... 18 more
> [15:07:59 ERROR]: Could not pass event EntityInteractEvent to MyPet v3.1
org.bukkit.event.EventException: null
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-3d850ec-809c399]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-3d850ec-809c399]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot.jar:git-Spigot-3d850ec-809c399]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot.jar:git-Spigot-3d850ec-809c399]
at net.minecraft.server.v1_12_R1.BlockPressurePlateBinary.e(BlockPressurePlateBinary.java:78) [spigot.jar:git-Spigot-3d850ec-809c399]
at net.minecraft.server.v1_12_R1.BlockPressurePlateAbstract.a(BlockPressurePlateAbstract.java:96) [spigot.jar:git-Spigot-3d850ec-809c399]
at net.minecraft.server.v1_12_R1.BlockPressurePlateAbstract.a(BlockPressurePlateAbstract.java:89) [spigot.jar:git-Spigot-3d850ec-809c399]
at net.minecraft.server.v1_12_R1.Entity.checkBlockCollisions(Entity.java:961) [spigot.jar:git-Spigot-3d850ec-809c399]
at net.minecraft.server.v1_12_R1.Entity.move(Entity.java:542) [spigot.jar:git-Spigot-3d850ec-809c399]
at net.minecraft.server.v1_12_R1.EntityLiving.a(EntityLiving.java:1811) [spigot.jar:git-Spigot-3d850ec-809c399]
at de.Keyle.MyPet.compat.v1_12_R1.entity.EntityMyPet.a(EntityMyPet.java:1096) [MyPet-3.10.jar:?]
at de.Keyle.MyPet.compat.v1_12_R1.entity.EntityMyPet.n(EntityMyPet.java:970) [MyPet-3.10.jar:?]
at net.minecraft.server.v1_12_R1.EntityLiving.B_(EntityLiving.java:1944) [spigot.jar:git-Spigot-3d850ec-809c399]
at net.minecraft.server.v1_12_R1.EntityInsentient.B_(EntityInsentient.java:246) [spigot.jar:git-Spigot-3d850ec-809c399]
at de.Keyle.MyPet.compat.v1_12_R1.entity.EntityMyPet.B_(EntityMyPet.java:1240) [MyPet-3.10.jar:?]
at net.minecraft.server.v1_12_R1.World.entityJoinedWorld(World.java:1633) [spigot.jar:git-Spigot-3d850ec-809c399]
at net.minecraft.server.v1_12_R1.World.h(World.java:1603) [spigot.jar:git-Spigot-3d850ec-809c399]
at net.minecraft.server.v1_12_R1.World.tickEntities(World.java:1437) [spigot.jar:git-Spigot-3d850ec-809c399]
at net.minecraft.server.v1_12_R1.WorldServer.tickEntities(WorldServer.java:665) [spigot.jar:git-Spigot-3d850ec-809c399]
at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:817) [spigot.jar:git-Spigot-3d850ec-809c399]
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot.jar:git-Spigot-3d850ec-809c399]
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot.jar:git-Spigot-3d850ec-809c399]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot.jar:git-Spigot-3d850ec-809c399]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
Caused by: java.lang.NoSuchFieldError: INTERACT
at de.Keyle.MyPet.util.hooks.WorldGuardHook.on(WorldGuardHook.java:301) ~[?:?]
at sun.reflect.GeneratedMethodAccessor364.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_242]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_242]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot.jar:git-Spigot-3d850ec-809c399]
... 23 more
> [15:08:00 ERROR]: Could not pass event EntityInteractEvent to MyPet v3.1
org.bukkit.event.EventException: null
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-3d850ec-809c399]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-3d850ec-809c399]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot.jar:git-Spigot-3d850ec-809c399]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot.jar:git-Spigot-3d850ec-809c399]
at net.minecraft.server.v1_12_R1.BlockPressurePlateBinary.e(BlockPressurePlateBinary.java:78) [spigot.jar:git-Spigot-3d850ec-809c399]
at net.minecraft.server.v1_12_R1.BlockPressurePlateAbstract.a(BlockPressurePlateAbstract.java:96) [spigot.jar:git-Spigot-3d850ec-809c399]
at net.minecraft.server.v1_12_R1.BlockPressurePlateAbstract.a(BlockPressurePlateAbstract.java:89) [spigot.jar:git-Spigot-3d850ec-809c399]
at net.minecraft.server.v1_12_R1.Entity.checkBlockCollisions(Entity.java:961) [spigot.jar:git-Spigot-3d850ec-809c399]
at net.minecraft.server.v1_12_R1.Entity.move(Entity.java:542) [spigot.jar:git-Spigot-3d850ec-809c399]
at net.minecraft.server.v1_12_R1.EntityLiving.a(EntityLiving.java:1811) [spigot.jar:git-Spigot-3d850ec-809c399]
at de.Keyle.MyPet.compat.v1_12_R1.entity.EntityMyPet.a(EntityMyPet.java:1096) [MyPet-3.10.jar:?]
at de.Keyle.MyPet.compat.v1_12_R1.entity.EntityMyPet.n(EntityMyPet.java:970) [MyPet-3.10.jar:?]
at net.minecraft.server.v1_12_R1.EntityLiving.B_(EntityLiving.java:1944) [spigot.jar:git-Spigot-3d850ec-809c399]
at net.minecraft.server.v1_12_R1.EntityInsentient.B_(EntityInsentient.java:246) [spigot.jar:git-Spigot-3d850ec-809c399]
at de.Keyle.MyPet.compat.v1_12_R1.entity.EntityMyPet.B_(EntityMyPet.java:1240) [MyPet-3.10.jar:?]
at net.minecraft.server.v1_12_R1.World.entityJoinedWorld(World.java:1633) [spigot.jar:git-Spigot-3d850ec-809c399]
at net.minecraft.server.v1_12_R1.World.h(World.java:1603) [spigot.jar:git-Spigot-3d850ec-809c399]
at net.minecraft.server.v1_12_R1.World.tickEntities(World.java:1437) [spigot.jar:git-Spigot-3d850ec-809c399]
at net.minecraft.server.v1_12_R1.WorldServer.tickEntities(WorldServer.java:665) [spigot.jar:git-Spigot-3d850ec-809c399]
at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:817) [spigot.jar:git-Spigot-3d850ec-809c399]
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot.jar:git-Spigot-3d850ec-809c399]
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot.jar:git-Spigot-3d850ec-809c399]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot.jar:git-Spigot-3d850ec-809c399]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
Caused by: java.lang.NoSuchFieldError: INTERACT
at de.Keyle.MyPet.util.hooks.WorldGuardHook.on(WorldGuardHook.java:301) ~[?:?]
at sun.reflect.GeneratedMethodAccessor364.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_242]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_242]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot.jar:git-Spigot-3d850ec-809c399]
... 23 more
> [15:08:00 ERROR]: Could not pass event EntityInteractEvent to MyPet v3.1
org.bukkit.event.EventException: null
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-3d850ec-809c399]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-3d850ec-809c399]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot.jar:git-Spigot-3d850ec-809c399]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot.jar:git-Spigot-3d850ec-809c399]
at net.minecraft.server.v1_12_R1.BlockPressurePlateBinary.e(BlockPressurePlateBinary.java:78) [spigot.jar:git-Spigot-3d850ec-809c399]
at net.minecraft.server.v1_12_R1.BlockPressurePlateAbstract.a(BlockPressurePlateAbstract.java:96) [spigot.jar:git-Spigot-3d850ec-809c399]
at net.minecraft.server.v1_12_R1.BlockPressurePlateAbstract.a(BlockPressurePlateAbstract.java:89) [spigot.jar:git-Spigot-3d850ec-809c399]
at net.minecraft.server.v1_12_R1.Entity.checkBlockCollisions(Entity.java:961) [spigot.jar:git-Spigot-3d850ec-809c399]
at net.minecraft.server.v1_12_R1.Entity.move(Entity.java:542) [spigot.jar:git-Spigot-3d850ec-809c399]
at net.minecraft.server.v1_12_R1.EntityItem.B_(EntityItem.java:86) [spigot.jar:git-Spigot-3d850ec-809c399]
at net.minecraft.server.v1_12_R1.World.entityJoinedWorld(World.java:1633) [spigot.jar:git-Spigot-3d850ec-809c399]
at net.minecraft.server.v1_12_R1.World.h(World.java:1603) [spigot.jar:git-Spigot-3d850ec-809c399]
at net.minecraft.server.v1_12_R1.World.tickEntities(World.java:1437) [spigot.jar:git-Spigot-3d850ec-809c399]
at net.minecraft.server.v1_12_R1.WorldServer.tickEntities(WorldServer.java:665) [spigot.jar:git-Spigot-3d850ec-809c399]
at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:817) [spigot.jar:git-Spigot-3d850ec-809c399]
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot.jar:git-Spigot-3d850ec-809c399]
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot.jar:git-Spigot-3d850ec-809c399]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot.jar:git-Spigot-3d850ec-809c399]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
Caused by: java.lang.NoSuchFieldError: INTERACT
at de.Keyle.MyPet.util.hooks.WorldGuardHook.on(WorldGuardHook.java:301) ~[?:?]
at sun.reflect.GeneratedMethodAccessor364.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_242]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_242]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot.jar:git-Spigot-3d850ec-809c399]
... 18 more

**Comment by zerafox** [comment]
You can start by using the template instead of just pasting an error onto a ticket.

Use the template and provide a proper error-report so we can actually do something to help you.
