### ISSUE TITLE
Error enabling MobStacker Hook

### ISSUE THREAD

**Issue by Onyx235** [xXKeyleXx/MyPet#1379]
# Bug report

* [ ] I have checked other issues to make sure this is not a duplicate.

## Describe the bug

In the console MyPet is not hooking into the MobStacker Plugin

## To Reproduce

_Steps to reproduce the behavior, please provide code snippets or a repository:_

1. Have Mobstacker plugin in plugin folder.
2. Have MyPet in plugin folder
3. Run server
...

## Expected behavior

Not display error/warnings to console/ and to hook into mobstacker 

## Actual behaviour

Says error occurs whilst enabling MobStacker hook

## Additional context

The plugin works fine, it just doesn't hook into mobstacker like it's suppost too

Paper 1.8.8. However had the same issue with Spigot 1.8.8

**MyPet Build/Version:**
3.10

**Error:**
```
PUT ERROR HERE IF NOT LONGER THAN ~10 LINES
```
[19:59:47 WARN]: [[0;32;22mMyPet[m] [m[0;31;1mError occured while enabling MobStacker (2.0.0) hook.[m
[19:59:47 WARN]: java.util.NoSuchElementException: No value present
[19:59:47 WARN]:        at java.util.Optional.get(Unknown Source)
[19:59:47 WARN]:        at de.Keyle.MyPet.util.hooks.MobStackerBHook.onEnable(MobStackerBHook.java:39)
[19:59:47 WARN]:        at de.Keyle.MyPet.api.util.hooks.PluginHookManager.enableHook(PluginHookManager.java:115)
[19:59:47 WARN]:        at de.Keyle.MyPet.api.util.hooks.PluginHookManager.enableHooks(PluginHookManager.java:168)
[19:59:47 WARN]:        at de.Keyle.MyPet.MyPetPlugin.onEnable(MyPetPlugin.java:390)
[19:59:47 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
[19:59:47 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332)
[19:59:47 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407)
[19:59:47 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359)
[19:59:47 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318)
[19:59:47 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408)
[19:59:47 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372)
[19:59:47 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327)
[19:59:47 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267)
[19:59:47 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563)
[19:59:47 WARN]:        at java.lang.Thread.run(Unknown Source)
[19:59:47 INFO]: [[0;32;22mMyPet[m] [mPlaceholderAPI (2.10.6) hook activated.[m
[19:59:47 INFO]: [[0;32;22mMyPet[m] [mProtocolLib (4.5.1) hook activated.[m

**Comment by UserDerezzed** [comment]
Fixed in 3.14.3-SNAPSHOT-b2
