### ISSUE TITLE
Log Error when pet dies and comes back immediately

### ISSUE THREAD

**Issue by Serial1990** [xXKeyleXx/MyPet#1389]
Log Error when pet dies and comes back immediately

_Steps to reproduce the behavior, please provide code snippets or a repository:

Pet dies -> Pet revives (Magma_Block)

**Bukkit/Spigot/Bungee Build/Version: Paper#92 1.16.1

**MyPet Build/Version: #1553

**Error:**
```
 Entity threw exception at spawn_nether:616.4471855908027,28.0,-375.30780846623264
 java.lang.NullPointerException
 	at net.minecraft.server.v1_16_R1.AttributeMapBase.e(SourceFile:48)
 	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1133)
 	at net.minecraft.server.v1_16_R1.AttributeMapBase.a(SourceFile:48)
 	at org.bukkit.craftbukkit.v1_16_R1.attribute.CraftAttributeMap.getAttribute(CraftAttributeMap.java:38)
 	at org.bukkit.craftbukkit.v1_16_R1.entity.CraftLivingEntity.getAttribute(CraftLivingEntity.java:642)
 	at org.bukkit.craftbukkit.v1_16_R1.event.CraftEventFactory.populateFields(CraftEventFactory.java:845)
 	at org.bukkit.craftbukkit.v1_16_R1.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:791)
 	at net.minecraft.server.v1_16_R1.EntityLiving.d(EntityLiving.java:1489)
 	at net.minecraft.server.v1_16_R1.EntityLiving.die(EntityLiving.java:1417)
 	at de.Keyle.MyPet.compat.v1_16_R1.entity.EntityMyPet.die(EntityMyPet.java:683)
 	at net.minecraft.server.v1_16_R1.EntityLiving.damageEntity(EntityLiving.java:1261)
 	at net.minecraft.server.v1_16_R1.BlockMagma.stepOn(BlockMagma.java:15)
 	at net.minecraft.server.v1_16_R1.Entity.move(Entity.java:711)
 	at net.minecraft.server.v1_16_R1.EntityLiving.a(EntityLiving.java:2357)
 	at net.minecraft.server.v1_16_R1.EntityLiving.f(EntityLiving.java:2316)
 	at de.Keyle.MyPet.compat.v1_16_R1.entity.EntityMyPet.f(EntityMyPet.java:1176)
 	at de.Keyle.MyPet.compat.v1_16_R1.entity.EntityMyPet.movementTick(EntityMyPet.java:1034)
 	at net.minecraft.server.v1_16_R1.EntityLiving.tick(EntityLiving.java:2468)
 	at net.minecraft.server.v1_16_R1.EntityInsentient.tick(EntityInsentient.java:306)
 	at de.Keyle.MyPet.compat.v1_16_R1.entity.EntityMyPet.tick(EntityMyPet.java:1327)
 	at net.minecraft.server.v1_16_R1.WorldServer.entityJoinedWorld(WorldServer.java:831)
 	at net.minecraft.server.v1_16_R1.World.a(World.java:932)
 	at net.minecraft.server.v1_16_R1.WorldServer.doTick(WorldServer.java:525)
 	at net.minecraft.server.v1_16_R1.MinecraftServer.b(MinecraftServer.java:1353)
 	at net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:377)
 	at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1212)
 	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1000)
 	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
 	at java.base/java.lang.Thread.run(Thread.java:834)

```

**Comment by niqoar** [comment]
Same here!

**Comment by Sulort** [comment]
Hi, we have the same issue, also using papermc #92 on 1.16.1 and mypet latest version 3.11 #B1553

https://pastebin.com/KbpHUS0V

**Comment by xXKeyleXx** [comment]
Please try the latest dev build and tell me if it still happens

**Comment by Serial1990** [comment]
Exactly the same Error with the #1554 and paper#92 such as paper#99 1.16.1

![2020-07-18_12 37 42](https://user-images.githubusercontent.com/1337501/87850907-02a27c80-c8f4-11ea-9c39-1556cb5e8ce0.png)

**Comment by andris155** [comment]
Same with latest build.
```
[14:30:12] [Server thread/WARN]: Entity threw exception at world114:2779.612500011921,75.0,182.18389010810793
[14:30:12] [Server thread/WARN]: java.lang.NullPointerException
[14:30:12] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.AttributeMapBase.e(SourceFile:48)
[14:30:12] [Server thread/WARN]: 	at java.base/java.util.HashMap.computeIfAbsent(Unknown Source)
[14:30:12] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.AttributeMapBase.a(SourceFile:48)
[14:30:12] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R1.attribute.CraftAttributeMap.getAttribute(CraftAttributeMap.java:38)
[14:30:12] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R1.entity.CraftLivingEntity.getAttribute(CraftLivingEntity.java:642)
[14:30:12] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R1.event.CraftEventFactory.populateFields(CraftEventFactory.java:845)
[14:30:12] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R1.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:791)
[14:30:12] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.EntityLiving.d(EntityLiving.java:1489)
[14:30:12] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.EntityLiving.die(EntityLiving.java:1417)
[14:30:12] [Server thread/WARN]: 	at de.Keyle.MyPet.compat.v1_16_R1.entity.EntityMyPet.die(EntityMyPet.java:683)
[14:30:12] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.EntityLiving.damageEntity(EntityLiving.java:1261)
[14:30:12] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.EntityIronGolem.attackEntity(EntityIronGolem.java:149)
[14:30:12] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.PathfinderGoalMeleeAttack.a(SourceFile:142)
[14:30:12] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.PathfinderGoalMeleeAttack.e(SourceFile:134)
[14:30:12] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.PathfinderGoalWrapped.e(PathfinderGoalWrapped.java:54)
[14:30:12] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.PathfinderGoalSelector.doTick(PathfinderGoalSelector.java:153)
[14:30:12] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.EntityInsentient.doTick(EntityInsentient.java:757)
[14:30:12] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.EntityLiving.movementTick(EntityLiving.java:2743)
[14:30:12] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.EntityInsentient.movementTick(EntityInsentient.java:543)
[14:30:12] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.EntityIronGolem.movementTick(EntityIronGolem.java:69)
[14:30:12] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.EntityLiving.tick(EntityLiving.java:2468)
[14:30:12] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.EntityInsentient.tick(EntityInsentient.java:306)
[14:30:12] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.WorldServer.entityJoinedWorld(WorldServer.java:832)
[14:30:12] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.World.a(World.java:932)
[14:30:12] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.WorldServer.doTick(WorldServer.java:526)
[14:30:12] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.MinecraftServer.b(MinecraftServer.java:1353)
[14:30:12] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:377)
[14:30:12] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1212)
[14:30:12] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1000)
[14:30:12] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
[14:30:12] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Unknown Source)
```
