### ISSUE TITLE
1_16_R1.entity.types.EntityMySnowman(Snowman) is no valid MyPet(Entity)

### ISSUE THREAD

**Issue by andris155** [xXKeyleXx/MyPet#1390]
# Bug report

* [x] I have checked other issues to make sure this is not a duplicate.

## Describe the bug

_A clear and concise description of what the bug is._
1_16_R1.entity.types.EntityMySnowman(Snowman) is no valid MyPet(Entity) error

## To Reproduce

_Steps to reproduce the behavior, please provide code snippets or a repository:_

I don't know. The plugin flood this error. Maybe cause the Snowman pet.
...

## Expected behavior

_A clear and concise description of what you expected to happen._
No flood this error and snowman pet works

## Actual behaviour

_If applicable, add screenshots to help explain your problem._
Flood this error and snowman pet maybe not work.

## Additional context

> Please use the `/petadmin ticket` command and attach the generated `ticket.zip` from the MyPet folder to this issue.

**Bukkit/Spigot/Bungee Build/Version:** Paper build 90 1.16.1

**MyPet Build/Version:** 3.11-SNAPSHOT-B1553

**Error:**
```
[21:13:19 INFO]: [de.Keyle.MyPet.MyPetPlugin] [MyPet] de.Keyle.MyPet.compat.v1_16_R1.entity.types.EntityMySnowman(Snowman) is no valid MyPet(Entity)!
[21:13:19 WARN]: java.lang.reflect.InvocationTargetException
[21:13:19 WARN]: at jdk.internal.reflect.GeneratedConstructorAccessor170.newInstance(Unknown Source)
[21:13:19 WARN]: at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[21:13:19 WARN]: at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
[21:13:19 WARN]: at de.Keyle.MyPet.compat.v1_16_R1.entity.EntityRegistry.createMinecraftEntity(EntityRegistry.java:83)
[21:13:19 WARN]: at de.Keyle.MyPet.entity.MyPet.createEntity(MyPet.java:473)
[21:13:19 WARN]: at de.Keyle.MyPet.util.player.MyPetPlayerImpl.schedule(MyPetPlayerImpl.java:481)
[21:13:19 WARN]: at de.Keyle.MyPet.api.util.Timer.lambda$startTimer$2(Timer.java:62)
[21:13:19 WARN]: at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftTask.run(CraftTask.java:99)
[21:13:19 WARN]: at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468)
[21:13:19 WARN]: at net.minecraft.server.v1_16_R1.MinecraftServer.b(MinecraftServer.java:1291)
[21:13:19 WARN]: at net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:377)
[21:13:19 WARN]: at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1212)
[21:13:19 WARN]: at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1000)
[21:13:19 WARN]: at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
[21:13:19 WARN]: at java.base/java.lang.Thread.run(Unknown Source)
[21:13:19 WARN]: Caused by: java.lang.NullPointerException
```

**Comment by andris155** [comment]
Thanks!
