### ISSUE TITLE
Error !!!! SQL .

### ISSUE THREAD

**Issue by VVheyn** [xXKeyleXx/MyPet#1399]
org.sqlite.SQLiteException: [SQLITE_CONSTRAINT]  Abort due to constraint violation (UNIQUE constraint failed: players.name)
[05:49:29 WARN]:        at org.sqlite.core.DB.newSQLException(DB.java:941)
[05:49:29 WARN]:        at org.sqlite.core.DB.newSQLException(DB.java:953)
[05:49:29 WARN]:        at org.sqlite.core.DB.execute(DB.java:854)
[05:49:29 WARN]:        at org.sqlite.core.DB.executeUpdate(DB.java:895)
[05:49:29 WARN]:        at org.sqlite.jdbc3.JDBC3PreparedStatement.executeUpdate(JDBC3PreparedStatement.java:102)
[05:49:29 WARN]:        at de.Keyle.MyPet.repository.types.SqLiteRepository$14.run(SqLiteRepository.java:954)
[05:49:29 WARN]:        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:99)
[05:49:29 WARN]:        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[05:49:29 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[05:49:29 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[05:49:29 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[05:49:29 WARN]:        at java.base/java.lang.Thread.run(Thread.java:834)

why ???

**Comment by mustafavanli** [comment]
It's great that you responded after five years. Your help was very much appreciated. Thank you. ;=)

**Comment by UserDerezzed** [comment]
@mustafavanli Sorry to disappoint but I'm not associated with this plugin at all. I'm just a community developer trying to help clean up the project and fix bugs. 👍
