### ISSUE TITLE
My users tried to tame another user's pet.

### ISSUE THREAD

**Issue by Fidelloz00** [xXKeyleXx/MyPet#1451]
This happens when trying to tame a donkey that is already a pet.

[00:16:10] [Server thread/INFO]: Denle la bienvenida a goku123proaso
[00:16:10] [Server thread/WARN]: Entity threw exception at Eventos:-205.63050042647765,16.0625,63.67490002765592
[00:16:10] [Server thread/WARN]: java.lang.NoSuchMethodError: 'float net.minecraft.server.v1_16_R3.SoundEffectType.a()'
[00:16:10] [Server thread/WARN]: 	at de.Keyle.MyPet.compat.v1_16_R3.entity.types.EntityMyDonkey.playStepSound(EntityMyDonkey.java:225)
[00:16:10] [Server thread/WARN]: 	at de.Keyle.MyPet.compat.v1_16_R3.entity.EntityMyPet.b(EntityMyPet.java:927)
[00:16:10] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.Entity.move(Entity.java:783)
[00:16:10] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.EntityLiving.a(EntityLiving.java:2388)
[00:16:10] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.EntityLiving.g(EntityLiving.java:2347)
[00:16:10] [Server thread/WARN]: 	at de.Keyle.MyPet.compat.v1_16_R3.entity.EntityMyPet.f(EntityMyPet.java:1187)
[00:16:10] [Server thread/WARN]: 	at de.Keyle.MyPet.compat.v1_16_R3.entity.EntityMyPet.movementTick(EntityMyPet.java:1045)
[00:16:10] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.EntityLiving.tick(EntityLiving.java:2499)
[00:16:10] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.EntityInsentient.tick(EntityInsentient.java:310)
[00:16:10] [Server thread/WARN]: 	at de.Keyle.MyPet.compat.v1_16_R3.entity.EntityMyPet.tick(EntityMyPet.java:1338)
[00:16:10] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.WorldServer.entityJoinedWorld(WorldServer.java:1365)
[00:16:10] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.WorldServer.doTick(WorldServer.java:1001)
[00:16:10] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1419)
[00:16:10] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:379)
[00:16:10] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1269)
[00:16:10] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1001)
[00:16:10] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:175)
[00:16:10] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by andris155** [comment]
I fixed this error. Update the MyPet version.
