### ISSUE TITLE
[MyPet] Task #94 for MyPet v1.1.7 generated an exception

### ISSUE THREAD

**Issue by TadeCooper** [xXKeyleXx/MyPet#426]
There is something wrong in the console,I don't know what to do.
MyPet is keeping make warning,just like this:

[MyPet] Task #94 for MyPet v1.1.7 generated an exception
java.lang.NullPointerException
        at de.Keyle.MyPet.util.MyPetPlayer.schedule(MyPetPlayer.java:357) ~[?:?]
        at de.Keyle.MyPet.util.Timer$3.run(Timer.java:71) ~[?:?]
        at org.bukkit.craftbukkit.v1_7_R1.scheduler.CraftTask.run(CraftTask.java:67) ~[craftbukkit-1.7.2-gbk.jar:git-Spigot-1.7.2-R0.3-122-gb58e277]
        at org.bukkit.craftbukkit.v1_7_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:345) [craftbukkit-1.7.2-gbk.jar:git-Spigot-1.7.2-R0.3-122-gb58e277]
        at net.minecraft.server.v1_7_R1.MinecraftServer.u(MinecraftServer.java:614) [craftbukkit-1.7.2-gbk.jar:git-Spigot-1.7.2-R0.3-122-gb58e277]
        at net.minecraft.server.v1_7_R1.DedicatedServer.u(DedicatedServer.java:273) [craftbukkit-1.7.2-gbk.jar:git-Spigot-1.7.2-R0.3-122-gb58e277]
        at net.minecraft.server.v1_7_R1.MinecraftServer.t(MinecraftServer.java:562) [craftbukkit-1.7.2-gbk.jar:git-Spigot-1.7.2-R0.3-122-gb58e277]
        at net.minecraft.server.v1_7_R1.MinecraftServer.run(MinecraftServer.java:469) [craftbukkit-1.7.2-gbk.jar:git-Spigot-1.7.2-R0.3-122-gb58e277]
        at net.minecraft.server.v1_7_R1.ThreadServerApplication.run(SourceFile:617) [craftbukkit-1.7.2-gbk.jar:git-Spigot-1.7.2-R0.3-122-gb58e277]

**Comment by xXKeyleXx** [comment]
MyPet 1.1.7 is more than a year old so I can't and wont fix any bugs that may occour in this version :/
