### ISSUE TITLE
Players cant release Enderman

### ISSUE THREAD

**Issue by ScuroK** [xXKeyleXx/MyPet#430]
People can not /petrelease Endermen. /petadmin remove does also not work for Endermen. 
There is not much in the console exept an error.

Zeile 19796: [15:07:08] [Server thread/ERROR]: null
Zeile 19688: [15:05:28] [Server thread/ERROR]: null
Zeile 19661: [15:05:27] [Server thread/ERROR]: null
Zeile 19630: [15:05:20] [Server thread/ERROR]: null
Zeile 19563: [15:04:46] [Server thread/ERROR]: null
Zeile 19524: [15:04:23] [Server thread/ERROR]: null
Zeile 19405: [15:01:22] [Server thread/ERROR]: null
Zeile 19364: [15:00:35] [Server thread/WARN]: HonigKuchen9000 moved wrongly!
Zeile 19363: [15:00:35] [Server thread/WARN]: Taucher_Nick moved wrongly!
Zeile 19362: [15:00:35] [Server thread/WARN]: HonigKuchen9000 moved wrongly!
Zeile 18952: [14:54:04] [Server thread/WARN]: Braunbaer1848 moved wrongly!
Zeile 18865: [14:52:47] [Server thread/WARN]: McSleeper moved wrongly!
Zeile 18763: [14:51:49] [Server thread/WARN]: [MyPet] Task #278281 for MyPet v1.2.1 generated an exception

**Comment by ScuroK** [comment]
Here is another error i found. but i dont know if this has something to do with the enderman problem:
Zeile 2371: [09:15:24] [Server thread/ERROR]: Could not pass event PlayerChangedWorldEvent to MyPet v1.2.1

**Comment by xXKeyleXx** [comment]
Ich brauch den Rest der Fehlermeldung ;) der Teil ist völlig nutzlos :P

**Comment by ScuroK** [comment]
Ich konnte nicht mehr dazu finden in der Konsole! Ich bin auch nicht der einzige der diesen Bug bisher gemeldet hat. Vielleicht kannst du es mal selber ausprobieren? Es ist der letzte wirklich nervige Bug denk ich! Danke und liebe Grüsse ScuroK

**Comment by xXKeyleXx** [comment]
Da muss mehr sein. Am Besten lädste mal den kompletten serverlog hoch, dann kann ich selber suchen :P

**Comment by ScuroK** [comment]
09:02:27] [Server thread/INFO]: PabloEscobar05 issued server command: /petrelease Enderman
[09:02:27] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'petrelease' in plugin MyPet v1.2.1
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[craftbukkit.jar:git-Spigot-d0d1d87-15e81cf]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[craftbukkit.jar:git-Spigot-d0d1d87-15e81cf]
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(CraftServer.java:646) ~[craftbukkit.jar:git-Spigot-d0d1d87-15e81cf]
	at net.minecraft.server.v1_8_R1.PlayerConnection.handleCommand(PlayerConnection.java:1115) [craftbukkit.jar:git-Spigot-d0d1d87-15e81cf]
	at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:950) [craftbukkit.jar:git-Spigot-d0d1d87-15e81cf]
	at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:26) [craftbukkit.jar:git-Spigot-d0d1d87-15e81cf]
	at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:53) [craftbukkit.jar:git-Spigot-d0d1d87-15e81cf]
	at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13) [craftbukkit.jar:git-Spigot-d0d1d87-15e81cf]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.7.0_71]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.7.0_71]
	at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:683) [craftbukkit.jar:git-Spigot-d0d1d87-15e81cf]
	at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [craftbukkit.jar:git-Spigot-d0d1d87-15e81cf]
	at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:623) [craftbukkit.jar:git-Spigot-d0d1d87-15e81cf]
	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:526) [craftbukkit.jar:git-Spigot-d0d1d87-15e81cf]
	at java.lang.Thread.run(Unknown Source) [?:1.7.0_71]
Caused by: java.lang.NullPointerException
	at de.Keyle.MyPet.skill.skills.implementation.inventory.ItemStackNBTConverter.itemStackToCompund(ItemStackNBTConverter.java:37) ~[?:?]
	at de.Keyle.MyPet.entity.types.enderman.MyEnderman.writeExtendedInfo(MyEnderman.java:56) ~[?:?]
	at de.Keyle.MyPet.entity.types.MyPetList.getInactiveMyPetFromMyPet(MyPetList.java:149) ~[?:?]
	at de.Keyle.MyPet.entity.types.MyPetList.setMyPetInactive(MyPetList.java:216) ~[?:?]
	at de.Keyle.MyPet.commands.CommandRelease.onCommand(CommandRelease.java:235) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[craftbukkit.jar:git-Spigot-d0d1d87-15e81cf]
	... 14 more

**Comment by ScuroK** [comment]
https://dl.dropboxusercontent.com/u/30946963/2015-02-01-3.log

**Comment by xXKeyleXx** [comment]
könnteste den PabloEscobar05 mal fragen was für nen BLock sein Enderman hatte?

**Comment by ScuroK** [comment]
Ich weiss nicht ob ich ihn nochmal treffe aber ich kanns sonst selber testen mit allen Blöcken...

**Comment by xXKeyleXx** [comment]
Ne das wär ein wenig übertrieben ;) Ich versuchs einfach mal.

**Comment by ScuroK** [comment]
OK ich hoffe du schaffst es!

**Comment by xXKeyleXx** [comment]
Tritt der Fehler immer noch auf? Wenn ja lad mir mal bitte deine My.Pet Datei hoch.

**Comment by ScuroK** [comment]
Ja der Fehler tritt noch immer auf. Auch wenn der Enderman nichts  in der Hand hat. Zudem greift er Spieler in "AcidIsland" an, obwohl pvp aus ist. Hier die my.pets-Datei:
https://dl.dropboxusercontent.com/u/30946963/My.Pets

**Comment by xXKeyleXx** [comment]
Ach du scheiße xD 989 Pets..... Wie soll ich denn da den Enderman finden xD

**Comment by ScuroK** [comment]
ich mach was du mir sagst... du hättest ja auch einen eigenen server zum testen...

**Comment by xXKeyleXx** [comment]
Versuch bitte mal den Fehler mit der Version zu provozieren (https://dl.dropboxusercontent.com/u/23957620/crap/MyPet-1.8-1.2.1-SNAPSHOT.jar). Wenn der Fehler auftritt müsste da ne Zeile, die mit vielen Gs anfängt, erscheinen. Die Zeile brauch ich :P

**Comment by ScuroK** [comment]
Ok ich mach es mal auf meinem testserver, warte eine weile

**Comment by ScuroK** [comment]
Ok ich mach es mal auf meinem testserver, warte eine weile

**Comment by ScuroK** [comment]
Ok ich mach es mal auf meinem testserver, warte eine weile

**Comment by ScuroK** [comment]
Ok ich mach es mal auf meinem testserver, warte eine weile

**Comment by ScuroK** [comment]
wo müsste die zeile sein im log oder im my.pets? ich update gerade den testserver und dann fang ich an

**Comment by xXKeyleXx** [comment]
Einmal hätte auch gereicht :P Wenn keine Texte angezeigt werden sollten einfach die Datei nochmal neu runterladen.

**Comment by xXKeyleXx** [comment]
im Log

**Comment by ScuroK** [comment]
ok warte

**Comment by ScuroK** [comment]
Leider konnte ich den Fehler auf dem Testserver nicht provozieren. Ich hatte Mypet komplett neu installiert mit der Version die du mir oben gegeben hattest. Ob da was in den Files auf meinem anderen Server nicht stimmt? Dennoch gabs jede Menge Meldungen im log:
https://dl.dropboxusercontent.com/u/30946963/latest.log

**Comment by ScuroK** [comment]
Viele G's sieht man zumindest in dem log!

**Comment by xXKeyleXx** [comment]
Das ist alles was ich brauchte :D Wie hat es der Typ geschaft nem Enderman Air zu geben? xD

**Comment by ScuroK** [comment]
Welcher Typ?? :D

**Comment by xXKeyleXx** [comment]
derjenige mit dem Enderman :D Typ war vllt nicht die beste Bezeichnung.

**Comment by ScuroK** [comment]
Im neusten Log? das bin ich -.- :D naja das frag ich dich ;) vieleicht mit sneaken und leerer hand? keine ahnung xD kannst du es fixen?

**Comment by ScuroK** [comment]
viele haben den bug mit dem enderman gemeldet nicht nur einer!

**Comment by xXKeyleXx** [comment]
Das könnte gut sein! Au man xD auf sowas muss man ersmal kommen :D Danke, ich fix das später.

**Comment by ScuroK** [comment]
Ich danke dir! Viel glück ich freu mich wenn du es schaffst! :dancer:

**Comment by ScuroK** [comment]
oder evt. wenn die spieler versuchen, dem enderman ein schwert oder rüstung zu geben so wie es bei zombies möglich ist!!

**Comment by ScuroK** [comment]
Achja und gib mir mal deine kontoangaben. Ich hab kein paypal

**Comment by xXKeyleXx** [comment]
Bug sollte gefixt sein. Ich schick dir später ne PN auf BukkitDev.

**Comment by ScuroK** [comment]
danke ich versuchs gleich mal :)
