### ISSUE TITLE
problem xXKeyleXx Germany

### ISSUE THREAD

**Issue by DARTHVADER231** [xXKeyleXx/MyPet#433]
Bitte antworte in Deutsch

**Comment by DARTHVADER231** [comment]
Germany xXKeyleXx?

Wen sie Deutscher/e sind ,Ich habe ein problem ich habe mir Mypet runtergeladen und auf mein server gemacht aber ich kann nix machen keine /pet oder egal was von Mypet und ich habe auch keine config und so alle ordner leer

Eglish: 
I have a problem I have downloaded and Mypet made on my server but I can not do nothing / pet or whatever of Mypet and I have no config and so all the folder is empty

**Comment by xXKeyleXx** [comment]
Wenn das der Fall sein sollte steht auch was dazu im Serverlog.

Und der Issue Titel is ja ma sowas von unpassend xD

**Comment by DARTHVADER231** [comment]
ok werde mal gucken

**Comment by DARTHVADER231** [comment]
>
[22:07:13 INFO]: [MyPet] Enabling MyPet v1.1.9
>
[22:07:13 ERROR]: Error occurred while enabling MyPet v1.1.9 (Is it up to date?)
java.lang.NoClassDefFoundError: net/minecraft/server/v1_7_R2/Packet
        at de.Keyle.MyPet.util.Configuration.setDefault(Configuration.java:173) ~[MyPet-1.1.9-SNAPSHOT.jar:?]
        at de.Keyle.MyPet.MyPetPlugin.onEnable(MyPetPlugin.java:138) ~[MyPet-1.1.9-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:250) ~[craftbukkit.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:350) [craftbukkit.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:389) [craftbukkit.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
        at org.bukkit.craftbukkit.v1_7_R1.CraftServer.loadPlugin(CraftServer.java:439) [craftbukkit.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
        at org.bukkit.craftbukkit.v1_7_R1.CraftServer.enablePlugins(CraftServer.java:375) [craftbukkit.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
        at net.minecraft.server.v1_7_R1.MinecraftServer.m(MinecraftServer.java:342) [craftbukkit.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
        at net.minecraft.server.v1_7_R1.MinecraftServer.g(MinecraftServer.java:319) [craftbukkit.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
        at net.minecraft.server.v1_7_R1.MinecraftServer.a(MinecraftServer.java:275) [craftbukkit.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
        at net.minecraft.server.v1_7_R1.DedicatedServer.init(DedicatedServer.java:175) [craftbukkit.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
        at net.minecraft.server.v1_7_R1.MinecraftServer.run(MinecraftServer.java:424) [craftbukkit.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
        at net.minecraft.server.v1_7_R1.ThreadServerApplication.run(SourceFile:617) [craftbukkit.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_7_R2.Packet
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:67) ~[craftbukkit.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:62) ~[craftbukkit.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_71]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_71]
        ... 13 more

Das steht Für MyPet

**Comment by xXKeyleXx** [comment]
MyPet 1.1.9 funktioniert nur mit Minecraft 1.7.9
