### ISSUE TITLE
When I try to change my pet's name

### ISSUE THREAD

**Issue by HardKrab** [xXKeyleXx/MyPet#453]
[20:46:21] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'petname' in plugin MyPet v1.1.7
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[PluginCommand.class:git-Cauldron-MCPC-Plus-1.7.2-1.1147.04.90]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:175) ~[SimpleCommandMap.class:git-Cauldron-MCPC-Plus-1.7.2-1.1147.04.90]
	at org.bukkit.craftbukkit.v1_7_R1.CraftServer.dispatchCommand(CraftServer.java:648) ~[CraftServer.class:git-Cauldron-MCPC-Plus-1.7.2-1.1147.04.90]
	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1360) [mx.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1127) [mx.class:?]
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:38) [ie.class:?]
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:53) [ie.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:206) [ef.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173) [ms.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:953) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432) [lj.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:783) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:646) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.7.0_72]
Caused by: java.lang.NoSuchMethodError: de.Keyle.MyPet.entity.types.EntityMyPet.setCustomNameVisible(Z)V
	at de.Keyle.MyPet.entity.types.MyPet.setPetName(MyPet.java:213) ~[?:?]
	at de.Keyle.MyPet.commands.CommandName.onCommand(CommandName.java:74) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[PluginCommand.class:git-Cauldron-MCPC-Plus-1.7.2-1.1147.04.90]
	... 13 more

**Comment by zerafox** [comment]
Keep in mind MyPet wasn't written for Cauldron back then, it was written for CraftBukkit specifically, so there may be features that just aren't handled well or at all on anything but CraftBukkit.

Considering it looks like you are running 1.1.7 on a 1.7.2 server (you didn't exactly provide that information, like you should. :P) it's not a version issue.
Is there anything more you can share in the MyPet.log? Any and all information always helps when encountering issues. However, also keep in mind that 1.1.7 is an old version and is no longer supported too.
