### ISSUE TITLE
pet don't release on death 

### ISSUE THREAD

**Issue by Caimas** [xXKeyleXx/MyPet#470]
hi, I said true on pet release on death and the pet just respawn, i think the problem come from somewhere else because if we do, /petrelease name, the pet is not here, but don't release. like "pcsa''. you can do /pc after. it's a small rp rp server, for other plugin i have health bar and mythic drop and a lots of mods. I copi paste the config file. (sorry for my english, it's not my first langage)

**Comment by xXKeyleXx** [comment]
There should be an error in the server logs.please post that error on pastebin and provide me the link.

**Comment by Caimas** [comment]
i don't know whar paste bin is, but i found the message of the error (i stopped the server manually after to get it) 
:  [21:26:59] [Server thread/INFO]: Yakulong issued server command: /pc
[21:27:22] [Server thread/INFO]: Yakulong issued server command: /petrelease pig
[21:27:22] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'petrelease' in plugin MyPet v1.2.1
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[PluginCommand.class:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) ~[SimpleCommandMap.class:?]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:717) ~[CraftServer.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1347) [nh.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1129) [nh.class:?]
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:38) [ir.class:?]
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:53) [ir.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:244) [ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173) [nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:980) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.7.0_60]
Caused by: java.lang.NoSuchFieldError: dead
	at de.Keyle.MyPet.entity.types.MyPet.removePet(MyPet.java:406) ~[?:?]
	at de.Keyle.MyPet.entity.types.MyPet.removePet(MyPet.java:398) ~[?:?]
	at de.Keyle.MyPet.commands.CommandRelease.onCommand(CommandRelease.java:220) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[PluginCommand.class:?]
	... 13 more
[21:27:47] [Server thread/INFO]: CONSOLE: Stopping the server..
[21:27:47] [Server thread/INFO]: Stopping server
[21:27:47] [Server thread/INFO]: [MythicDrops] Disabling MythicDrops v3.0.1-b346-STABLE
[21:27:47] [Server thread/INFO]: [HealthBar] Disabling HealthBar v1.8.2
[21:27:47] [Server thread/INFO]: HealthBar disabled, all the health bars have been removed.
[21:27:47] [Server thread/INFO]: [MyPet] Disabling MyPet v1.2.1
[21:27:47] [Server thread/INFO]: Saving players
[21:27:47] [Server thread/INFO]: Yakulong lost connection: Server closed
[21:27:47] [Server thread/INFO]: Yakulong left the game.
[21:27:47] [Server thread/INFO]: Saving worlds
[21:27:47] [Server thread/INFO]: Saving chunks for level 'world'/Overworld
[21:27:48] [Server thread/INFO]: Saving chunks for level 'DIM1'/The End
[21:27:48] [Server thread/INFO]: Saving chunks for level 'DIM-1'/Nether
[21:27:48] [Server thread/INFO]: Unloading dimension 0
[21:27:48] [Server thread/INFO]: Unloading dimension -1
[21:27:48] [Server thread/INFO]: Unloading dimension 1
[21:27:48] [Server thread/INFO]: Applying holder lookups
[21:27:48] [Server thread/INFO]: Holder lookups applied

**Comment by zerafox** [comment]
Pastebin is a website where you can paste things into a tidy/neat little "file" and provide us a link to view it. :P
Should give it a google search sometime. xD

**Comment by Caimas** [comment]
sorry, i was tired, i feel stupid now, by the way english is not my first langage so sorry if sometime i write wrong, here is the link, i put just the error , think that will be more easy for you like that : http://pastebin.com/zLMreWsW

**Comment by xXKeyleXx** [comment]
Do you use Cauldron or any non Bukkit/Spigot server?

**Comment by Caimas** [comment]
i have  cauldronbukkit-1.7.10-1.1207.01.198, but it's the only plugins that give me problems.  (of course i hav my pet 1.7.10)

**Comment by Caimas** [comment]
i had a compatibily problem with one of my mod or plugin, i deleted some and now i don't have any problem, sorry by the way for my ''bad english'' it's not my first langage but i try

**Comment by zerafox** [comment]
So you've resolved your issue then?
What if I may ask, was the conflicting Mod or Plugin that caused MyPet to not work properly?

**Comment by Caimas** [comment]
i deleted 5 mods, ( Better-Breeds, Familiar Api, le chunk du milieu, medieval mob , mo skeleton. healt bar and mythic drop, as plugin but i don't thinks it's the others plugins. that was by luck, i deleted them just because i didn't find them so necessary . actually i don't have any bugs to release the pets, but still don't release when they die.

**Comment by zerafox** [comment]
Considering you are running a Non-Bukkit/Spigot server, MyPet isn't guaranteed to work 100% anyway.
I am also not sure if the Pet Release on Death, is if the pet dies, or if the player dies. I cannot say it's a feature I've ever personally used.
