### ISSUE TITLE
MyPet-1.1.9 - 1.2.2 dont work

### ISSUE THREAD

**Issue by SecretSmoky** [xXKeyleXx/MyPet#475]
Everytime I start my Server I get a an errormessage. And MyPet create a Pluginfolder but no Files.
I tried to use MyPet version 1.1.9 till 1.2.2 but everytime the same Problem.
I testet all versions of MyPet with MC Serverversion: 1.8-R0.1-SNAPSHOT

[14:30:42] [Server thread/ERROR]: Error occurred while enabling MyPet v1.2.0 (Is it up to date?)
java.lang.NoClassDefFoundError: net/minecraft/server/v1_7_R3/Packet
	at de.Keyle.MyPet.util.Configuration.setDefault(Configuration.java:175) ~[?:?]
	at de.Keyle.MyPet.MyPetPlugin.onEnable(MyPetPlugin.java:138) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot_server.jar:git-Spigot-b1e6da1-17962f6]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335) [spigot_server.jar:git-Spigot-b1e6da1-17962f6]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot_server.jar:git-Spigot-b1e6da1-17962f6]
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugin(CraftServer.java:355) [spigot_server.jar:git-Spigot-b1e6da1-17962f6]
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.enablePlugins(CraftServer.java:315) [spigot_server.jar:git-Spigot-b1e6da1-17962f6]
	at net.minecraft.server.v1_8_R1.MinecraftServer.q(MinecraftServer.java:402) [spigot_server.jar:git-Spigot-b1e6da1-17962f6]
	at net.minecraft.server.v1_8_R1.MinecraftServer.k(MinecraftServer.java:370) [spigot_server.jar:git-Spigot-b1e6da1-17962f6]
	at net.minecraft.server.v1_8_R1.MinecraftServer.a(MinecraftServer.java:325) [spigot_server.jar:git-Spigot-b1e6da1-17962f6]
	at net.minecraft.server.v1_8_R1.DedicatedServer.init(DedicatedServer.java:211) [spigot_server.jar:git-Spigot-b1e6da1-17962f6]
	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:494) [spigot_server.jar:git-Spigot-b1e6da1-17962f6]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_45]
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_7_R3.Packet
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91) ~[spigot_server.jar:git-Spigot-b1e6da1-17962f6]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot_server.jar:git-Spigot-b1e6da1-17962f6]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_45]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_45]
	... 13 more

**Comment by xXKeyleXx** [comment]
I wrote to compatible Bukkit/Minecraft version below every MyPet version so start reading.
