### ISSUE TITLE
Error occurred while enabling MyPet

### ISSUE THREAD

**Issue by DirolGaming** [xXKeyleXx/MyPet#484]
So basically i'm having trouble enabling the plugin on my server.
Server version: 1.8
Error:
[16:40:45] [Server thread/ERROR]: Error occurred while enabling MyPet v1.2.2 (Is it up to date?)
java.lang.NoClassDefFoundError: net/minecraft/server/v1_8_R3/Packet
	at de.Keyle.MyPet.util.Configuration.setDefault(Configuration.java:180) ~[?:?]
	at de.Keyle.MyPet.MyPetPlugin.onEnable(MyPetPlugin.java:143) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot-BT36_1.8_04.29.jar:git-Spigot-550ebac-7019900]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335) [spigot-BT36_1.8_04.29.jar:git-Spigot-550ebac-7019900]
	at us.Myles.PWP.TransparentListeners.PerWorldPluginLoader.enablePlugin(PerWorldPluginLoader.java:145) [PerWorldPlugins%20(1).jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-BT36_1.8_04.29.jar:git-Spigot-550ebac-7019900]
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugin(CraftServer.java:356) [spigot-BT36_1.8_04.29.jar:git-Spigot-550ebac-7019900]
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.enablePlugins(CraftServer.java:316) [spigot-BT36_1.8_04.29.jar:git-Spigot-550ebac-7019900]
	at net.minecraft.server.v1_8_R1.MinecraftServer.q(MinecraftServer.java:402) [spigot-BT36_1.8_04.29.jar:git-Spigot-550ebac-7019900]
	at net.minecraft.server.v1_8_R1.MinecraftServer.k(MinecraftServer.java:370) [spigot-BT36_1.8_04.29.jar:git-Spigot-550ebac-7019900]
	at net.minecraft.server.v1_8_R1.MinecraftServer.a(MinecraftServer.java:325) [spigot-BT36_1.8_04.29.jar:git-Spigot-550ebac-7019900]
	at net.minecraft.server.v1_8_R1.DedicatedServer.init(DedicatedServer.java:211) [spigot-BT36_1.8_04.29.jar:git-Spigot-550ebac-7019900]
	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:505) [spigot-BT36_1.8_04.29.jar:git-Spigot-550ebac-7019900]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_8_R3.Packet
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91) ~[spigot-BT36_1.8_04.29.jar:git-Spigot-550ebac-7019900]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-BT36_1.8_04.29.jar:git-Spigot-550ebac-7019900]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_45]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_45]
	... 14 more

MyPet files are all empty.

**Comment by zerafox** [comment]
Spigot 1.8?

1.2.2 was written for 1.8.+

Try downgrading your MyPet if you are only running a 1.8 server. You'll want a 1.2.1 version of MyPet I believe.

**Comment by DirolGaming** [comment]
Downgraded it, still the same.

[17:37:06] [Server thread/INFO]: [MyPet] Enabling MyPet v1.2.1
[17:37:06] [Server thread/ERROR]: Error occurred while enabling MyPet v1.2.1 (Is it up to date?)
java.lang.NoClassDefFoundError: net/minecraft/server/v1_8_R2/Packet
	at de.Keyle.MyPet.util.Configuration.setDefault(Configuration.java:178) ~[?:?]
	at de.Keyle.MyPet.MyPetPlugin.onEnable(MyPetPlugin.java:142) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot-BT36_1.8_04.29.jar:git-Spigot-550ebac-7019900]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335) [spigot-BT36_1.8_04.29.jar:git-Spigot-550ebac-7019900]
	at us.Myles.PWP.TransparentListeners.PerWorldPluginLoader.enablePlugin(PerWorldPluginLoader.java:145) [PerWorldPlugins%20(1).jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-BT36_1.8_04.29.jar:git-Spigot-550ebac-7019900]
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugin(CraftServer.java:356) [spigot-BT36_1.8_04.29.jar:git-Spigot-550ebac-7019900]
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.enablePlugins(CraftServer.java:316) [spigot-BT36_1.8_04.29.jar:git-Spigot-550ebac-7019900]
	at net.minecraft.server.v1_8_R1.MinecraftServer.q(MinecraftServer.java:402) [spigot-BT36_1.8_04.29.jar:git-Spigot-550ebac-7019900]
	at net.minecraft.server.v1_8_R1.MinecraftServer.k(MinecraftServer.java:370) [spigot-BT36_1.8_04.29.jar:git-Spigot-550ebac-7019900]
	at net.minecraft.server.v1_8_R1.MinecraftServer.a(MinecraftServer.java:325) [spigot-BT36_1.8_04.29.jar:git-Spigot-550ebac-7019900]
	at net.minecraft.server.v1_8_R1.DedicatedServer.init(DedicatedServer.java:211) [spigot-BT36_1.8_04.29.jar:git-Spigot-550ebac-7019900]
	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:505) [spigot-BT36_1.8_04.29.jar:git-Spigot-550ebac-7019900]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_8_R2.Packet
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91) ~[spigot-BT36_1.8_04.29.jar:git-Spigot-550ebac-7019900]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-BT36_1.8_04.29.jar:git-Spigot-550ebac-7019900]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_45]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_45]
	... 14 more

**Comment by zerafox** [comment]
You are running, Spigot, yes?
There are multiple server types out there, you never clarified which you were running... MyPet won't run on all of them...

Also it is just a flat 1.8 server? Not a 1.8.1, or a 1.8.3?
I'm afraid the information you give is kind of vague.. xD

**Comment by DirolGaming** [comment]
Maybe this will help.
![](http://i.gyazo.com/3ee4a76bc821176f9e21a8b665c171fd.png)

**Comment by zerafox** [comment]
A 1.2.1 version should work just fine then, so why you're getting the outdated error is beyond me.
Assuming that the 1.2.1 version is actually written for 1.8 and not 1.8.1, but I believe those were all compatible between one another.
At this point I can only suggest 1 of 2 things. You try all the Dev Builds of 1.2.1 for your server until you find a build that works; or you wait until Keyle can get to your ticket and perhaps help you better than I can.
It appears the version you have on your server might be 1 version too high.

java.lang.NoClassDefFoundError: net/minecraft/server/v1_8_R2/Packet

It's attempting to find things in an R2 where your server is running 1.8 R1.
That is only my guess, I am still not 100% on reading error messages, but from a 'simple stand-point' that would be my first guess anyway.


Since I am unsure of the Build # of MyPet you are using, I would suggest trying a build between 647 and 669.

**Comment by xXKeyleXx** [comment]
http://build.keyle.de/job/MyPet/669/ should work for you. Why is it so hard to find it? I marked every Minecraft version update and every upload on BukkitDev has a textline that gives you the one and only working Bukkit version. Please give me feedback ....

**Comment by DirolGaming** [comment]
The plugin seems to be working, thank you.
