### ISSUE TITLE
NPE in UltimateSurvivalGames support

### ISSUE THREAD

**Issue by PikachuEXE** [xXKeyleXx/MyPet#487]
# Env
- Plugin Version: [Build 688](http://build.keyle.de/job/MyPet/688/)
- Bukkit Version: Spigot 1.8.7

# Log
```
[21:55:32] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'petcall' in plugin MyPet v1.2.2
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-3ccbe77-a6a57a9]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot.jar:git-Spigot-3ccbe77-a6a57a9]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:642) ~[spigot.jar:git-Spigot-3ccbe77-a6a57a9]
	at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1135) [spigot.jar:git-Spigot-3ccbe77-a6a57a9]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:970) [spigot.jar:git-Spigot-3ccbe77-a6a57a9]
	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot.jar:git-Spigot-3ccbe77-a6a57a9]
	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot.jar:git-Spigot-3ccbe77-a6a57a9]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-3ccbe77-a6a57a9]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_11]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_11]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SystemUtils.java:19) [spigot.jar:git-Spigot-3ccbe77-a6a57a9]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:718) [spigot.jar:git-Spigot-3ccbe77-a6a57a9]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:367) [spigot.jar:git-Spigot-3ccbe77-a6a57a9]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:657) [spigot.jar:git-Spigot-3ccbe77-a6a57a9]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:560) [spigot.jar:git-Spigot-3ccbe77-a6a57a9]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_11]
Caused by: java.lang.NoClassDefFoundError: me/maker56/survivalgames/SurvivalGames
	at de.Keyle.MyPet.util.hooks.arenas.UltimateSurvivalGames.isInSurvivalGames(UltimateSurvivalGames.java:50) ~[?:?]
	at de.Keyle.MyPet.entity.types.MyPet.createPet(MyPet.java:377) ~[?:?]
	at de.Keyle.MyPet.commands.CommandCall.onCommand(CommandCall.java:41) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-3ccbe77-a6a57a9]
	... 15 more
```

**Comment by xXKeyleXx** [comment]
Your SurvivalGames version would be good to know.

**Comment by PikachuEXE** [comment]
I have http://dev.bukkit.org/bukkit-plugins/survival-games/
But not http://dev.bukkit.org/bukkit-plugins/ultimatesurvivalgames/

**Comment by xXKeyleXx** [comment]
Survival Games had it's last update in 2013. Are you sure you use this one?

**Comment by PikachuEXE** [comment]
I confirm I am using http://dev.bukkit.org/bukkit-plugins/survival-games/
not http://dev.bukkit.org/bukkit-plugins/ultimatesurvivalgames/

**Comment by PikachuEXE** [comment]
`plugin.yml`:
```yaml
name: SurvivalGames
version: 0.5.8.54
main: org.mcsg.survivalgames.SurvivalGames
authors: [Double0negative]
description: Fully Automated Hunger Games Plugin!

commands:
    survivalgames:
        description: Survival Games Command
        usage: /sg <command> <args>
        aliases: [sg, hungergames, hg]
```

**Comment by xXKeyleXx** [comment]
Could you please use the "/petadmin ticket" command and upload the ticket.zip from the MyPet folder for me?

**Comment by PikachuEXE** [comment]
http://www.mediafire.com/download/nspu5nspa8fapl5/ticket.zip

**Comment by PikachuEXE** [comment]
Hi dear author,

Do you have time to look into this?
I just want to know the progress and see what other information I can provide to help solve this issue.

**Comment by PikachuEXE** [comment]
It seems the issue is fixed, verified by using build 691.
Thanks!
