### ISSUE TITLE
My Pet [Is it up to date] ??

### ISSUE THREAD

**Issue by PinoyLifeCraft** [xXKeyleXx/MyPet#511]
[20:58:34 INFO]: [MyPet] Enabling MyPet v1.2.1
[20:58:34 ERROR]: Error occurred while enabling MyPet v1.2.1 (Is it up to date?)

java.lang.NoClassDefFoundError: net/minecraft/server/v1_8_R2/Packet
        at de.Keyle.MyPet.util.Configuration.setDefault(Configuration.java:178)
~[?:?]
        at de.Keyle.MyPet.MyPetPlugin.onEnable(MyPetPlugin.java:142) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[c
raftbukkit.jar:git-Bukkit-33d5de3]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader
.java:327) [craftbukkit.jar:git-Bukkit-33d5de3]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManage
r.java:404) [craftbukkit.jar:git-Bukkit-33d5de3]
        at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugin(CraftServer.jav
a:341) [craftbukkit.jar:git-Bukkit-33d5de3]
        at org.bukkit.craftbukkit.v1_8_R1.CraftServer.enablePlugins(CraftServer.
java:313) [craftbukkit.jar:git-Bukkit-33d5de3]
        at net.minecraft.server.v1_8_R1.MinecraftServer.q(MinecraftServer.java:3
94) [craftbukkit.jar:git-Bukkit-33d5de3]
        at net.minecraft.server.v1_8_R1.MinecraftServer.k(MinecraftServer.java:3
62) [craftbukkit.jar:git-Bukkit-33d5de3]
        at net.minecraft.server.v1_8_R1.MinecraftServer.a(MinecraftServer.java:3
17) [craftbukkit.jar:git-Bukkit-33d5de3]
        at net.minecraft.server.v1_8_R1.DedicatedServer.init(DedicatedServer.jav
a:190) [craftbukkit.jar:git-Bukkit-33d5de3]
        at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java
:484) [craftbukkit.jar:git-Bukkit-33d5de3]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_45]
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_8_R2.Packet

        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.
java:67) ~[craftbukkit.jar:git-Bukkit-33d5de3]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.
java:62) ~[craftbukkit.jar:git-Bukkit-33d5de3]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_45]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_45]
        ... 13 more

**Comment by PinoyLifeCraft** [comment]
my pet is not working in 1.8.1 :question:  :(

**Comment by xXKeyleXx** [comment]
It works but you used the wrong build for 1.8.1

**Comment by xXKeyleXx** [comment]
http://build.keyle.de/job/MyPet/687/

**Comment by PinoyLifeCraft** [comment]
Hellow are you the owner of the plugin 
Thanks!

**Comment by PinoyLifeCraft** [comment]
I can't tame pet i use Lead and i just kill the mob
Pls help :smiley: :

**Comment by PinoyLifeCraft** [comment]
i receive again the error message [is it up to date]
:disappointed:
