### ISSUE TITLE
World change error

### ISSUE THREAD

**Issue by xion87** [xXKeyleXx/MyPet#561]
Sometimes i get this spam on console... i got multiverse  and pet disabled in some worlds...
01:23:52] [Server thread/ERROR]: Could not pass event PlayerChangedWorldEvent to MyPet v1.2.2
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot.jar:git-Spigot-5f38d38-12698ea]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-5f38d38-12698ea]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-5f38d38-12698ea]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-5f38d38-12698ea]
	at net.minecraft.server.v1_8_R3.PlayerList.moveToWorld(PlayerList.java:628) [spigot.jar:git-Spigot-5f38d38-12698ea]
	at org.bukkit.craftbukkit.v1_8_R3.entity.CraftPlayer.teleport(CraftPlayer.java:471) [spigot.jar:git-Spigot-5f38d38-12698ea]
	at org.bukkit.craftbukkit.v1_8_R3.entity.CraftEntity.teleport(CraftEntity.java:226) [spigot.jar:git-Spigot-5f38d38-12698ea]
	at org.cyberiantiger.minecraft.ducksuite.teleports.listeners.TeleportsListener.playerConnect(TeleportsListener.java:35) [ducksuite-teleports-1.0-SNAPSHOT.jar:?]
	at sun.reflect.GeneratedMethodAccessor532.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_66]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_66]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) [spigot.jar:git-Spigot-5f38d38-12698ea]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [spigot.jar:git-Spigot-5f38d38-12698ea]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-5f38d38-12698ea]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-5f38d38-12698ea]
	at net.minecraft.server.v1_8_R3.PlayerList.onPlayerJoin(PlayerList.java:298) [spigot.jar:git-Spigot-5f38d38-12698ea]
	at net.minecraft.server.v1_8_R3.PlayerList.a(PlayerList.java:157) [spigot.jar:git-Spigot-5f38d38-12698ea]
	at net.minecraft.server.v1_8_R3.LoginListener.b(LoginListener.java:144) [spigot.jar:git-Spigot-5f38d38-12698ea]
	at net.minecraft.server.v1_8_R3.LoginListener.c(LoginListener.java:54) [spigot.jar:git-Spigot-5f38d38-12698ea]
	at net.minecraft.server.v1_8_R3.NetworkManager.a(NetworkManager.java:231) [spigot.jar:git-Spigot-5f38d38-12698ea]
	at net.minecraft.server.v1_8_R3.ServerConnection.c(ServerConnection.java:148) [spigot.jar:git-Spigot-5f38d38-12698ea]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:814) [spigot.jar:git-Spigot-5f38d38-12698ea]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot.jar:git-Spigot-5f38d38-12698ea]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot.jar:git-Spigot-5f38d38-12698ea]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot.jar:git-Spigot-5f38d38-12698ea]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66]
Caused by: java.lang.NullPointerException
	at de.Keyle.MyPet.listeners.PlayerListener.onMyPetPlayerChangeWorld(PlayerListener.java:262) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor410.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_66]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_66]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-5f38d38-12698ea]
	... 25 more

**Comment by xXKeyleXx** [comment]
I think build 706+ should already fix that

**Comment by xion87** [comment]
okey i will try, thank for the fast reply

**Comment by xXKeyleXx** [comment]
Is it fixed?

**Comment by xion87** [comment]
yep i dont see that error anymore, i think is fixed! thank you!
