### ISSUE TITLE
exp.js bug?

### ISSUE THREAD

**Issue by ExtremoDuro** [xXKeyleXx/MyPet#589]
```
[10:10:14] [Server thread/WARN]: <eval>:20 ReferenceError: "floor" is not defined
[10:10:14] [Server thread/WARN]: 	at jdk.nashorn.internal.runtime.ECMAErrors.error(ECMAErrors.java:57)
[10:10:14] [Server thread/WARN]: 	at jdk.nashorn.internal.runtime.ECMAErrors.referenceError(ECMAErrors.java:319)
[10:10:14] [Server thread/WARN]: 	at jdk.nashorn.internal.runtime.ECMAErrors.referenceError(ECMAErrors.java:291)
[10:10:14] [Server thread/WARN]: 	at jdk.nashorn.internal.objects.Global.__noSuchProperty__(Global.java:1432)
[10:10:14] [Server thread/WARN]: 	at jdk.nashorn.internal.scripts.Script$Recompilation$4$336AA$\^eval\_.getLevel(<eval>:20)
[10:10:14] [Server thread/WARN]: 	at jdk.nashorn.internal.scripts.Script$Recompilation$3$767AA$\^eval\_.getRequiredExp(<eval>:27)
[10:10:14] [Server thread/WARN]: 	at de.Keyle.MyPet.skill.experience.JavaScript$IExperience$$NashornJavaAdapter.getRequiredExp(Unknown Source)
[10:10:14] [Server thread/WARN]: 	at de.Keyle.MyPet.skill.experience.JavaScript.getRequiredExp(JavaScript.java:112)
[10:10:14] [Server thread/WARN]: 	at de.Keyle.MyPet.skill.experience.JavaScript.<init>(JavaScript.java:65)
[10:10:14] [Server thread/WARN]: 	at de.Keyle.MyPet.skill.Experience.<init>(Experience.java:62)
[10:10:14] [Server thread/WARN]: 	at de.Keyle.MyPet.entity.types.MyPet.<init>(MyPet.java:108)
[10:10:14] [Server thread/WARN]: 	at de.Keyle.MyPet.entity.types.chicken.MyChicken.<init>(MyChicken.java:43)
[10:10:14] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[10:10:14] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[10:10:14] [Server thread/WARN]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[10:10:14] [Server thread/WARN]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
[10:10:14] [Server thread/WARN]: 	at de.Keyle.MyPet.entity.types.MyPetType.getNewMyPetInstance(MyPetType.java:201)
[10:10:14] [Server thread/WARN]: 	at de.Keyle.MyPet.entity.types.MyPetList.getMyPetFromInactiveMyPet(MyPetList.java:49)
[10:10:14] [Server thread/WARN]: 	at de.Keyle.MyPet.entity.types.MyPetList.setMyPetActive(MyPetList.java:191)
[10:10:14] [Server thread/WARN]: 	at de.Keyle.MyPet.listeners.PlayerListener.onPlayerJoin(PlayerListener.java:126)
[10:10:14] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[10:10:14] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[10:10:14] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[10:10:14] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[10:10:14] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)
[10:10:14] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[10:10:14] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
[10:10:14] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
[10:10:14] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PlayerList.onPlayerJoin(PlayerList.java:298)
[10:10:14] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PlayerList.a(PlayerList.java:157)
[10:10:14] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.LoginListener.b(LoginListener.java:144)
[10:10:14] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.LoginListener.c(LoginListener.java:54)
[10:10:14] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.NetworkManager.a(NetworkManager.java:231)
[10:10:14] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.ServerConnection.c(ServerConnection.java:148)
[10:10:14] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:814)
[10:10:14] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[10:10:14] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[10:10:14] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[10:10:14] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[10:10:14] [Server thread/INFO]: [[0;32;1mM[0;32;22my[0;32;1mP[0;32;22met[m] [0;31;1mThis error appeared because your Levelscript (exp.js) caused an error.[m
[10:10:14] [Server thread/WARN]: <eval>:20 ReferenceError: "floor" is not defined
[10:10:14] [Server thread/WARN]: 	at jdk.nashorn.internal.runtime.ECMAErrors.error(ECMAErrors.java:57)
[10:10:14] [Server thread/WARN]: 	at jdk.nashorn.internal.runtime.ECMAErrors.referenceError(ECMAErrors.java:319)
[10:10:14] [Server thread/WARN]: 	at jdk.nashorn.internal.runtime.ECMAErrors.referenceError(ECMAErrors.java:291)
[10:10:14] [Server thread/WARN]: 	at jdk.nashorn.internal.objects.Global.__noSuchProperty__(Global.java:1432)
[10:10:14] [Server thread/WARN]: 	at jdk.nashorn.internal.scripts.Script$Recompilation$4$336AA$\^eval\_.getLevel(<eval>:20)
[10:10:14] [Server thread/WARN]: 	at jdk.nashorn.internal.scripts.Script$Recompilation$1$987AA$\^eval\_.getCurrentExp(<eval>:37)
[10:10:14] [Server thread/WARN]: 	at de.Keyle.MyPet.skill.experience.JavaScript$IExperience$$NashornJavaAdapter.getCurrentExp(Unknown Source)
[10:10:14] [Server thread/WARN]: 	at de.Keyle.MyPet.skill.experience.JavaScript.getCurrentExp(JavaScript.java:141)
[10:10:14] [Server thread/WARN]: 	at de.Keyle.MyPet.skill.experience.JavaScript.<init>(JavaScript.java:66)
[10:10:14] [Server thread/WARN]: 	at de.Keyle.MyPet.skill.Experience.<init>(Experience.java:62)
[10:10:14] [Server thread/WARN]: 	at de.Keyle.MyPet.entity.types.MyPet.<init>(MyPet.java:108)
[10:10:14] [Server thread/WARN]: 	at de.Keyle.MyPet.entity.types.chicken.MyChicken.<init>(MyChicken.java:43)
[10:10:14] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[10:10:14] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[10:10:14] [Server thread/WARN]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[10:10:14] [Server thread/WARN]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
[10:10:14] [Server thread/WARN]: 	at de.Keyle.MyPet.entity.types.MyPetType.getNewMyPetInstance(MyPetType.java:201)
[10:10:14] [Server thread/WARN]: 	at de.Keyle.MyPet.entity.types.MyPetList.getMyPetFromInactiveMyPet(MyPetList.java:49)
[10:10:14] [Server thread/WARN]: 	at de.Keyle.MyPet.entity.types.MyPetList.setMyPetActive(MyPetList.java:191)
[10:10:14] [Server thread/WARN]: 	at de.Keyle.MyPet.listeners.PlayerListener.onPlayerJoin(PlayerListener.java:126)
[10:10:14] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[10:10:14] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[10:10:14] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[10:10:14] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[10:10:14] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)
[10:10:14] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[10:10:14] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
[10:10:14] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
[10:10:14] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PlayerList.onPlayerJoin(PlayerList.java:298)
[10:10:14] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PlayerList.a(PlayerList.java:157)
[10:10:14] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.LoginListener.b(LoginListener.java:144)
[10:10:14] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.LoginListener.c(LoginListener.java:54)
[10:10:14] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.NetworkManager.a(NetworkManager.java:231)
[10:10:14] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.ServerConnection.c(ServerConnection.java:148)
[10:10:14] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:814)
[10:10:14] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[10:10:14] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[10:10:14] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[10:10:14] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[10:10:14] [Server thread/INFO]: [[0;32;1mM[0;32;22my[0;32;1mP[0;32;22met[m] [0;31;1mThis error appeared because your Levelscript (exp.js) caused an error.[m
[10:10:14] [Server thread/WARN]: <eval>:48 TypeError: [Number 1.0] is not a function
[10:10:14] [Server thread/WARN]: 	at jdk.nashorn.internal.runtime.ECMAErrors.error(ECMAErrors.java:57)
[10:10:14] [Server thread/WARN]: 	at jdk.nashorn.internal.runtime.ECMAErrors.typeError(ECMAErrors.java:213)
[10:10:14] [Server thread/WARN]: 	at jdk.nashorn.internal.runtime.ECMAErrors.typeError(ECMAErrors.java:185)
[10:10:14] [Server thread/WARN]: 	at jdk.nashorn.internal.runtime.ECMAErrors.typeError(ECMAErrors.java:172)
[10:10:14] [Server thread/WARN]: 	at jdk.nashorn.internal.runtime.ScriptObject.notAFunction(ScriptObject.java:1869)
[10:10:14] [Server thread/WARN]: 	at jdk.nashorn.internal.runtime.ScriptObject.findCallMethod(ScriptObject.java:1865)
[10:10:14] [Server thread/WARN]: 	at jdk.nashorn.internal.runtime.ScriptObject.lookup(ScriptObject.java:1833)
[10:10:14] [Server thread/WARN]: 	at jdk.nashorn.internal.runtime.linker.PrimitiveLookup.lookupPrimitive(PrimitiveLookup.java:155)
[10:10:14] [Server thread/WARN]: 	at jdk.nashorn.internal.runtime.linker.PrimitiveLookup.lookupPrimitive(PrimitiveLookup.java:80)
[10:10:14] [Server thread/WARN]: 	at jdk.nashorn.internal.objects.NativeNumber.lookupPrimitive(NativeNumber.java:323)
[10:10:14] [Server thread/WARN]: 	at jdk.nashorn.internal.objects.Global.primitiveLookup(Global.java:1127)
[10:10:14] [Server thread/WARN]: 	at jdk.nashorn.internal.runtime.linker.NashornPrimitiveLinker.getGuardedInvocation(NashornPrimitiveLinker.java:71)
[10:10:14] [Server thread/WARN]: 	at jdk.internal.dynalink.support.CompositeTypeBasedGuardingDynamicLinker.getGuardedInvocation(CompositeTypeBasedGuardingDynamicLinker.java:176)
[10:10:14] [Server thread/WARN]: 	at jdk.internal.dynalink.support.CompositeGuardingDynamicLinker.getGuardedInvocation(CompositeGuardingDynamicLinker.java:124)
[10:10:14] [Server thread/WARN]: 	at jdk.internal.dynalink.support.LinkerServicesImpl.getGuardedInvocation(LinkerServicesImpl.java:154)
[10:10:14] [Server thread/WARN]: 	at jdk.internal.dynalink.DynamicLinker.relink(DynamicLinker.java:253)
[10:10:14] [Server thread/WARN]: 	at jdk.nashorn.internal.scripts.Script$Recompilation$2$1371AA$\^eval\_.getExpByLevel(<eval>:48)
[10:10:14] [Server thread/WARN]: 	at de.Keyle.MyPet.skill.experience.JavaScript$IExperience$$NashornJavaAdapter.getExpByLevel(Unknown Source)
[10:10:14] [Server thread/WARN]: 	at de.Keyle.MyPet.skill.experience.JavaScript.getExpByLevel(JavaScript.java:168)
[10:10:14] [Server thread/WARN]: 	at de.Keyle.MyPet.skill.experience.JavaScript.<init>(JavaScript.java:67)
[10:10:14] [Server thread/WARN]: 	at de.Keyle.MyPet.skill.Experience.<init>(Experience.java:62)
[10:10:14] [Server thread/WARN]: 	at de.Keyle.MyPet.entity.types.MyPet.<init>(MyPet.java:108)
[10:10:14] [Server thread/WARN]: 	at de.Keyle.MyPet.entity.types.chicken.MyChicken.<init>(MyChicken.java:43)
[10:10:14] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[10:10:14] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[10:10:14] [Server thread/WARN]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[10:10:14] [Server thread/WARN]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
[10:10:14] [Server thread/WARN]: 	at de.Keyle.MyPet.entity.types.MyPetType.getNewMyPetInstance(MyPetType.java:201)
[10:10:14] [Server thread/WARN]: 	at de.Keyle.MyPet.entity.types.MyPetList.getMyPetFromInactiveMyPet(MyPetList.java:49)
[10:10:14] [Server thread/WARN]: 	at de.Keyle.MyPet.entity.types.MyPetList.setMyPetActive(MyPetList.java:191)
[10:10:14] [Server thread/WARN]: 	at de.Keyle.MyPet.listeners.PlayerListener.onPlayerJoin(PlayerListener.java:126)
[10:10:14] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[10:10:14] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[10:10:14] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[10:10:14] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[10:10:14] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)
[10:10:14] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[10:10:14] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
[10:10:14] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
[10:10:14] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PlayerList.onPlayerJoin(PlayerList.java:298)
[10:10:14] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PlayerList.a(PlayerList.java:157)
[10:10:14] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.LoginListener.b(LoginListener.java:144)
[10:10:14] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.LoginListener.c(LoginListener.java:54)
[10:10:14] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.NetworkManager.a(NetworkManager.java:231)
[10:10:14] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.ServerConnection.c(ServerConnection.java:148)
[10:10:14] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:814)
[10:10:14] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[10:10:14] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[10:10:14] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[10:10:14] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
```

**Comment by xXKeyleXx** [comment]
What Java do you use? And please use a service like pastebin or gist to show me your errorlogs.

**Comment by Extreme21** [comment]
OpenJDK 8. I will, thanks ^^

**Comment by xXKeyleXx** [comment]
Yeah..... that's what I thought....the OpenJDK uses a different JS engine than the Oracle one.... I need to find a better solution for that...

**Comment by xXKeyleXx** [comment]
The latest build uses an external library so any JDK should work now.
