### ISSUE TITLE
Can you change the MyPetPlayer class?

### ISSUE THREAD

**Issue by FabioZumbi12** [xXKeyleXx/MyPet#612]
My plugin supports all versions of minecraft, including 1.7.10. With the change of way we get the MyPetPlayer, i cant import "de.Keyle.MyPet.util.player.MyPetPlayer" for both versions to check and the property methos to get the player.

This is my code:

```
MyPetPlayer mpp = null;
            	if (Bukkit.getPluginManager().getPlugin("MyPet").getDescription().getVersion().contains("1.2.4")){
            		mpp = PlayerList.getMyPetPlayer(p.getName());  
            	} else {
            		mpp = MyPetPlayer.getMyPetPlayer(p.getName()); 
            	}
```
But i cant compile because the new "MyPetPlayer" dont have "getMyPetPlayer(player)". I cant import both versions too because the class "MyPetPlayer" dont changed.

...or add this method again on MyPetPlayer only for compatibility access.

Is this possible? Thanks.

**Comment by xXKeyleXx** [comment]
Sorry, didn't know that anyone even added MyPet support :/

I will move the MyPetPlayer class to another package in the next SNAPSHOT but this will not change the compatibility problems with 1.2.4.

Why do you need the MyPetPlayer? Can you find the player using a MyPet?

**Comment by FabioZumbi12** [comment]
I use to check if a player have Pet and deny the pet on a region based on a flag. This the code:

```
            //Mypet Flag
            if (RedProtect.MyPet && !region.canPet(player)){
            	MyPetPlayer mpp = PlayerList.getMyPetPlayer(player.getName());            	         	
            	if (mpp != null && mpp.hasMyPet() && mpp.getMyPet().getStatus() != null){
                	if (mpp.getMyPet().getStatus().equals(PetState.Here)){
                		mpp.getMyPet().setStatus(PetState.Despawned);
                		RPLang.sendMessage(player, "playerlistener.region.cantpet");	
                	}  
            	}        	      			
            }
```

**Comment by xXKeyleXx** [comment]
Could you link me the class please.

**Comment by xXKeyleXx** [comment]
You could do it by using reflection, even tho it's not the best way but maybe the only way to support 1.2.4.
In 1.2.5 the classed is located in the api package.

BTW it's will be better to write:
`mpp.getMyPet().remove(true);`
instead of
`mpp.getMyPet().setStatus(PetState.Despawned);`
This way the plugin will know that the pet's has unwillingly been sent away

**Comment by FabioZumbi12** [comment]
Using version 1.2.6 i think done with mutiversions. See the code:

```
//Mypet Flag
            if (RedProtect.MyPet && !r.canPet(p)){
                if (Integer.parseInt(Bukkit.getPluginManager().getPlugin("MyPet").getDescription().getVersion().replace(".", "")) <= 124){
                	de.Keyle.MyPet.util.player.MyPetPlayer mpp = de.Keyle.MyPet.util.player.MyPetPlayer.getMyPetPlayer(p.getName()); 
                	if (mpp != null && mpp.hasMyPet() && mpp.getMyPet().getStatus() != null){
                    	if (mpp.getMyPet().getStatus().equals(PetState.Here)){
                    		mpp.getMyPet().removePet();
                    		RPLang.sendMessage(p, "playerlistener.region.cantpet");	
                    	}  
                	}                	
                } else {
                	MyPetPlayer mpp = PlayerList.getMyPetPlayer(p.getName());  
                	if (mpp != null && mpp.hasMyPet() && mpp.getMyPet().getStatus() != null){
                    	if (mpp.getMyPet().getStatus().equals(PetState.Here)){
                    		mpp.getMyPet().removePet();
                    		RPLang.sendMessage(p, "playerlistener.region.cantpet");	
                    	}  
                	}
                }            	        	      			
        	}
```
And using ".removePet()" will not release the pet right? Only despawn? And why the option to use with boolean (`.removePet(boolean)`)?

**Comment by xXKeyleXx** [comment]
Looks fine. Using remove pet does the same as setStatus(Despawned) and the option with the boolean will tell the plugin whether the pet wants to respawn (on next player join, teleport, world change, etc)

**Comment by FabioZumbi12** [comment]
Thank you for the help! ^^

**Comment by FabioZumbi12** [comment]
Hello, now testing with 1.2.7 seens the code is droping null point like this error:

```
[23:12:25 WARN]: [RedProtect] Task #250386 for RedProtect v6.4.3 generated an exception
java.lang.NullPointerException        at de.Keyle.MyPet.repository.PlayerList.getInternalUUID(PlayerList.java:49) ~[?:?]        at de.Keyle.MyPet.repository.PlayerList.getMyPetPlayer(PlayerList.java:64) ~[?:?]        at de.Keyle.MyPet.repository.PlayerList.getMyPetPlayer(PlayerList.java:73) ~[?:?]        at br.net.fabiozumbi12.RedProtect.listeners.RPPlayerListener.RegionFlags(RPPlayerListener.java:1102) ~[?:?]        at br.net.fabiozumbi12.RedProtect.listeners.RPPlayerListener.access$000(RPPlayerListener.java:85) ~[?:?]        at br.net.fabiozumbi12.RedProtect.listeners.RPPlayerListener$1.run(RPPlayerListener.java:582) ~[?:?]        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]
```

This is the lines of my code: 

```
import de.Keyle.MyPet.api.entity.MyPetEntity;
import de.Keyle.MyPet.api.player.MyPetPlayer;
import de.Keyle.MyPet.entity.types.MyPet.PetState;
import de.Keyle.MyPet.repository.PlayerList;
...
MyPetPlayer mpp = PlayerList.getMyPetPlayer(p.getName()); 
```

**Comment by xXKeyleXx** [comment]
do you check for MyPetPlayers with PlayerList.isMyPetPlayer(p) ?

**Comment by FabioZumbi12** [comment]
Humm, i will try!

**Comment by FabioZumbi12** [comment]
I think worked, no erros and pet go away when enter the region without respawn on relogin ^^

But i will try on my public server now.

Thanks to fast response :)
