### ISSUE TITLE
Could not pass event MyPetLevelUpEvent to MyPet v1.2.8

### ISSUE THREAD

**Issue by PinoyLifeCraft** [xXKeyleXx/MyPet#629]
[20:38:40 ERROR]: Could not pass event MyPetLevelUpEvent to MyPet v1.2.8
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.ja
va:310) ~[craftbukkit.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.jav
a:62) ~[craftbukkit.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.j
ava:502) [craftbukkit.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.j
ava:487) [craftbukkit.jar:git-Spigot-db6de12-18fbb24]
        at de.Keyle.MyPet.skill.Experience.addExp(Experience.java:144) [MyPet-1.
2.8-SNAPSHOT.jar:?]
        at de.Keyle.MyPet.listeners.EntityListener.onEntityDeath(EntityListener.
java:872) [MyPet-1.2.8-SNAPSHOT.jar:?]
        at sun.reflect.GeneratedMethodAccessor375.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1
.8.0_66]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_66]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.ja
va:306) [craftbukkit.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.jav
a:62) [craftbukkit.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.j
ava:502) [craftbukkit.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.j
ava:487) [craftbukkit.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callEntityDeat
hEvent(CraftEventFactory.java:378) [craftbukkit.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.EntityLiving.die(EntityLiving.java:874)
[craftbukkit.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.EntityZombie.die(EntityZombie.java:561)
[craftbukkit.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.EntityLiving.damageEntity(EntityLiving.j
ava:812) [craftbukkit.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.EntityMonster.damageEntity(EntityMonster
.java:42) [craftbukkit.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.EntityZombie.damageEntity(EntityZombie.j
ava:167) [craftbukkit.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.EntityPigZombie.damageEntity(SourceFile:
143) [craftbukkit.jar:git-Spigot-db6de12-18fbb24]
        at de.Keyle.MyPet.entity.types.EntityMyPet.attack(EntityMyPet.java:293)
[MyPet-1.2.8-SNAPSHOT.jar:?]
        at de.Keyle.MyPet.entity.ai.attack.MeleeAttack.tick(MeleeAttack.java:112
) [MyPet-1.2.8-SNAPSHOT.jar:?]
        at de.Keyle.MyPet.entity.ai.AIGoalSelector.tick(AIGoalSelector.java:118)
 [MyPet-1.2.8-SNAPSHOT.jar:?]
        at de.Keyle.MyPet.entity.types.EntityMyPet.doMyPetTick(EntityMyPet.java:
737) [MyPet-1.2.8-SNAPSHOT.jar:?]
        at de.Keyle.MyPet.entity.types.EntityMyPet.m(EntityMyPet.java:685) [MyPe
t-1.2.8-SNAPSHOT.jar:?]
        at net.minecraft.server.v1_8_R3.EntityLiving.t_(EntityLiving.java:1487)
[craftbukkit.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.EntityInsentient.t_(EntityInsentient.jav
a:193) [craftbukkit.jar:git-Spigot-db6de12-18fbb24]
        at de.Keyle.MyPet.entity.types.EntityMyPet.t_(EntityMyPet.java:811) [MyP
et-1.2.8-SNAPSHOT.jar:?]
        at net.minecraft.server.v1_8_R3.World.entityJoinedWorld(World.java:1607)
 [craftbukkit.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.World.g(World.java:1582) [craftbukkit.ja
r:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.World.tickEntities(World.java:1425) [cra
ftbukkit.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.WorldServer.tickEntities(WorldServer.jav
a:597) [craftbukkit.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:7
86) [craftbukkit.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:3
74) [craftbukkit.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:6
54) [craftbukkit.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java
:557) [craftbukkit.jar:git-Spigot-db6de12-18fbb24]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_66]
Caused by: java.lang.NullPointerException
        at de.Keyle.MyPet.skill.skills.implementation.Control.upgrade(Control.ja
va:59) ~[?:?]
        at de.Keyle.MyPet.listeners.LevelUpListener.onLevelUp(LevelUpListener.ja
va:76) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0
_66]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0
_66]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1
.8.0_66]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_66]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.ja
va:306) ~[craftbukkit.jar:git-Spigot-db6de12-18fbb24]
        ... 36 more

**Comment by xXKeyleXx** [comment]
What control item have you set in the config?

**Comment by PinoyLifeCraft** [comment]
Wait what do you mean? i can't find it in config.yml :disappointed:

**Comment by xXKeyleXx** [comment]
Sill.Control.Item

**Comment by PinoyLifeCraft** [comment]
What? Do you mean Skill Control Item?

  Skill:
    Control:
      Item: 0
    Ride:
      Item: 0

**Comment by xXKeyleXx** [comment]
I see. Thanks, will fix that later on today.
