### ISSUE TITLE
MyPet Premium 1.2.7 error (null)

### ISSUE THREAD

**Issue by andris155** [xXKeyleXx/MyPet#643]
[13:06:08] [Server thread/INFO]: kockafej930 issued server command: /pc
[13:06:08] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'pc' in plugin MyPet v1.2.7
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[spigot_1.8.jar:git-PaperSpigot-83b7006-039621d]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:143) ~[spigot_1.8.jar:git-PaperSpigot-83b7006-039621d]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:666) ~[spigot_1.8.jar:git-PaperSpigot-83b7006-039621d]
	at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1189) [spigot_1.8.jar:git-PaperSpigot-83b7006-039621d]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1001) [spigot_1.8.jar:git-PaperSpigot-83b7006-039621d]
	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot_1.8.jar:git-PaperSpigot-83b7006-039621d]
	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot_1.8.jar:git-PaperSpigot-83b7006-039621d]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot_1.8.jar:git-PaperSpigot-83b7006-039621d]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_51]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_51]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot_1.8.jar:git-PaperSpigot-83b7006-039621d]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:773) [spigot_1.8.jar:git-PaperSpigot-83b7006-039621d]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [spigot_1.8.jar:git-PaperSpigot-83b7006-039621d]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [spigot_1.8.jar:git-PaperSpigot-83b7006-039621d]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [spigot_1.8.jar:git-PaperSpigot-83b7006-039621d]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_51]
Caused by: java.lang.IllegalArgumentException: Illegal group reference
	at java.util.regex.Matcher.appendReplacement(Unknown Source) ~[?:1.8.0_51]
	at java.util.regex.Matcher.replaceAll(Unknown Source) ~[?:1.8.0_51]
	at java.lang.String.replaceAll(Unknown Source) ~[?:1.8.0_51]
	at de.Keyle.MyPet.util.Util.formatText(Util.java:120) ~[?:?]
	at de.Keyle.MyPet.commands.CommandCall.onCommand(CommandCall.java:46) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[spigot_1.8.jar:git-PaperSpigot-83b7006-039621d]
	... 15 more

**Comment by xXKeyleXx** [comment]
Did this happened more than once?

**Comment by andris155** [comment]
no

**Comment by xXKeyleXx** [comment]
I'm not sure what this happened because in theory this can not happen at all :P
So as long as this doesn't happen again I will mark this as error caused by an unfortunate event.
