### ISSUE TITLE
MyPet + Ultimate SurvivalGames error

### ISSUE THREAD

**Issue by andris155** [xXKeyleXx/MyPet#649]
[14:33:01] [Server thread/ERROR]: Could not pass event InventoryClickEvent to SurvivalGames vBeta dev1.9.4b
org.bukkit.event.EventException
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot_1.8.jar:git-PaperSpigot-4c925a4-3f3c65f]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[spigot_1.8.jar:git-PaperSpigot-4c925a4-3f3c65f]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot_1.8.jar:git-PaperSpigot-4c925a4-3f3c65f]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [spigot_1.8.jar:git-PaperSpigot-4c925a4-3f3c65f]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) [spigot_1.8.jar:git-PaperSpigot-4c925a4-3f3c65f]
at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1657) [spigot_1.8.jar:git-PaperSpigot-4c925a4-3f3c65f]
at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:31) [spigot_1.8.jar:git-PaperSpigot-4c925a4-3f3c65f]
at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:9) [spigot_1.8.jar:git-PaperSpigot-4c925a4-3f3c65f]
at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot_1.8.jar:git-PaperSpigot-4c925a4-3f3c65f]
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_51]
at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_51]
at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot_1.8.jar:git-PaperSpigot-4c925a4-3f3c65f]
at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:773) [spigot_1.8.jar:git-PaperSpigot-4c925a4-3f3c65f]
at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [spigot_1.8.jar:git-PaperSpigot-4c925a4-3f3c65f]
at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [spigot_1.8.jar:git-PaperSpigot-4c925a4-3f3c65f]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [spigot_1.8.jar:git-PaperSpigot-4c925a4-3f3c65f]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_51]
Caused by: java.lang.IndexOutOfBoundsException: Index: 54, Size: 54
at java.util.ArrayList.rangeCheck(Unknown Source) ~[?:1.8.0_51]
at java.util.ArrayList.get(Unknown Source) ~[?:1.8.0_51]
**at de.Keyle.MyPet.skill.skills.implementation.inventory.CustomInventory.getItem(CustomInventory.java:78) ~[?:?]**
at org.bukkit.craftbukkit.v1_8_R3.inventory.CraftInventory.getItem(CraftInventory.java:47) ~[spigot_1.8.jar:git-PaperSpigot-4c925a4-3f3c65f]
**at me.maker56.survivalgames.listener.PlayerListener.onInventoryClickEvent(PlayerListener.java:70) ~[?:?]**
at sun.reflect.GeneratedMethodAccessor214.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_51]
at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_51]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[spigot_1.8.jar:git-PaperSpigot-4c925a4-3f3c65f]
... 16 more

**Comment by xXKeyleXx** [comment]
This is a problem originates from your SurvivalGames plugin not MyPet.

**Comment by andris155** [comment]
How to fix? :/

**Comment by xXKeyleXx** [comment]
I did a quick fix that should prevent that error. even tho USG shouldn't cause it in the first place...

**Comment by andris155** [comment]
Thanks!
xXKeyleXx the best developer!

**Comment by xXKeyleXx** [comment]
The only thing is that I don't know when I will release the next MyPet-Premium version because I want to add some thing I haven't finished yet :/
