### ISSUE TITLE
Console Error Code

### ISSUE THREAD

**Issue by djlawrence4** [xXKeyleXx/MyPet#675]
When it happend: Ironically I punched an NPC from Citizens2 with Sentry trait and it popped an error code

Console Output:

Could not pass event EntityDamageByEntityEvent to MyPet v1.3.2
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.9.jar:git-Spigot-3af4605-8447e4f]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.9.jar:git-Spigot-3af4605-8447e4f]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.9.jar:git-Spigot-3af4605-8447e4f]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.9.jar:git-Spigot-3af4605-8447e4f]
        at org.bukkit.craftbukkit.v1_9_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:87) [spigot-1.9.jar:git-Spigot-3af4605-8447e4f]
        at org.bukkit.craftbukkit.v1_9_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:556) [spigot-1.9.jar:git-Spigot-3af4605-8447e4f]
        at org.bukkit.craftbukkit.v1_9_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:465) [spigot-1.9.jar:git-Spigot-3af4605-8447e4f]
        at org.bukkit.craftbukkit.v1_9_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:588) [spigot-1.9.jar:git-Spigot-3af4605-8447e4f]
        at net.minecraft.server.v1_9_R1.EntityLiving.damageEntity0(EntityLiving.java:1206) [spigot-1.9.jar:git-Spigot-3af4605-8447e4f]
        at net.minecraft.server.v1_9_R1.EntityHuman.damageEntity0(EntityHuman.java:838) [spigot-1.9.jar:git-Spigot-3af4605-8447e4f]
        at net.minecraft.server.v1_9_R1.EntityLiving.damageEntity(EntityLiving.java:814) [spigot-1.9.jar:git-Spigot-3af4605-8447e4f]
        at net.minecraft.server.v1_9_R1.EntityHuman.damageEntity(EntityHuman.java:762) [spigot-1.9.jar:git-Spigot-3af4605-8447e4f]
        at net.minecraft.server.v1_9_R1.EntityPlayer.damageEntity(EntityPlayer.java:513) [spigot-1.9.jar:git-Spigot-3af4605-8447e4f]
        at net.citizensnpcs.npc.entity.EntityHumanNPC.damageEntity(EntityHumanNPC.java:120) [citizens-2.0.17-SNAPSHOT.jar:?]
        at net.minecraft.server.v1_9_R1.EntityHuman.attack(EntityHuman.java:999) [spigot-1.9.jar:git-Spigot-3af4605-8447e4f]
        at net.minecraft.server.v1_9_R1.EntityPlayer.attack(EntityPlayer.java:1141) [spigot-1.9.jar:git-Spigot-3af4605-8447e4f]
        at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:1529) [spigot-1.9.jar:git-Spigot-3af4605-8447e4f]
        at de.robingrether.idisguise.management.impl.v1_9_R1.ChannelRegisterImpl$PlayerConnectionInjected.a(ChannelRegisterImpl.java:159) [iDisguise-5.1.1.jar:?]
        at net.minecraft.server.v1_9_R1.PacketPlayInUseEntity.a(SourceFile:68) [spigot-1.9.jar:git-Spigot-3af4605-8447e4f]
        at net.minecraft.server.v1_9_R1.PacketPlayInUseEntity.a(SourceFile:12) [spigot-1.9.jar:git-Spigot-3af4605-8447e4f]
        at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.9.jar:git-Spigot-3af4605-8447e4f]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_72]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_72]
        at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [spigot-1.9.jar:git-Spigot-3af4605-8447e4f]
        at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:721) [spigot-1.9.jar:git-Spigot-3af4605-8447e4f]
        at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-1.9.jar:git-Spigot-3af4605-8447e4f]
        at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [spigot-1.9.jar:git-Spigot-3af4605-8447e4f]
        at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot-1.9.jar:git-Spigot-3af4605-8447e4f]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]
Caused by: java.lang.NullPointerException
        at de.Keyle.MyPet.listeners.EntityListener.onEntityDamageByPlayer(EntityListener.java:284) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_72]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_72]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_72]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_72]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.9.jar:git-Spigot-3af4605-8447e4f]
        ... 28 more

[MyPetlog.txt](https://github.com/xXKeyleXx/MyPet/files/156141/MyPetlog.txt)

**Comment by xXKeyleXx** [comment]
duplicate to #670
