### ISSUE TITLE
EntityDeathEvent

### ISSUE THREAD

**Issue by Phreag** [xXKeyleXx/MyPet#682]
[15:39:21 ERROR]: Could not pass event EntityDeathEvent to MyPet v1.3.2
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot.jar
:git-Paper-448]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[spigot.jar:git-
Paper-448]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:g
it-Paper-448]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [spigot.jar
:git-Paper-448]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [spigot.jar
:git-Paper-448]
        at org.bukkit.craftbukkit.v1_9_R1.event.CraftEventFactory.callEntityDeathEvent(CraftEventFac
tory.java:378) [spigot.jar:git-Paper-448]
        at net.minecraft.server.v1_9_R1.EntityLiving.die(EntityLiving.java:978) [spigot.jar:git-Pape
r-448]
        at net.minecraft.server.v1_9_R1.EntityLiving.damageEntity(EntityLiving.java:894) [spigot.jar
:git-Paper-448]
        at de.Keyle.MyPet.compat.v1_9_R1.entity.EntityMyPet.attack(EntityMyPet.java:343) [MyPet-Prem
ium-1.3.2-SNAPSHOT.jar:?]
        at de.Keyle.MyPet.compat.v1_9_R1.entity.ai.attack.MeleeAttack.tick(MeleeAttack.java:113) [My
Pet-Premium-1.3.2-SNAPSHOT.jar:?]
        at de.Keyle.MyPet.api.entity.ai.AIGoalSelector.tick(AIGoalSelector.java:125) [MyPet-Premium-
1.3.2-SNAPSHOT.jar:?]
        at de.Keyle.MyPet.compat.v1_9_R1.entity.EntityMyPet.doMyPetTick(EntityMyPet.java:955) [MyPet
-Premium-1.3.2-SNAPSHOT.jar:?]
        at de.Keyle.MyPet.compat.v1_9_R1.entity.EntityMyPet.n(EntityMyPet.java:900) [MyPet-Premium-1
.3.2-SNAPSHOT.jar:?]
        at net.minecraft.server.v1_9_R1.EntityLiving.m(EntityLiving.java:1761) [spigot.jar:git-Paper
-448]
        at net.minecraft.server.v1_9_R1.EntityInsentient.m(EntityInsentient.java:244) [spigot.jar:gi
t-Paper-448]
        at de.Keyle.MyPet.compat.v1_9_R1.entity.EntityMyPet.m(EntityMyPet.java:1077) [MyPet-Premium-
1.3.2-SNAPSHOT.jar:?]
        at net.minecraft.server.v1_9_R1.World.entityJoinedWorld(World.java:1610) [spigot.jar:git-Pap
er-448]
        at net.minecraft.server.v1_9_R1.World.g(World.java:1585) [spigot.jar:git-Paper-448]
        at net.minecraft.server.v1_9_R1.World.tickEntities(World.java:1415) [spigot.jar:git-Paper-44
8]
        at net.minecraft.server.v1_9_R1.WorldServer.tickEntities(WorldServer.java:630) [spigot.jar:g
it-Paper-448]
        at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:847) [spigot.jar:git-
Paper-448]
        at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:404) [spigot.jar:git-
Paper-448]
        at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:714) [spigot.jar:git-
Paper-448]
        at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:613) [spigot.jar:gi
t-Paper-448]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_71]
Caused by: java.lang.NullPointerException
        at de.Keyle.MyPet.listeners.EntityListener.onMyPetEntityDeath(EntityListener.java:793) ~[?:?
]
        at sun.reflect.GeneratedMethodAccessor291.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?
:1.8.0_71]
        at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_71]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[spigot.jar
:git-Paper-448]
        ... 24 more

**Comment by xXKeyleXx** [comment]
Can't reproduce that error :/

**Comment by xXKeyleXx** [comment]
duplicate to #713
