### ISSUE TITLE
MySQL prolems

### ISSUE THREAD

**Issue by plasmavngaming** [xXKeyleXx/MyPet#686]
I config the MySQL and start the Server then i check the mysql it does not have a Table about MyPet
Sorry for my English Error :P
  Repository:
    Type: MySQL
    ConvertFrom: ''
    NBT:
      AutoSaveTime: 60
      Pet:
        SaveOnAdd: true
        SaveOnUpdate: true
        SaveOnRemove: true
      Player:
        SaveOnAdd: true
        SaveOnUpdate: true
        SaveOnRemove: true
      Backup:
        Active: true
        SaveInterval: 1440
        DateFormat: yyyy_MM_dd_HH.mm
    MySQL:
      Database: waf2_main
      TablePrefix: ''
      Host: localhost
      Password: khoinghi@
      User: khoinghi
      Port: 3306
    MongoDB:
      Database: mypet
      CollectionPrefix: ''
      Host: localhost
      Password: ''
      User: ''
      Port: 27017

**Comment by xXKeyleXx** [comment]
Anything in the logs?

**Comment by plasmavngaming** [comment]
Nah! Just have this:
03-05-2016 21:54 [INFO] [MyPet] Compat mode for v1_8_R3 loaded.
03-05-2016 21:54 [INFO] [MyPet] ProtocolLib hook activated.
03-05-2016 21:54 [INFO] [MyPet] --- Loading WorldGroups ---------------------------
03-05-2016 21:54 [INFO] [MyPet]    added 'world' to 'default'
03-05-2016 21:54 [INFO] [MyPet]    added 'world_nether' to 'default'
03-05-2016 21:54 [INFO] [MyPet]    added 'world_the_end' to 'default'
03-05-2016 21:54 [INFO] [MyPet]    added 'spawn' to 'default'
03-05-2016 21:54 [INFO] [MyPet]    added 'map' to 'default'
03-05-2016 21:54 [INFO] [MyPet]  registered 'default' group
03-05-2016 21:54 [INFO] [MyPet] -------------------------------------------------
03-05-2016 21:54 [INFO] [MyPet] Thank you for buying MyPet-Premium!
03-05-2016 21:54 [INFO] [MyPet] version 1.3.2-SNAPSHOT-b142P ENABLED
03-06-2016 09:19 [INFO] [MyPet] Disabling MyPet v1.3.2
03-06-2016 09:41 [INFO] [MyPet] Compat mode for v1_8_R3 loaded.
03-06-2016 09:41 [INFO] [MyPet] ProtocolLib hook activated.
03-06-2016 09:41 [INFO] [MyPet] --- Loading WorldGroups ---------------------------
03-06-2016 09:41 [INFO] [MyPet]    added 'world' to 'default'
03-06-2016 09:41 [INFO] [MyPet]    added 'world_nether' to 'default'
03-06-2016 09:41 [INFO] [MyPet]    added 'world_the_end' to 'default'
03-06-2016 09:41 [INFO] [MyPet]    added 'spawn' to 'default'
03-06-2016 09:41 [INFO] [MyPet]    added 'map' to 'default'
03-06-2016 09:41 [INFO] [MyPet]  registered 'default' group
03-06-2016 09:41 [INFO] [MyPet] -------------------------------------------------
03-06-2016 09:41 [INFO] [MyPet] Thank you for buying MyPet-Premium!
03-06-2016 09:41 [INFO] [MyPet] version 1.3.2-SNAPSHOT-b142P ENABLED
03-06-2016 09:42 [INFO] [MyPet] Disabling MyPet v1.3.2

**Comment by plasmavngaming** [comment]
Hey ==! I was check agian and has it:
[15:13:21] [Craft Scheduler Thread - 24/WARN]: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'waf2_mypet.pet_players' doesn't exist
[15:13:21] [Craft Scheduler Thread - 24/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[15:13:21] [Craft Scheduler Thread - 24/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[15:13:21] [Craft Scheduler Thread - 24/WARN]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[15:13:21] [Craft Scheduler Thread - 24/WARN]: 	at java.lang.reflect.Constructor.newInstance(Unknown Source)
[15:13:21] [Craft Scheduler Thread - 24/WARN]: 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
[15:13:21] [Craft Scheduler Thread - 24/WARN]: 	at com.mysql.jdbc.Util.getInstance(Util.java:382)
[15:13:21] [Craft Scheduler Thread - 24/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1052)
[15:13:21] [Craft Scheduler Thread - 24/WARN]: 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3593)
[15:13:21] [Craft Scheduler Thread - 24/WARN]: 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3525)
[15:13:21] [Craft Scheduler Thread - 24/WARN]: 	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1986)
[15:13:21] [Craft Scheduler Thread - 24/WARN]: 	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2140)
[15:13:21] [Craft Scheduler Thread - 24/WARN]: 	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2626)
[15:13:21] [Craft Scheduler Thread - 24/WARN]: 	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2111)
[15:13:21] [Craft Scheduler Thread - 24/WARN]: 	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:2273)
[15:13:21] [Craft Scheduler Thread - 24/WARN]: 	at de.Keyle.MyPet.repository.types.MySqlRepository$12.run(MySqlRepository.java:905)
[15:13:21] [Craft Scheduler Thread - 24/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
[15:13:21] [Craft Scheduler Thread - 24/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[15:13:21] [Craft Scheduler Thread - 24/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[15:13:21] [Craft Scheduler Thread - 24/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[15:13:21] [Craft Scheduler Thread - 24/WARN]: 	at java.lang.Thread.run(Unknown Source)
