### ISSUE TITLE
[MyPet] Unhandled exception occured in onPacketSending(PacketEvent) for MyPet

### ISSUE THREAD

**Issue by Rocologo** [xXKeyleXx/MyPet#687]
While testing MobHunting with a new version of MyPet (1.3.2-SNAPSHOT) and Protocollib for 1.9 

I got this error when my player joins the server, MyPet immediately throws this error:

`[12:46:33] [Server thread/ERROR]: [MyPet] Unhandled exception occured in onPacketSending(PacketEvent) for MyPet
java.lang.RuntimeException: Cannot retrieve entity from ID.
	at com.comphenix.protocol.wrappers.BukkitConverters$13.getSpecificValue(BukkitConverters.java:700) ~[ProtocolLib-B244.jar:3.7-SNAPSHOT-b244]
	at com.comphenix.protocol.wrappers.BukkitConverters$13.getSpecificValue(BukkitConverters.java:679) ~[ProtocolLib-B244.jar:3.7-SNAPSHOT-b244]
	at com.comphenix.protocol.wrappers.BukkitConverters$IgnoreNullConverter.getSpecific(BukkitConverters.java:147) ~[ProtocolLib-B244.jar:3.7-SNAPSHOT-b244]
	at com.comphenix.protocol.reflect.StructureModifier.readInternal(StructureModifier.java:229) ~[ProtocolLib-B244.jar:3.7-SNAPSHOT-b244]
	at com.comphenix.protocol.reflect.StructureModifier.read(StructureModifier.java:197) ~[ProtocolLib-B244.jar:3.7-SNAPSHOT-b244]
	at com.comphenix.protocol.reflect.StructureModifier.readSafely(StructureModifier.java:260) ~[ProtocolLib-B244.jar:3.7-SNAPSHOT-b244]
	at de.Keyle.MyPet.util.hooks.ProtocolLib$1.onPacketSending(ProtocolLib.java:68) ~[MyPet-1.3.2-SNAPSHOT.jar:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) [ProtocolLib-B244.jar:3.7-SNAPSHOT-b244]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) [ProtocolLib-B244.jar:3.7-SNAPSHOT-b244]
	at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:637) [ProtocolLib-B244.jar:3.7-SNAPSHOT-b244]
	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:613) [ProtocolLib-B244.jar:3.7-SNAPSHOT-b244]
	at com.comphenix.protocol.compat.netty.independent.NettyProtocolInjector.packetQueued(NettyProtocolInjector.java:318) [ProtocolLib-B244.jar:3.7-SNAPSHOT-b244]
	at com.comphenix.protocol.compat.netty.independent.NettyProtocolInjector.onPacketSending(NettyProtocolInjector.java:278) [ProtocolLib-B244.jar:3.7-SNAPSHOT-b244]
	at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector.processSending(NettyChannelInjector.java:401) [ProtocolLib-B244.jar:3.7-SNAPSHOT-b244]
	at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector.access$500(NettyChannelInjector.java:82) [ProtocolLib-B244.jar:3.7-SNAPSHOT-b244]
	at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector$5.handleScheduled(NettyChannelInjector.java:367) [ProtocolLib-B244.jar:3.7-SNAPSHOT-b244]
	at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector$5.onMessageScheduled(NettyChannelInjector.java:335) [ProtocolLib-B244.jar:3.7-SNAPSHOT-b244]
	at com.comphenix.protocol.compat.netty.independent.NettyChannelProxy$2.schedulingRunnable(NettyChannelProxy.java:127) [ProtocolLib-B244.jar:3.7-SNAPSHOT-b244]
	at com.comphenix.protocol.compat.netty.independent.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:95) [ProtocolLib-B244.jar:3.7-SNAPSHOT-b244]
	at net.minecraft.server.v1_9_R1.NetworkManager.a(NetworkManager.java:193) [spigot.jar:git-Spigot-b39373b-60f01ef]
	at net.minecraft.server.v1_9_R1.NetworkManager.sendPacket(NetworkManager.java:142) [spigot.jar:git-Spigot-b39373b-60f01ef]
	at net.minecraft.server.v1_9_R1.PlayerConnection.sendPacket(PlayerConnection.java:1060) [spigot.jar:git-Spigot-b39373b-60f01ef]
	at net.minecraft.server.v1_9_R1.EntityTrackerEntry.broadcast(EntityTrackerEntry.java:292) [spigot.jar:git-Spigot-b39373b-60f01ef]
	at net.minecraft.server.v1_9_R1.EntityTrackerEntry.track(EntityTrackerEntry.java:188) [spigot.jar:git-Spigot-b39373b-60f01ef]
	at net.minecraft.server.v1_9_R1.EntityTracker.updatePlayers(EntityTracker.java:179) [spigot.jar:git-Spigot-b39373b-60f01ef]
	at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:809) [spigot.jar:git-Spigot-b39373b-60f01ef]
	at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot.jar:git-Spigot-b39373b-60f01ef]
	at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [spigot.jar:git-Spigot-b39373b-60f01ef]
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot.jar:git-Spigot-b39373b-60f01ef]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_74]
Caused by: com.comphenix.protocol.reflect.FieldAccessException: Cannot find entity from ID 1186.
	at com.comphenix.protocol.injector.EntityUtilities.getEntityFromID(EntityUtilities.java:256) ~[ProtocolLib-B244.jar:3.7-SNAPSHOT-b244]
	at com.comphenix.protocol.injector.PacketFilterManager.getEntityFromID(PacketFilterManager.java:982) ~[ProtocolLib-B244.jar:3.7-SNAPSHOT-b244]
	at com.comphenix.protocol.wrappers.BukkitConverters$13.getSpecificValue(BukkitConverters.java:694) ~[ProtocolLib-B244.jar:3.7-SNAPSHOT-b244]
	... 29 more
Caused by: java.lang.ClassCastException: Cannot cast net.citizensnpcs.util.nms.PlayerlistTrackerEntry to net.minecraft.server.v1_9_R1.EntityTracker
	at java.lang.Class.cast(Class.java:3369) ~[?:1.8.0_74]
	at com.comphenix.protocol.injector.EntityUtilities.getEntityTrackerEntry(EntityUtilities.java:221) ~[ProtocolLib-B244.jar:3.7-SNAPSHOT-b244]
	at com.comphenix.protocol.injector.EntityUtilities.getEntityFromID(EntityUtilities.java:231) ~[ProtocolLib-B244.jar:3.7-SNAPSHOT-b244]
	at com.comphenix.protocol.injector.PacketFilterManager.getEntityFromID(PacketFilterManager.java:982) ~[ProtocolLib-B244.jar:3.7-SNAPSHOT-b244]
	at com.comphenix.protocol.wrappers.BukkitConverters$13.getSpecificValue(BukkitConverters.java:694) ~[ProtocolLib-B244.jar:3.7-SNAPSHOT-b244]
	... 29 more
[12:46:33] [Server thread/ERROR]: Parameters: 
  net.minecraft.server.v1_9_R1.PacketPlayOutEntityTeleport@1cad3b73[
    a=1186
    b=-274.4795154974596
    c=94.0
    d=86.50496002605851
    e=2
    f=5
    g=true
  ]
`

**Comment by xXKeyleXx** [comment]
Duplicate to #683
