### ISSUE TITLE
MyPet Premium Beta 6 Error

### ISSUE THREAD

**Issue by andris155** [xXKeyleXx/MyPet#703]
```
[22:58:21] [Craft Scheduler Thread - 6502/WARN]: java.sql.SQLTransientConnectionException: HikariPool-0 - Connection is not available, request timed out after 30000ms.
[22:58:21] [Craft Scheduler Thread - 6502/WARN]: 	at de.Keyle.MyPet.util.hikari.pool.HikariPool.getConnection(HikariPool.java:195)
[22:58:21] [Craft Scheduler Thread - 6502/WARN]: 	at de.Keyle.MyPet.util.hikari.pool.HikariPool.getConnection(HikariPool.java:147)
[22:58:21] [Craft Scheduler Thread - 6502/WARN]: 	at de.Keyle.MyPet.util.hikari.HikariDataSource.getConnection(HikariDataSource.java:99)
[22:58:21] [Craft Scheduler Thread - 6502/WARN]: 	at de.Keyle.MyPet.repository.types.MySqlRepository$8.run(MySqlRepository.java:611)
[22:58:21] [Craft Scheduler Thread - 6502/WARN]: 	at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java:58)
[22:58:21] [Craft Scheduler Thread - 6502/WARN]: 	at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[22:58:21] [Craft Scheduler Thread - 6502/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[22:58:21] [Craft Scheduler Thread - 6502/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[22:58:21] [Craft Scheduler Thread - 6502/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[22:58:21] [Craft Scheduler Thread - 6502/WARN]: 	at java.lang.Thread.run(Unknown Source)
[22:58:21] [Craft Scheduler Thread - 6531/WARN]: java.sql.SQLTransientConnectionException: HikariPool-0 - Connection is not available, request timed out after 30000ms.
[22:58:21] [Craft Scheduler Thread - 6531/WARN]: 	at de.Keyle.MyPet.util.hikari.pool.HikariPool.getConnection(HikariPool.java:195)
[22:58:21] [Craft Scheduler Thread - 6531/WARN]: 	at de.Keyle.MyPet.util.hikari.pool.HikariPool.getConnection(HikariPool.java:147)
[22:58:21] [Craft Scheduler Thread - 6531/WARN]: 	at de.Keyle.MyPet.util.hikari.HikariDataSource.getConnection(HikariDataSource.java:99)
[22:58:21] [Craft Scheduler Thread - 6531/WARN]: 	at de.Keyle.MyPet.repository.types.MySqlRepository$14.run(MySqlRepository.java:1015)
[22:58:21] [Craft Scheduler Thread - 6531/WARN]: 	at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java:58)
[22:58:21] [Craft Scheduler Thread - 6531/WARN]: 	at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[22:58:21] [Craft Scheduler Thread - 6531/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[22:58:21] [Craft Scheduler Thread - 6531/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[22:58:21] [Craft Scheduler Thread - 6531/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[22:58:21] [Craft Scheduler Thread - 6531/WARN]: 	at java.lang.Thread.run(Unknown Source)
```

**Comment by xXKeyleXx** [comment]
Is your MySQL server available? How big is the MaxConnections value under MySQL in the config?

**Comment by andris155** [comment]
Fixed: Server restart.
/plugman load mypet = write MySQL error :(

**Comment by andris155** [comment]
Not fixed, MyPet write again errors.

**Comment by andris155** [comment]
Yes MySQL server available

**Comment by andris155** [comment]
MaxConnections: 48

**Comment by xXKeyleXx** [comment]
I think I know what the problem is. I will send you a message on the Spigot forums with a fixed version.

**Comment by andris155** [comment]
Ok. :)

**Comment by xXKeyleXx** [comment]
Message sent.

**Comment by andris155** [comment]
Thanks. :)
