### ISSUE TITLE
Mypet 2.0.0 Spigot 1.7.9 petcall error

### ISSUE THREAD

**Issue by IceBlade** [xXKeyleXx/MyPet#724]
my server is running Spigot 1.7.9, I installed mypet 2.0.0 is work correctly but when use /petc or /pc or/petcall it say an internal error has occocured. Can anyone help me please?

**Comment by xXKeyleXx** [comment]
I need the error from the console

**Comment by IceBlade** [comment]
It works perfectly and it doesnt give error just the code petcall wheni used it it says an internal error but nothing in mypet log

**Comment by xXKeyleXx** [comment]
If you get this message there must be something in the server logs.

**Comment by xXKeyleXx** [comment]
Are you use you use 1.7.9 not 1.7.10? Because it shouldn't work with 1.7.9 at all.

**Comment by IceBlade** [comment]
When i use /version in serer it says spgot 1.7.9(mcp 1.7.10)

**Comment by xXKeyleXx** [comment]
Is it vanilla Spigot or a modded version?

**Comment by IceBlade** [comment]
Crasftbukkit 1.7.x 1.8.x

**Comment by xXKeyleXx** [comment]
Ah that version of Spigot doesn't work anyway with MyPet. You need to use a version that either supports one or the other.

**Comment by IceBlade** [comment]
I have to run 1.7.x1.8x which versiyon can i use?

**Comment by xXKeyleXx** [comment]
There is no version for that.

**Comment by IceBlade** [comment]
Will u do it?

**Comment by xXKeyleXx** [comment]
Maybe idk. I'm against that hacky version trick.

**Comment by IceBlade** [comment]
I have to got it :\

**Comment by xXKeyleXx** [comment]
Could you upload the used spigot version. It's not easy to get the desired version these days....

**Comment by IceBlade** [comment]
hey w8 in game /version says 1.7.9 but in server files i have 1.7.10 how can i look mypet logs?

**Comment by IceBlade** [comment]
i have got a log file [15:53:48] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'pc' in plugin MyPet v2.0.0
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[craftbukkit.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) ~[craftbukkit.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:767) ~[craftbukkit.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	at net.minecraft.server.v1_7_R4.PlayerConnection.handleCommand(PlayerConnection.java:1043) [craftbukkit.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	at net.minecraft.server.v1_7_R4.PlayerConnection.a(PlayerConnection.java:880) [craftbukkit.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	at net.minecraft.server.v1_7_R4.PacketPlayInChat.a(PacketPlayInChat.java:28) [craftbukkit.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	at net.minecraft.server.v1_7_R4.PacketPlayInChat.handle(PacketPlayInChat.java:65) [craftbukkit.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	at net.minecraft.server.v1_7_R4.NetworkManager.a(NetworkManager.java:186) [craftbukkit.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	at net.minecraft.server.v1_7_R4.ServerConnection.c(ServerConnection.java:81) [craftbukkit.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:734) [craftbukkit.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289) [craftbukkit.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584) [craftbukkit.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490) [craftbukkit.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [craftbukkit.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
Caused by: java.lang.NoSuchFieldError: SPECTATOR
	at de.Keyle.MyPet.entity.MyPet.createEntity(MyPet.java:388) ~[?:?]
	at de.Keyle.MyPet.commands.CommandCall.onCommand(CommandCall.java:44) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[craftbukkit.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	... 13 more
 like this and it is 1.7.9 sorry

**Comment by xXKeyleXx** [comment]
That's what I needed :D

**Comment by xXKeyleXx** [comment]
Download the latest dev build and you should be fine

**Comment by IceBlade** [comment]
what ll i do with this?

**Comment by IceBlade** [comment]
can u give me link pls

**Comment by xXKeyleXx** [comment]
https://build.keyle.de/job/MyPet/878/

**Comment by IceBlade** [comment]
will i download this than copy it to plugins folder?

**Comment by xXKeyleXx** [comment]
yep

**Comment by IceBlade** [comment]
how can i download ths

**Comment by xXKeyleXx** [comment]
https://build.keyle.de/job/MyPet/878/artifact/target/MyPet-2.0.1-SNAPSHOT.jar

**Comment by IceBlade** [comment]
lets try it

**Comment by IceBlade** [comment]
how can i thank u? u saved my life

**Comment by IceBlade** [comment]
can i ride mypet?

**Comment by IceBlade** [comment]
when i used /petc it crashed thani cant login my server when i try it crashes

**Comment by IceBlade** [comment]
help pls minecraft crashes

**Comment by IceBlade** [comment]
hey?

**Comment by xXKeyleXx** [comment]
I'm not your servant so you have to wait until I have time to answer...

The problem you have is caused buy the version difference between MC 1.7 and 1.8. If you had uploaded the spigot version you are using as I told you to do I might be able to help you.

**Comment by IceBlade** [comment]
i am uploading it

**Comment by IceBlade** [comment]
https://mega.nz/#!OFV1TYIC!4-f2s1t_NzmA1wcEb6wCccQxM9RkJsMBM6L2XaX9Ryw 
here it is

**Comment by xXKeyleXx** [comment]
https://build.keyle.de/job/MyPet/879/artifact/target/MyPet-2.0.1-SNAPSHOT.jar

**Comment by IceBlade** [comment]
isnt that the same one with the first jar that u give?

**Comment by xXKeyleXx** [comment]
No...it's a different one

**Comment by IceBlade** [comment]
Okcwill try in 1 hour

**Comment by IceBlade** [comment]
it didnt worked it didnt crash for me but other players crashed

**Comment by xXKeyleXx** [comment]
Without any further info I can't help them/you. I need the pet types and Minecraft versions they/you play on. And please try the latest version of MyPet.

**Comment by IceBlade** [comment]
https://github.com/xXKeyleXx/MyPet/issues/729

can we continue from there?
1.7.x-1.8.x the snapshot works with 1.8.x players but crashes 1.7.x players

**Comment by xXKeyleXx** [comment]
You keep posting in both of them :P
