### ISSUE TITLE
MyPet-Premium 2.0.0 not work. (crash...)

### ISSUE THREAD

**Issue by andris155** [xXKeyleXx/MyPet#731]
```
---- Minecraft Crash Report ----
// Shall we play a game?

Time: 3/18/16 10:11 PM
Description: Exception in server tick loop

java.lang.IllegalArgumentException: Don't know how to add class de.Keyle.MyPet.compat.v1_9_R1.skill.skills.ranged.nms.MyPetArrow!
	at net.minecraft.server.v1_9_R1.EntityTrackerEntry.e(EntityTrackerEntry.java:581)
	at net.minecraft.server.v1_9_R1.EntityTrackerEntry.updatePlayer(EntityTrackerEntry.java:368)
	at net.minecraft.server.v1_9_R1.EntityTrackerEntry.scanPlayers(EntityTrackerEntry.java:467)
	at net.minecraft.server.v1_9_R1.EntityTrackerEntry.track(EntityTrackerEntry.java:82)
	at net.minecraft.server.v1_9_R1.EntityTracker.updatePlayers(EntityTracker.java:179)
	at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:864)
	at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:404)
	at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:714)
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:613)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by Kronox12** [comment]
This problem occured when we were testing out the /petrespawn command. My pet had the ranged skill with arrow for projectile. He used it. The server crashed.... twice...

**Comment by andris155** [comment]
pls fix. :(

**Comment by xXKeyleXx** [comment]
I already fixed that ;) I will upload a new version soon

**Comment by andris155** [comment]
Oh thanks, I wait new version. :)
