### ISSUE TITLE
Mypet 2.0 on spigot 1.9

### ISSUE THREAD

**Issue by learypro** [xXKeyleXx/MyPet#733]
[04:53:02] [Server thread/ERROR]: Could not pass event MyPetLevelUpEvent to MyPet v2.0.0
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot.jar:git-Spigot-7d15d07-c194444]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-7d15d07-c194444]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-7d15d07-c194444]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-7d15d07-c194444]
	at de.Keyle.MyPet.api.skill.MyPetExperience.addExp(MyPetExperience.java:113) [MyPet%202.0.0.jar:?]
	at de.Keyle.MyPet.listeners.EntityListener.onEntityDeath(EntityListener.java:921) [MyPet%202.0.0.jar:?]
	at sun.reflect.GeneratedMethodAccessor53.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_95]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_95]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) [spigot.jar:git-Spigot-7d15d07-c194444]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [spigot.jar:git-Spigot-7d15d07-c194444]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-7d15d07-c194444]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-7d15d07-c194444]
	at org.bukkit.craftbukkit.v1_9_R1.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:363) [spigot.jar:git-Spigot-7d15d07-c194444]
	at net.minecraft.server.v1_9_R1.EntityLiving.die(EntityLiving.java:974) [spigot.jar:git-Spigot-7d15d07-c194444]
	at net.minecraft.server.v1_9_R1.EntityZombie.die(EntityZombie.java:553) [spigot.jar:git-Spigot-7d15d07-c194444]
	at net.minecraft.server.v1_9_R1.EntityLiving.damageEntity(EntityLiving.java:890) [spigot.jar:git-Spigot-7d15d07-c194444]
	at net.minecraft.server.v1_9_R1.EntityMonster.damageEntity(EntityMonster.java:44) [spigot.jar:git-Spigot-7d15d07-c194444]
	at net.minecraft.server.v1_9_R1.EntityZombie.damageEntity(EntityZombie.java:179) [spigot.jar:git-Spigot-7d15d07-c194444]
	at de.Keyle.MyPet.compat.v1_9_R1.entity.EntityMyPet.attack(EntityMyPet.java:346) [MyPet%202.0.0.jar:?]
	at de.Keyle.MyPet.compat.v1_9_R1.entity.ai.attack.MeleeAttack.tick(MeleeAttack.java:113) [MyPet%202.0.0.jar:?]
	at de.Keyle.MyPet.api.entity.ai.AIGoalSelector.tick(AIGoalSelector.java:125) [MyPet%202.0.0.jar:?]
	at de.Keyle.MyPet.compat.v1_9_R1.entity.EntityMyPet.doMyPetTick(EntityMyPet.java:969) [MyPet%202.0.0.jar:?]
	at de.Keyle.MyPet.compat.v1_9_R1.entity.EntityMyPet.n(EntityMyPet.java:916) [MyPet%202.0.0.jar:?]
	at net.minecraft.server.v1_9_R1.EntityLiving.m(EntityLiving.java:1759) [spigot.jar:git-Spigot-7d15d07-c194444]
	at net.minecraft.server.v1_9_R1.EntityInsentient.m(EntityInsentient.java:243) [spigot.jar:git-Spigot-7d15d07-c194444]
	at de.Keyle.MyPet.compat.v1_9_R1.entity.EntityMyPet.m(EntityMyPet.java:1081) [MyPet%202.0.0.jar:?]
	at net.minecraft.server.v1_9_R1.World.entityJoinedWorld(World.java:1576) [spigot.jar:git-Spigot-7d15d07-c194444]
	at net.minecraft.server.v1_9_R1.World.g(World.java:1551) [spigot.jar:git-Spigot-7d15d07-c194444]
	at net.minecraft.server.v1_9_R1.World.tickEntities(World.java:1391) [spigot.jar:git-Spigot-7d15d07-c194444]
	at net.minecraft.server.v1_9_R1.WorldServer.tickEntities(WorldServer.java:627) [spigot.jar:git-Spigot-7d15d07-c194444]
	at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:787) [spigot.jar:git-Spigot-7d15d07-c194444]
	at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot.jar:git-Spigot-7d15d07-c194444]
	at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:655) [spigot.jar:git-Spigot-7d15d07-c194444]
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:554) [spigot.jar:git-Spigot-7d15d07-c194444]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_95]
Caused by: java.lang.IllegalArgumentException: Duplicate id value for 5!
	at net.minecraft.server.v1_9_R1.DataWatcher.register(DataWatcher.java:63) ~[spigot.jar:git-Spigot-7d15d07-c194444]
	at org.bukkit.craftbukkit.v1_9_R1.entity.CraftFirework.<init>(CraftFirework.java:29) ~[spigot.jar:git-Spigot-7d15d07-c194444]
	at org.bukkit.craftbukkit.v1_9_R1.entity.CraftEntity.getEntity(CraftEntity.java:181) ~[spigot.jar:git-Spigot-7d15d07-c194444]
	at net.minecraft.server.v1_9_R1.Entity.getBukkitEntity(Entity.java:54) ~[spigot.jar:git-Spigot-7d15d07-c194444]
	at net.minecraft.server.v1_9_R1.World.addEntity(World.java:938) ~[spigot.jar:git-Spigot-7d15d07-c194444]
	at org.bukkit.craftbukkit.v1_9_R1.CraftWorld.addEntity(CraftWorld.java:1130) ~[spigot.jar:git-Spigot-7d15d07-c194444]
	at org.bukkit.craftbukkit.v1_9_R1.CraftWorld.spawn(CraftWorld.java:1137) ~[spigot.jar:git-Spigot-7d15d07-c194444]
	at org.bukkit.craftbukkit.v1_9_R1.CraftWorld.spawn(CraftWorld.java:851) ~[spigot.jar:git-Spigot-7d15d07-c194444]
	at org.bukkit.craftbukkit.v1_9_R1.CraftWorld.spawnEntity(CraftWorld.java:360) ~[spigot.jar:git-Spigot-7d15d07-c194444]
	at de.Keyle.MyPet.listeners.LevelUpListener.onLevelUp(LevelUpListener.java:87) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_95]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_95]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_95]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_95]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-7d15d07-c194444]
	... 35 more

**Comment by learypro** [comment]
03-19-2016 04:23 [INFO] [MyPet] Compat mode for v1_9_R1 loaded.
03-19-2016 04:23 [INFO] [MyPet] Default skilltree file created (default.st).
03-19-2016 04:23 [INFO] [MyPet] No groups found. Everything will be in 'default' group.
03-19-2016 04:23 [INFO] [MyPet] --- Loading WorldGroups ---------------------------
03-19-2016 04:23 [INFO] [MyPet] added world to 'default' group.
03-19-2016 04:23 [INFO] [MyPet] added world_nether to 'default' group.
03-19-2016 04:23 [INFO] [MyPet] added world_the_end to 'default' group.
03-19-2016 04:23 [INFO] [MyPet] -------------------------------------------------
03-19-2016 04:23 [INFO] [MyPet] version 2.0.0-b873 ENABLED
03-19-2016 04:29 [INFO] [MyPet] Compat mode for v1_9_R1 loaded.
03-19-2016 04:29 [INFO] [MyPet] [NBT] 0 PetPlayer(s) loaded
03-19-2016 04:29 [INFO] [MyPet] [NBT] 0 pet(s) loaded
03-19-2016 04:29 [INFO] [MyPet] --- Loading WorldGroups ---------------------------
03-19-2016 04:29 [INFO] [MyPet]    added 'world' to 'default'
03-19-2016 04:29 [INFO] [MyPet]    added 'world_nether' to 'default'
03-19-2016 04:29 [INFO] [MyPet]    added 'world_the_end' to 'default'
03-19-2016 04:29 [INFO] [MyPet]  registered 'default' group
03-19-2016 04:29 [INFO] [MyPet] -------------------------------------------------
03-19-2016 04:29 [INFO] [MyPet] version 2.0.0-b873 ENABLED
03-19-2016 04:29 [INFO] [MyPet-NPC] version 1.0.5-b108 ENABLED

**Comment by xXKeyleXx** [comment]
Have you tried to update Spigot? Because that error looks like a Spigot problem.

**Comment by learypro** [comment]
Yes I have updated Spigot to the lastest version.

**Comment by xXKeyleXx** [comment]
Did it happened more than once?

**Comment by learypro** [comment]
Yes, it happened when mypet has level up.

2016-03-19 19:59 GMT+07:00 Sebastian Comans <notifications@github.com>:

**Comment by xXKeyleXx** [comment]
Hm... it doesn't happen for me. Have you changed the color?
