### ISSUE TITLE
org.bukkit.event.EventException

### ISSUE THREAD

**Issue by andris155** [xXKeyleXx/MyPet#748]
```
org.bukkit.event.EventException
	at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:46) ~[patched_1.9.jar:git-Paper-585]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[patched_1.9.jar:git-Paper-585]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.9.jar:git-Paper-585]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [patched_1.9.jar:git-Paper-585]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [patched_1.9.jar:git-Paper-585]
	at org.bukkit.craftbukkit.v1_9_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:89) [patched_1.9.jar:git-Paper-585]
	at org.bukkit.craftbukkit.v1_9_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:570) [patched_1.9.jar:git-Paper-585]
	at org.bukkit.craftbukkit.v1_9_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:479) [patched_1.9.jar:git-Paper-585]
	at org.bukkit.craftbukkit.v1_9_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:602) [patched_1.9.jar:git-Paper-585]
	at net.minecraft.server.v1_9_R1.EntityLiving.damageEntity0(EntityLiving.java:1218) [patched_1.9.jar:git-Paper-585]
	at net.minecraft.server.v1_9_R1.EntityLiving.damageEntity(EntityLiving.java:828) [patched_1.9.jar:git-Paper-585]
	at de.Keyle.MyPet.compat.v1_9_R1.entity.EntityMyPet.attack(EntityMyPet.java:346) [MyPet-Premium-2.0.2.jar:?]
	at de.Keyle.MyPet.compat.v1_9_R1.entity.ai.attack.MeleeAttack.tick(MeleeAttack.java:113) [MyPet-Premium-2.0.2.jar:?]
	at de.Keyle.MyPet.api.entity.ai.AIGoalSelector.tick(AIGoalSelector.java:125) [MyPet-Premium-2.0.2.jar:?]
	at de.Keyle.MyPet.compat.v1_9_R1.entity.EntityMyPet.doMyPetTick(EntityMyPet.java:969) [MyPet-Premium-2.0.2.jar:?]
	at de.Keyle.MyPet.compat.v1_9_R1.entity.EntityMyPet.n(EntityMyPet.java:916) [MyPet-Premium-2.0.2.jar:?]
	at net.minecraft.server.v1_9_R1.EntityLiving.m(EntityLiving.java:1782) [patched_1.9.jar:git-Paper-585]
	at net.minecraft.server.v1_9_R1.EntityInsentient.m(EntityInsentient.java:244) [patched_1.9.jar:git-Paper-585]
	at de.Keyle.MyPet.compat.v1_9_R1.entity.EntityMyPet.m(EntityMyPet.java:1091) [MyPet-Premium-2.0.2.jar:?]
	at net.minecraft.server.v1_9_R1.World.entityJoinedWorld(World.java:1727) [patched_1.9.jar:git-Paper-585]
	at net.minecraft.server.v1_9_R1.World.g(World.java:1702) [patched_1.9.jar:git-Paper-585]
	at net.minecraft.server.v1_9_R1.World.tickEntities(World.java:1527) [patched_1.9.jar:git-Paper-585]
	at net.minecraft.server.v1_9_R1.WorldServer.tickEntities(WorldServer.java:634) [patched_1.9.jar:git-Paper-585]
	at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:882) [patched_1.9.jar:git-Paper-585]
	at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:404) [patched_1.9.jar:git-Paper-585]
	at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:720) [patched_1.9.jar:git-Paper-585]
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:619) [patched_1.9.jar:git-Paper-585]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_51]
Caused by: java.lang.IllegalStateException: Optional.get() cannot be called on an absent value
	at com.google.common.base.Absent.get(Absent.java:47) ~[patched_1.9.jar:git-Paper-585]
	at de.Keyle.MyPet.skill.skills.Thorns.reflectDamage(Thorns.java:99) ~[?:?]
	at de.Keyle.MyPet.listeners.EntityListener.onMyPetEntityDamageByEntity(EntityListener.java:265) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor688.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44) ~[patched_1.9.jar:git-Paper-585]
	... 27 more
```

**Comment by xXKeyleXx** [comment]
Do you have any plugin that removes the pet when it damages something/someone?

**Comment by andris155** [comment]
No, I don't

**Comment by xXKeyleXx** [comment]
The problem is that the pet disappeared as the thorns damage was applied. If you don't have any plugins that could do that this error is not possible xD but who am I to question Java :D

**Comment by andris155** [comment]
Plugins (50): MobEggSpawnerBlocker, PlugMan, NametagEdit, MineMarket-Universal, EntityDetection, ChatColor, AsyncWorldEditInjector, CoreProtect, Deadbolt, SkinsModule, LimitCreative, CreativeNbtControl, ClearLag, ChatControl, Chairs, ProtocolLib, NoCheatPlus, LibsDisguises, AsyncWorldEdit, IPWhitelist, OldGoldSurvival, RedstoneClockDetector, PermissionsEx, Vault, FamoustLottery, FwdMsgChanger, MyCommand, PlayerHeads, WorldEdit, Essentials, PlotMe, Jobs, Auctions, Multiverse-Core, TreasureChest, EssentialsChat, MobArena, WorldGuard, EssentialsGeoIP, LimitedCreative, EssentialsSpawn, PvPManager, RedstoneClockPreventer, TitleManager, iZone, AreaShop, SurvivalGames, CraftBook, ChestShop, MyPet
