### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by andris155** [xXKeyleXx/MyPet#757]
```
1.04 17:17:58 [Server] WARN java.lang.NullPointerException
11.04 17:17:58 [Server] WARN at de.Keyle.MyPet.compat.v1_9_R1.entity.EntityMyPet.onLivingUpdate(EntityMyPet.java:551)
11.04 17:17:58 [Server] WARN at de.Keyle.MyPet.compat.v1_9_R1.entity.EntityMyPet.m(EntityMyPet.java:1093)
11.04 17:17:58 [Server] WARN at net.minecraft.server.v1_9_R1.World.entityJoinedWorld(World.java:1726)
11.04 17:17:58 [Server] WARN at net.minecraft.server.v1_9_R1.World.g(World.java:1701)
11.04 17:17:58 [Server] WARN at net.minecraft.server.v1_9_R1.World.tickEntities(World.java:1526)
11.04 17:17:58 [Server] WARN at net.minecraft.server.v1_9_R1.WorldServer.tickEntities(WorldServer.java:635)
11.04 17:17:58 [Server] WARN at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:883)
11.04 17:17:58 [Server] WARN at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:404)
11.04 17:17:58 [Server] WARN at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:721)
11.04 17:17:58 [Server] WARN at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:620)
11.04 17:17:58 [Server] WARN at java.lang.Thread.run(Unknown Source)
```

**Comment by xXKeyleXx** [comment]
Could you give me more info about your server (Paper/Spigot, version, plugins)

**Comment by andris155** [comment]
patched_1.9.2.jar:git-Paper-651

**Comment by andris155** [comment]
MyPet-Premium-2.0.4

**Comment by andris155** [comment]
Plugins (49): MobEggSpawnerBlocker, PlugMan, NametagEdit, MineMarket-Universal, EntityDetection, ChatColor, AsyncWorldEditInjector, CoreProtect, Deadbolt, SkinsModule, LimitCreative, CreativeNbtControl, ClearLag, ChatControl, Chairs, ProtocolLib, NoCheatPlus, LibsDisguises, AsyncWorldEdit, IPWhitelist, OldGoldSurvival, RedstoneClockDetector, PermissionsEx, Lottery, Vault, FwdMsgChanger, MyCommand, PlayerHeads, WorldEdit, Essentials, PlotMe, Jobs, Auctions, Multiverse-Core, TreasureChest, EssentialsChat, MobArena, WorldGuard, EssentialsGeoIP, LimitedCreative, EssentialsSpawn, PvPManager, RedstoneClockPreventer, TitleManager, MyPet, iZone, AreaShop, ChestShop, CraftBook

**Comment by xXKeyleXx** [comment]
Could you copy some lines before and after the error so I can get an idea what was going on when this happened.

**Comment by andris155** [comment]
```
[17:17:27] [Server thread/INFO]: MINEPRO issued server command: /back
[17:17:27] [Server thread/INFO]: StenHD issued server command: /petrelease
[17:17:31] [User Authenticator #391/INFO]: UUID of player asder023 is bf5b2e22-8c9c-3f4e-9c83-21e6136e1abe
[17:17:31] [Server thread/INFO]: asder023[/************:41164] logged in with entity id 645274 at ([world]25535.30000001192, 57.0, 32755.207423728607)
[17:17:31] [Server thread/INFO]: [CraftBook] Enabling CraftBook v3.9-SNAPSHOT
[17:17:31] [Server thread/INFO]: [CraftBook] Loading persistent data from YAML!
[17:17:31] [Server thread/INFO]: [CraftBook] Registered 15 custom recipes!
[17:17:31] [Server thread/INFO]: [CraftBook] Enumerating chunks for self-triggered components...
[17:17:31] [Server thread/INFO]: [CraftBook] 6530 chunk(s) for 6 world(s) processed (63ms elapsed)
[17:17:31] [Server thread/INFO]: [PlugMan] Craftbook has been loaded and enabled.
[17:17:32] [Server thread/INFO]: [+] asder023
[17:17:34] [Server thread/INFO]: elliot issued server command: /home spawner
[17:17:37] [Server thread/INFO]: StenHD issued server command: /r most meg azt írja hívjam ide :P
[17:17:40] [Server thread/INFO]: kalmpanna issued server command: /tpahere dingdong2000
[17:17:43] [Server thread/INFO]: dingdong2000 issued server command: /tpaccept
[17:17:48] [Async Chat Thread - #105/INFO]: [Tag]jazmin666: Mit kérsz?
[17:17:51] [Async Chat Thread - #105/INFO]: [Elit]StenHD: Várj menézem ha lelépek jó lesz e
[17:17:57] [Server thread/INFO]: Rubikkocka issued server command: /tpa jazmin666
[17:17:58] [Server thread/INFO]: StenHD lost connection: Disconnected
[17:17:58] [Server thread/INFO]: [-] StenHD
[17:17:58] [Server thread/WARN]: java.lang.NullPointerException
[17:17:58] [Server thread/WARN]: 	at de.Keyle.MyPet.compat.v1_9_R1.entity.EntityMyPet.onLivingUpdate(EntityMyPet.java:551)
[17:17:58] [Server thread/WARN]: 	at de.Keyle.MyPet.compat.v1_9_R1.entity.EntityMyPet.m(EntityMyPet.java:1093)
[17:17:58] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.World.entityJoinedWorld(World.java:1726)
[17:17:58] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.World.g(World.java:1701)
[17:17:58] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.World.tickEntities(World.java:1526)
[17:17:58] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.WorldServer.tickEntities(WorldServer.java:635)
[17:17:58] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:883)
[17:17:58] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:404)
[17:17:58] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:721)
[17:17:58] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:620)
[17:17:58] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
```
