### ISSUE TITLE
Error in Mypet 2

### ISSUE THREAD

**Issue by Gothicraft** [xXKeyleXx/MyPet#759]
I have this error on my server 1.7.10
Please Help me!:

[18:53:09] [Server thread/ERROR]: Could not pass event EntityDamageByEntityEvent to MyPet v2.0.4
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:299) ~[SPIGOT1710:git-Spigot-1604]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[SPIGOT1710:git-Spigot-1604]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [SPIGOT1710:git-Spigot-1604]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [SPIGOT1710:git-Spigot-1604]
	at org.bukkit.craftbukkit.v1_7_R4.event.CraftEventFactory.callEvent(CraftEventFactory.java:108) [SPIGOT1710:git-Spigot-1604]
	at org.bukkit.craftbukkit.v1_7_R4.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:549) [SPIGOT1710:git-Spigot-1604]
	at org.bukkit.craftbukkit.v1_7_R4.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:462) [SPIGOT1710:git-Spigot-1604]
	at org.bukkit.craftbukkit.v1_7_R4.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:581) [SPIGOT1710:git-Spigot-1604]
	at net.minecraft.server.v1_7_R4.EntityLiving.d(EntityLiving.java:1040) [SPIGOT1710:git-Spigot-1604]
	at net.minecraft.server.v1_7_R4.EntityLiving.damageEntity(EntityLiving.java:684) [SPIGOT1710:git-Spigot-1604]
	at net.minecraft.server.v1_7_R4.EntityAnimal.damageEntity(SourceFile:145) [SPIGOT1710:git-Spigot-1604]
	at net.minecraft.server.v1_7_R4.EntityHuman.attack(EntityHuman.java:948) [SPIGOT1710:git-Spigot-1604]
	at net.minecraft.server.v1_7_R4.PlayerConnection.a(PlayerConnection.java:1191) [SPIGOT1710:git-Spigot-1604]
	at net.minecraft.server.v1_7_R4.PacketPlayInUseEntity.a(SourceFile:55) [SPIGOT1710:git-Spigot-1604]
	at net.minecraft.server.v1_7_R4.PacketPlayInUseEntity.handle(SourceFile:10) [SPIGOT1710:git-Spigot-1604]
	at net.minecraft.server.v1_7_R4.NetworkManager.a(NetworkManager.java:184) [SPIGOT1710:git-Spigot-1604]
	at net.minecraft.server.v1_7_R4.ServerConnection.c(ServerConnection.java:81) [SPIGOT1710:git-Spigot-1604]
	at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:734) [SPIGOT1710:git-Spigot-1604]
	at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289) [SPIGOT1710:git-Spigot-1604]
	at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584) [SPIGOT1710:git-Spigot-1604]
	at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490) [SPIGOT1710:git-Spigot-1604]
	at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [SPIGOT1710:git-Spigot-1604]
Caused by: java.lang.NoClassDefFoundError: org/bukkit/entity/Guardian
	at de.Keyle.MyPet.listeners.EntityListener.onEntityDamageByPlayer(EntityListener.java:472) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor263.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_73]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_73]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:296) ~[SPIGOT1710:git-Spigot-1604]
	... 21 more
Caused by: java.lang.ClassNotFoundException: org.bukkit.entity.Guardian
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91) ~[SPIGOT1710:git-Spigot-1604]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[SPIGOT1710:git-Spigot-1604]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_73]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_73]
	at de.Keyle.MyPet.listeners.EntityListener.onEntityDamageByPlayer(EntityListener.java:472) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor263.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_73]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_73]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:296) ~[SPIGOT1710:git-Spigot-1604]
	... 21 more
[18:53:09] [Server thread/ERROR]: Could not pass event EntityDamageByEntityEvent to MyPet v2.0.4
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:299) ~[SPIGOT1710:git-Spigot-1604]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[SPIGOT1710:git-Spigot-1604]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [SPIGOT1710:git-Spigot-1604]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [SPIGOT1710:git-Spigot-1604]
	at org.bukkit.craftbukkit.v1_7_R4.event.CraftEventFactory.callEvent(CraftEventFactory.java:108) [SPIGOT1710:git-Spigot-1604]
	at org.bukkit.craftbukkit.v1_7_R4.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:549) [SPIGOT1710:git-Spigot-1604]
	at org.bukkit.craftbukkit.v1_7_R4.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:462) [SPIGOT1710:git-Spigot-1604]
	at org.bukkit.craftbukkit.v1_7_R4.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:581) [SPIGOT1710:git-Spigot-1604]
	at net.minecraft.server.v1_7_R4.EntityLiving.d(EntityLiving.java:1040) [SPIGOT1710:git-Spigot-1604]
	at net.minecraft.server.v1_7_R4.EntityLiving.damageEntity(EntityLiving.java:684) [SPIGOT1710:git-Spigot-1604]
	at net.minecraft.server.v1_7_R4.EntityAnimal.damageEntity(SourceFile:145) [SPIGOT1710:git-Spigot-1604]
	at net.minecraft.server.v1_7_R4.EntityHuman.attack(EntityHuman.java:948) [SPIGOT1710:git-Spigot-1604]
	at net.minecraft.server.v1_7_R4.PlayerConnection.a(PlayerConnection.java:1191) [SPIGOT1710:git-Spigot-1604]
	at net.minecraft.server.v1_7_R4.PacketPlayInUseEntity.a(SourceFile:55) [SPIGOT1710:git-Spigot-1604]
	at net.minecraft.server.v1_7_R4.PacketPlayInUseEntity.handle(SourceFile:10) [SPIGOT1710:git-Spigot-1604]
	at net.minecraft.server.v1_7_R4.NetworkManager.a(NetworkManager.java:184) [SPIGOT1710:git-Spigot-1604]
	at net.minecraft.server.v1_7_R4.ServerConnection.c(ServerConnection.java:81) [SPIGOT1710:git-Spigot-1604]
	at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:734) [SPIGOT1710:git-Spigot-1604]
	at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289) [SPIGOT1710:git-Spigot-1604]
	at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584) [SPIGOT1710:git-Spigot-1604]
	at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490) [SPIGOT1710:git-Spigot-1604]
	at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [SPIGOT1710:git-Spigot-1604]
Caused by: java.lang.NoClassDefFoundError: org/bukkit/entity/Guardian
	at de.Keyle.MyPet.listeners.EntityListener.onEntityDamageByPlayer(EntityListener.java:472) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor263.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_73]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_73]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:296) ~[SPIGOT1710:git-Spigot-1604]
	... 21 more

**Comment by Gothicraft** [comment]
i from argentina and my english is bad, Sorry
I forgot to tell you that when this error gives players can not enter more to sv
client crash
