### ISSUE TITLE
MyPet v2.0.6 premium generated an exception

### ISSUE THREAD

**Issue by andris155** [xXKeyleXx/MyPet#772]
```
[16:11:33] [Server thread/WARN]: [[0;32;22mMyPet[m] [mTask #70 for MyPet v2.0.6 generated an exception[m
java.lang.NullPointerException
	at de.Keyle.MyPet.compat.v1_9_R1.util.inventory.ItemStackComparator.compareTagData(ItemStackComparator.java:115) ~[?:?]
	at de.Keyle.MyPet.compat.v1_9_R1.util.inventory.ItemStackComparator.compareItem(ItemStackComparator.java:33) ~[?:?]
	at de.Keyle.MyPet.compat.v1_9_R1.util.inventory.CustomInventory.addItem(CustomInventory.java:111) ~[?:?]
	at de.Keyle.MyPet.skill.skills.Pickup.schedule(Pickup.java:153) ~[?:?]
	at de.Keyle.MyPet.entity.MyPet.schedule(MyPet.java:512) ~[?:?]
	at de.Keyle.MyPet.api.util.Timer$1.run(Timer.java:53) ~[?:?]
	at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java:58) ~[patched_1.9.2.jar:git-Paper-706]
	at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:352) [patched_1.9.2.jar:git-Paper-706]
	at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:820) [patched_1.9.2.jar:git-Paper-706]
	at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:404) [patched_1.9.2.jar:git-Paper-706]
	at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:721) [patched_1.9.2.jar:git-Paper-706]
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:620) [patched_1.9.2.jar:git-Paper-706]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_91]
```

**Comment by xXKeyleXx** [comment]
Already fixed and a new update was published Tuesday at 9:45 PM ;) please update before opening tickets :P
