### ISSUE TITLE
Pets cause server crashes

### ISSUE THREAD

**Issue by Ldcr993519867** [xXKeyleXx/MyPet#778]
The page uses Baidu translate, please don't care about my grammar

When a pet shot a arrow,the server crashes.
----------------
Description: Exception in server tick loop

java.lang.IllegalArgumentException: Don't know how to add class de.Keyle.MyPet.compat.v1_9_R1.skill.skills.ranged.nms.MyPetArrow!
	at net.minecraft.server.v1_9_R1.EntityTrackerEntry.e(EntityTrackerEntry.java:555)
	at net.minecraft.server.v1_9_R1.EntityTrackerEntry.updatePlayer(EntityTrackerEntry.java:342)
	at net.minecraft.server.v1_9_R1.EntityTrackerEntry.scanPlayers(EntityTrackerEntry.java:441)
	at net.minecraft.server.v1_9_R1.EntityTrackerEntry.track(EntityTrackerEntry.java:77)
	at net.minecraft.server.v1_9_R1.EntityTracker.updatePlayers(EntityTracker.java:179)
	at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:804)
	at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400)
	at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:655)
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:554)
	at java.lang.Thread.run(Unknown Source)

---------------
This server is running CraftBukkit version git-Spigot-ee4e41a-3879b98 (MC: 1.9) (Implementing API version 1.9-R0.1-SNAPSHOT)
---------------
Plugins (29): WorldEdit, ColorChat, FrameProtect, CommandCode, clear, ChopTreeW, Vault, Multiverse-Core, PermissionsEx, AT, GlobalMarket, UDtitle, CoreProtect, BetterChairs, ActionAnnouncer, SafeNetherDoor, ProtocolLib, Elytra, Essentials, Residence, EssentialsProtect, ServerSigns, EssentialsSpawn, EssentialsAntiBuild, LockettePro, AuthMe, EssentialsChat, NeverLag, ColorMOTD

**Comment by xXKeyleXx** [comment]
MyPet version?

**Comment by Ldcr993519867** [comment]
2.0.0
I download it from dev.bukkit.org
http://dev.bukkit.org/bukkit-plugins/mypet/files/47-mypet-2-0-0-for-mc-1-7-10-1-8-3-1-8-9-1-9/

**Comment by xXKeyleXx** [comment]
You should download MyPet from Spigot from now on. I will not update it on BukkitDev anymore.

https://www.spigotmc.org/resources/mypet.12725/
