### ISSUE TITLE
MyPet Premium 2.0.9 Unhandled exception executing command

### ISSUE THREAD

**Issue by andris155** [xXKeyleXx/MyPet#785]
```
[17:07:07] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'petname' in plugin MyPet v2.0.9
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.9.2.jar:git-Paper-727]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:146) ~[patched_1.9.2.jar:git-Paper-727]
	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.dispatchCommand(CraftServer.java:664) ~[patched_1.9.2.jar:git-Paper-727]
	at net.minecraft.server.v1_9_R1.PlayerConnection.handleCommand(PlayerConnection.java:1388) [patched_1.9.2.jar:git-Paper-727]
	at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:1193) [patched_1.9.2.jar:git-Paper-727]
	at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [patched_1.9.2.jar:git-Paper-727]
	at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) [patched_1.9.2.jar:git-Paper-727]
	at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [patched_1.9.2.jar:git-Paper-727]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_91]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_91]
	at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [patched_1.9.2.jar:git-Paper-727]
	at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:813) [patched_1.9.2.jar:git-Paper-727]
	at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:404) [patched_1.9.2.jar:git-Paper-727]
	at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:723) [patched_1.9.2.jar:git-Paper-727]
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:622) [patched_1.9.2.jar:git-Paper-727]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_91]
Caused by: java.lang.IllegalStateException: Optional.get() cannot be called on an absent value
	at com.google.common.base.Absent.get(Absent.java:47) ~[patched_1.9.2.jar:git-Paper-727]
	at de.Keyle.MyPet.entity.MyPet.setPetName(MyPet.java:247) ~[?:?]
	at de.Keyle.MyPet.commands.CommandName.onCommand(CommandName.java:83) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.9.2.jar:git-Paper-727]
	... 15 more
```

**Comment by xXKeyleXx** [comment]
Should be fixed in the next version. Thanks for reporting.
