### ISSUE TITLE
Error on Pet Activate

### ISSUE THREAD

**Issue by Phreag** [xXKeyleXx/MyPet#786]
Using Paper 1.9.2

[21:50:25 WARN]: [MyPet] Task #45384416 for MyPet v2.0.7 generated an exception
java.lang.NullPointerException
        at de.Keyle.MyPet.repository.MyPetManager.activateMyPet(MyPetManager.java:77) ~[?:?]
        at de.Keyle.MyPet.listeners.PlayerListener$1$1$1.callback(PlayerListener.java:165) ~[?:?]
        at de.Keyle.MyPet.listeners.PlayerListener$1$1$1.callback(PlayerListener.java:162) ~[?:?]
        at de.Keyle.MyPet.api.repository.RepositoryCallback.run(RepositoryCallback.java:37) ~[?:?]
        at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java:58) ~[spigot.jar:gi
t-Paper-724]
        at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftSchedule
r.java:352) [spigot.jar:git-Paper-724]
        at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:822) [spigot.jar:git-
Paper-724]
        at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:404) [spigot.jar:git-
Paper-724]
        at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:723) [spigot.jar:git-
Paper-724]
        at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:622) [spigot.jar:gi
t-Paper-724]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_71]

**Comment by Phreag** [comment]
[21:50:24 INFO]: [BungeePerms] Login by Reporp
[21:50:24 INFO]: Reporp[/188.105.223.110:60998] logged in with entity id 11647999 at ([world]8289.26
9479326293, 68.0, -2081.896128752413)
[21:50:25 WARN]: java.lang.reflect.InvocationTargetException
[21:50:25 WARN]:        at sun.reflect.GeneratedConstructorAccessor312.newInstance(Unknown Source)
[21:50:25 WARN]:        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConst
ructorAccessorImpl.java:45)
[21:50:25 WARN]:        at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
[21:50:25 WARN]:        at de.Keyle.MyPet.entity.MyPetClass.getNewMyPetInstance(MyPetClass.java:81)
[21:50:25 WARN]:        at de.Keyle.MyPet.repository.MyPetManager.activateMyPet(MyPetManager.java:76
)
[21:50:25 WARN]:        at de.Keyle.MyPet.listeners.PlayerListener$1$1$1.callback(PlayerListener.jav
a:165)
[21:50:25 WARN]:        at de.Keyle.MyPet.listeners.PlayerListener$1$1$1.callback(PlayerListener.jav
a:162)
[21:50:25 WARN]:        at de.Keyle.MyPet.api.repository.RepositoryCallback.run(RepositoryCallback.j
ava:37)
[21:50:25 WARN]:        at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java:58)

[21:50:25 WARN]:        at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftScheduler.mainThreadHeartbe
at(CraftScheduler.java:352)
[21:50:25 WARN]:        at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:822)
[21:50:25 WARN]:        at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:404)
[21:50:25 WARN]:        at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:723)
[21:50:25 WARN]:        at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:622
)
[21:50:25 WARN]:        at java.lang.Thread.run(Thread.java:745)
[21:50:25 WARN]: Caused by: java.lang.NullPointerException

**Comment by Phreag** [comment]
Can be closed, bug does no more exist in newer versions
