### ISSUE TITLE
Could not pass event PlayerInteractEvent to MyPet v2.1.0

### ISSUE THREAD

**Issue by PinoyLifeCraft** [xXKeyleXx/MyPet#800]
[19:20:37 ERROR]: Could not pass event PlayerInteractEvent to MyPet v2.1.0
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.ja
va:310) ~[craftbukkit.jar:git-Spigot-8a048fe-a022dd2]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.jav
a:62) ~[craftbukkit.jar:git-Spigot-8a048fe-a022dd2]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.j
ava:502) [craftbukkit.jar:git-Spigot-8a048fe-a022dd2]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.j
ava:487) [craftbukkit.jar:git-Spigot-8a048fe-a022dd2]
        at org.bukkit.craftbukkit.v1_9_R2.event.CraftEventFactory.callPlayerInte
ractEvent(CraftEventFactory.java:231) [craftbukkit.jar:git-Spigot-8a048fe-a022dd
2]
        at org.bukkit.craftbukkit.v1_9_R2.event.CraftEventFactory.callPlayerInte
ractEvent(CraftEventFactory.java:198) [craftbukkit.jar:git-Spigot-8a048fe-a022dd
2]
        at org.bukkit.craftbukkit.v1_9_R2.event.CraftEventFactory.callPlayerInte
ractEvent(CraftEventFactory.java:194) [craftbukkit.jar:git-Spigot-8a048fe-a022dd
2]
        at net.minecraft.server.v1_9_R2.PlayerConnection.a(PlayerConnection.java
:944) [craftbukkit.jar:git-Spigot-8a048fe-a022dd2]
        at net.minecraft.server.v1_9_R2.PacketPlayInBlockPlace.a(PacketPlayInBlo
ckPlace.java:27) [craftbukkit.jar:git-Spigot-8a048fe-a022dd2]
        at net.minecraft.server.v1_9_R2.PacketPlayInBlockPlace.a(PacketPlayInBlo
ckPlace.java:1) [craftbukkit.jar:git-Spigot-8a048fe-a022dd2]
        at net.minecraft.server.v1_9_R2.PlayerConnectionUtils$1.run(SourceFile:1
3) [craftbukkit.jar:git-Spigot-8a048fe-a022dd2]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [
?:1.8.0_66]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_66]
        at net.minecraft.server.v1_9_R2.SystemUtils.a(SourceFile:45) [craftbukki

        at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:7
26) [craftbukkit.jar:git-Spigot-8a048fe-a022dd2]
        at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:3
99) [craftbukkit.jar:git-Spigot-8a048fe-a022dd2]
        at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:6
65) [craftbukkit.jar:git-Spigot-8a048fe-a022dd2]
        at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java
:564) [craftbukkit.jar:git-Spigot-8a048fe-a022dd2]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_66]
Caused by: java.lang.NullPointerException
        at de.Keyle.MyPet.compat.v1_9_R2.util.ConfigItem.compare(ConfigItem.java
:47) ~[?:?]
        at de.Keyle.MyPet.listeners.PlayerListener.onPlayerInteract(PlayerListen
er.java:67) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor163.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1
.8.0_66]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_66]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.ja
va:306) ~[craftbukkit.jar:git-Spigot-8a048fe-a022dd2]
        ... 18 more

**Comment by xXKeyleXx** [comment]
What's your control item (config)?
