### ISSUE TITLE
Could not pass event PlayerInteractEvent to MyPet v2.1.1

### ISSUE THREAD

**Issue by PinoyLifeCraft** [xXKeyleXx/MyPet#805]
[14:54:52 ERROR]: Could not pass event PlayerInteractEvent to MyPet v2.1.1
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.ja
va:310) ~[craftbukkit.jar:git-Spigot-8a048fe-71e5248]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.jav
a:62) ~[craftbukkit.jar:git-Spigot-8a048fe-71e5248]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.j
ava:502) [craftbukkit.jar:git-Spigot-8a048fe-71e5248]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.j
ava:487) [craftbukkit.jar:git-Spigot-8a048fe-71e5248]
        at org.bukkit.craftbukkit.v1_9_R2.event.CraftEventFactory.callPlayerInte
ractEvent(CraftEventFactory.java:231) [craftbukkit.jar:git-Spigot-8a048fe-71e524
8]
        at org.bukkit.craftbukkit.v1_9_R2.event.CraftEventFactory.callPlayerInte
ractEvent(CraftEventFactory.java:198) [craftbukkit.jar:git-Spigot-8a048fe-71e524
8]
        at org.bukkit.craftbukkit.v1_9_R2.event.CraftEventFactory.callPlayerInte
ractEvent(CraftEventFactory.java:194) [craftbukkit.jar:git-Spigot-8a048fe-71e524
8]
        at net.minecraft.server.v1_9_R2.PlayerConnection.a(PlayerConnection.java
:944) [craftbukkit.jar:git-Spigot-8a048fe-71e5248]
        at net.minecraft.server.v1_9_R2.PacketPlayInBlockPlace.a(PacketPlayInBlo
ckPlace.java:27) [craftbukkit.jar:git-Spigot-8a048fe-71e5248]
        at net.minecraft.server.v1_9_R2.PacketPlayInBlockPlace.a(PacketPlayInBlo
ckPlace.java:1) [craftbukkit.jar:git-Spigot-8a048fe-71e5248]
        at net.minecraft.server.v1_9_R2.PlayerConnectionUtils$1.run(SourceFile:1
3) [craftbukkit.jar:git-Spigot-8a048fe-71e5248]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [
?:1.8.0_66]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_66]
        at net.minecraft.server.v1_9_R2.SystemUtils.a(SourceFile:45) [craftbukki
t.jar:git-Spigot-8a048fe-71e5248]
        at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:7
26) [craftbukkit.jar:git-Spigot-8a048fe-71e5248]
        at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:3
99) [craftbukkit.jar:git-Spigot-8a048fe-71e5248]
        at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:6
65) [craftbukkit.jar:git-Spigot-8a048fe-71e5248]
        at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java
:564) [craftbukkit.jar:git-Spigot-8a048fe-71e5248]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_66]
Caused by: java.lang.NullPointerException
        at de.Keyle.MyPet.compat.v1_9_R2.util.ConfigItem.compare(ConfigItem.java
:47) ~[?:?]
        at de.Keyle.MyPet.listeners.PlayerListener.on(PlayerListener.java:67) ~[
?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0
_66]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0
_66]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1
.8.0_66]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_66]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.ja
va:306) ~[craftbukkit.jar:git-Spigot-8a048fe-71e5248]
        ... 18 more

**Comment by xXKeyleXx** [comment]
posting the same error twice doens't make me fix it faster....

**Comment by xXKeyleXx** [comment]
duplicate to #800
