### ISSUE TITLE
MyPet Premium 2.1.7 error (onPacketSending)

### ISSUE THREAD

**Issue by andris155** [xXKeyleXx/MyPet#817]
```
[18:19:31] [Server thread/ERROR]: [MyPet] Unhandled exception occured in onPacketSending(PacketEvent) for MyPet
com.comphenix.protocol.reflect.FieldAccessException: Field index out of bounds. (Index: 3, Size: 2)
	at com.comphenix.protocol.reflect.StructureModifier.readInternal(StructureModifier.java:223) ~[ProtocolLib.jar:4.0.2-SNAPSHOT-b293]
	at com.comphenix.protocol.reflect.StructureModifier.read(StructureModifier.java:198) ~[ProtocolLib.jar:4.0.2-SNAPSHOT-b293]
	at de.Keyle.MyPet.util.hooks.ProtocolLib$2.onPacketSending(ProtocolLib.java:143) ~[MyPet-Premium-2.1.7.jar:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) [ProtocolLib.jar:4.0.2-SNAPSHOT-b293]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) [ProtocolLib.jar:4.0.2-SNAPSHOT-b293]
	at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:608) [ProtocolLib.jar:4.0.2-SNAPSHOT-b293]
	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:584) [ProtocolLib.jar:4.0.2-SNAPSHOT-b293]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:309) [ProtocolLib.jar:4.0.2-SNAPSHOT-b293]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:269) [ProtocolLib.jar:4.0.2-SNAPSHOT-b293]
	at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:396) [ProtocolLib.jar:4.0.2-SNAPSHOT-b293]
	at com.comphenix.protocol.injector.netty.ChannelInjector.access$500(ChannelInjector.java:77) [ProtocolLib.jar:4.0.2-SNAPSHOT-b293]
	at com.comphenix.protocol.injector.netty.ChannelInjector$5.handleScheduled(ChannelInjector.java:362) [ProtocolLib.jar:4.0.2-SNAPSHOT-b293]
	at com.comphenix.protocol.injector.netty.ChannelInjector$5.onMessageScheduled(ChannelInjector.java:330) [ProtocolLib.jar:4.0.2-SNAPSHOT-b293]
	at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) [ProtocolLib.jar:4.0.2-SNAPSHOT-b293]
	at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) [ProtocolLib.jar:4.0.2-SNAPSHOT-b293]
	at net.minecraft.server.v1_10_R1.NetworkManager.a(NetworkManager.java:194) [patched_1.10.jar:git-Paper-781]
	at net.minecraft.server.v1_10_R1.NetworkManager.sendPacket(NetworkManager.java:143) [patched_1.10.jar:git-Paper-781]
	at net.minecraft.server.v1_10_R1.PlayerConnection.sendPacket(PlayerConnection.java:1102) [patched_1.10.jar:git-Paper-781]
	at net.minecraft.server.v1_10_R1.EntityTrackerEntry.track(EntityTrackerEntry.java:225) [patched_1.10.jar:git-Paper-781]
	at net.minecraft.server.v1_10_R1.EntityTracker.updatePlayers(EntityTracker.java:178) [patched_1.10.jar:git-Paper-781]
	at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:881) [patched_1.10.jar:git-Paper-781]
	at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:403) [patched_1.10.jar:git-Paper-781]
	at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:730) [patched_1.10.jar:git-Paper-781]
	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:629) [patched_1.10.jar:git-Paper-781]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_91]
[18:19:31] [Server thread/ERROR]: Parameters: 
  net.minecraft.server.v1_10_R1.PacketPlayOutEntity$PacketPlayOutRelEntityMoveLook@6132243c[
    a=445957
    b=1540
    c=0
    d=-4727
    e=-125
    f=2
    g=true
    h=true
  ]
```

```
[18:30:55] [Server thread/ERROR]: [MyPet] Unhandled exception number 512 occured in onPacketSending(PacketEvent) for MyPet
com.comphenix.protocol.reflect.FieldAccessException: Field index out of bounds. (Index: 3, Size: 2)
	at com.comphenix.protocol.reflect.StructureModifier.readInternal(StructureModifier.java:223) ~[ProtocolLib.jar:4.0.2-SNAPSHOT-b293]
	at com.comphenix.protocol.reflect.StructureModifier.read(StructureModifier.java:198) ~[ProtocolLib.jar:4.0.2-SNAPSHOT-b293]
	at de.Keyle.MyPet.util.hooks.ProtocolLib$2.onPacketSending(ProtocolLib.java:143) ~[MyPet-Premium-2.1.7.jar:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) [ProtocolLib.jar:4.0.2-SNAPSHOT-b293]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) [ProtocolLib.jar:4.0.2-SNAPSHOT-b293]
	at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:608) [ProtocolLib.jar:4.0.2-SNAPSHOT-b293]
	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:584) [ProtocolLib.jar:4.0.2-SNAPSHOT-b293]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:309) [ProtocolLib.jar:4.0.2-SNAPSHOT-b293]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:269) [ProtocolLib.jar:4.0.2-SNAPSHOT-b293]
	at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:396) [ProtocolLib.jar:4.0.2-SNAPSHOT-b293]
	at com.comphenix.protocol.injector.netty.ChannelInjector.access$500(ChannelInjector.java:77) [ProtocolLib.jar:4.0.2-SNAPSHOT-b293]
	at com.comphenix.protocol.injector.netty.ChannelInjector$5.handleScheduled(ChannelInjector.java:362) [ProtocolLib.jar:4.0.2-SNAPSHOT-b293]
	at com.comphenix.protocol.injector.netty.ChannelInjector$5.onMessageScheduled(ChannelInjector.java:330) [ProtocolLib.jar:4.0.2-SNAPSHOT-b293]
	at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) [ProtocolLib.jar:4.0.2-SNAPSHOT-b293]
	at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) [ProtocolLib.jar:4.0.2-SNAPSHOT-b293]
	at net.minecraft.server.v1_10_R1.NetworkManager.a(NetworkManager.java:194) [patched_1.10.jar:git-Paper-781]
	at net.minecraft.server.v1_10_R1.NetworkManager.sendPacket(NetworkManager.java:143) [patched_1.10.jar:git-Paper-781]
	at net.minecraft.server.v1_10_R1.PlayerConnection.sendPacket(PlayerConnection.java:1102) [patched_1.10.jar:git-Paper-781]
	at net.minecraft.server.v1_10_R1.EntityTrackerEntry.track(EntityTrackerEntry.java:225) [patched_1.10.jar:git-Paper-781]
	at net.minecraft.server.v1_10_R1.EntityTracker.updatePlayers(EntityTracker.java:178) [patched_1.10.jar:git-Paper-781]
	at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:881) [patched_1.10.jar:git-Paper-781]
	at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:403) [patched_1.10.jar:git-Paper-781]
	at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:730) [patched_1.10.jar:git-Paper-781]
	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:629) [patched_1.10.jar:git-Paper-781]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_91]
```

**Comment by xXKeyleXx** [comment]
Will upload a new version as soon as I fix the jumping bug for 1.10
