### ISSUE TITLE
MyPet Premium 2.1.8 Fatal error (Error executing task)

### ISSUE THREAD

**Issue by andris155** [xXKeyleXx/MyPet#820]
```
[11:41:33] [Server thread/INFO]: FlyMiner issued server command: /peti
[11:41:34] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException: -1
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_91]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_91]
	at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:46) [patched_1.10.jar:git-Paper-781]
	at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:793) [patched_1.10.jar:git-Paper-781]
	at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:403) [patched_1.10.jar:git-Paper-781]
	at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:730) [patched_1.10.jar:git-Paper-781]
	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:629) [patched_1.10.jar:git-Paper-781]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_91]
Caused by: java.lang.ArrayIndexOutOfBoundsException: -1
	at java.util.ArrayList.elementData(Unknown Source) ~[?:1.8.0_91]
	at java.util.ArrayList.get(Unknown Source) ~[?:1.8.0_91]
	at net.minecraft.server.v1_10_R1.Container.getSlot(Container.java:111) ~[patched_1.10.jar:git-Paper-781]
	at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1819) ~[patched_1.10.jar:git-Paper-781]
	at net.minecraft.server.v1_10_R1.PacketPlayInWindowClick.a(SourceFile:33) ~[patched_1.10.jar:git-Paper-781]
	at net.minecraft.server.v1_10_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.10.jar:git-Paper-781]
	at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) ~[patched_1.10.jar:git-Paper-781]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_91]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_91]
	at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) ~[patched_1.10.jar:git-Paper-781]
	... 5 more
```

**Comment by xXKeyleXx** [comment]
It's not a MyPet problem. Either the server failed at reading the inventory click packet from the player, some plugin messed with the inventory click packet or a user tried to crash your server.
