### ISSUE TITLE
MyPet Premium 2.2.0 error (java.lang.NullPointerException)

### ISSUE THREAD

**Issue by andris155** [xXKeyleXx/MyPet#840]
```
21.07 19:59:54 [Server] WARN java.lang.NullPointerException
21.07 19:59:54 [Server] WARN at de.Keyle.MyPet.compat.v1_10_R1.entity.EntityMyPet.makeLivingSound(EntityMyPet.java:673)
21.07 19:59:54 [Server] WARN at de.Keyle.MyPet.compat.v1_10_R1.entity.EntityMyPet.G(EntityMyPet.java:1142)
21.07 19:59:54 [Server] WARN at net.minecraft.server.v1_10_R1.EntityInsentient.D(EntityInsentient.java:172)
21.07 19:59:54 [Server] WARN at net.minecraft.server.v1_10_R1.EntityInsentient.U(EntityInsentient.java:185)
21.07 19:59:54 [Server] WARN at net.minecraft.server.v1_10_R1.Entity.m(Entity.java:321)
21.07 19:59:54 [Server] WARN at net.minecraft.server.v1_10_R1.EntityLiving.m(EntityLiving.java:1768)
21.07 19:59:54 [Server] WARN at net.minecraft.server.v1_10_R1.EntityInsentient.m(EntityInsentient.java:241)
21.07 19:59:54 [Server] WARN at de.Keyle.MyPet.compat.v1_10_R1.entity.EntityMyPet.m(EntityMyPet.java:1127)
21.07 19:59:54 [Server] WARN at net.minecraft.server.v1_10_R1.World.entityJoinedWorld(World.java:1738)
21.07 19:59:54 [Server] WARN at net.minecraft.server.v1_10_R1.World.g(World.java:1713)
21.07 19:59:54 [Server] WARN at net.minecraft.server.v1_10_R1.World.tickEntities(World.java:1530)
21.07 19:59:54 [Server] WARN at net.minecraft.server.v1_10_R1.WorldServer.tickEntities(WorldServer.java:643)
21.07 19:59:54 [Server] WARN at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:859)
21.07 19:59:54 [Server] WARN at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:404)
21.07 19:59:54 [Server] WARN at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:725)
21.07 19:59:54 [Server] WARN at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:624)
21.07 19:59:54 [Server] WARN at java.lang.Thread.run(Unknown Source)
```
Paper 1.10

**Comment by xXKeyleXx** [comment]
Was there any other error before this one? What happened right before this happened?
