### ISSUE TITLE
Error on Startup (2.2.3 @ Spigot 1.10.2)

### ISSUE THREAD

**Issue by Phreag** [xXKeyleXx/MyPet#845]
[22:32:03 INFO]: This server is running Paper version git-Paper-821 (MC: 1.10.2) (Implementing API v
ersion 1.10.2-R0.1-SNAPSHOT)

[22:28:42 INFO]: [MyPet] Enabling MyPet v2.2.3
[22:28:42 INFO]: [MyPet] Citizens hook activated.
[22:28:43 INFO]: [MyPet] ProtocolLib hook activated.
[22:28:43 INFO]: [MyPet] Vault hook activated.
[22:28:43 INFO]: [MyPet] WorldGuard hook activated.
[22:28:43 ERROR]: Error occurred while enabling MyPet v2.2.3 (Is it up to date?)
java.lang.NullPointerException
        at de.Keyle.MyPet.util.ConfigurationLoader.seperateFood(ConfigurationLoader.java:493) ~[?:?]

        at de.Keyle.MyPet.util.ConfigurationLoader.loadConfiguration(ConfigurationLoader.java:460) ~
[?:?]
        at de.Keyle.MyPet.MyPetPlugin.onEnable(MyPetPlugin.java:162) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292) ~[spigot.jar:git-Paper-
821]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:319) [spigot.j
ar:git-Paper-821]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [spigot.
jar:git-Paper-821]
        at org.bukkit.craftbukkit.v1_10_R1.CraftServer.loadPlugin(CraftServer.java:358) [spigot.jar:
git-Paper-821]
        at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugins(CraftServer.java:318) [spigot.j
ar:git-Paper-821]
        at net.minecraft.server.v1_10_R1.MinecraftServer.t(MinecraftServer.java:409) [spigot.jar:git
-Paper-821]
        at net.minecraft.server.v1_10_R1.MinecraftServer.l(MinecraftServer.java:374) [spigot.jar:git
-Paper-821]
        at net.minecraft.server.v1_10_R1.MinecraftServer.a(MinecraftServer.java:328) [spigot.jar:git
-Paper-821]
        at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:275) [spigot.jar:
git-Paper-821]
        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:575) [spigot.jar:g
it-Paper-821]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_71]

Whats the Problem?

**Comment by frizzbee30** [comment]
we are using 1.10.2 , standard spigot, looks like the same issue?

**Comment by Phreag** [comment]
Red the text i pasted...

22:32:03 INFO]: This server is running Paper version git-Paper-821 (MC: 1.10.2) (Implementing API v
ersion 1.10.2-R0.1-SNAPSHOT)
