### ISSUE TITLE
Error with NCP

### ISSUE THREAD

**Issue by Nachodiazv** [xXKeyleXx/MyPet#847]
`[03:21:12] [Server thread/INFO]: This server is running Paper version git-Paper-717 (MC: 1.9.2) (Implementing API version 1.9.2-R0.1-SNAPSHOT)`

```
[03:21:18] [Server thread/ERROR]: Error occurred while enabling MyPet v2.2.3 (Is it up to date?)
java.lang.NoSuchFieldError: MOVING_VEHICLE_ENVELOPE
        at de.Keyle.MyPet.util.hooks.NoCheatPlusHook.onEnable(NoCheatPlusHook.java:38) ~[?:?]
        at de.Keyle.MyPet.api.util.hooks.PluginHookManager.registerHook(PluginHookManager.java:58) ~[?:?]
        at de.Keyle.MyPet.MyPetPlugin.onEnable(MyPetPlugin.java:145) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292) ~[spigot.jar:git-Paper-717]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:319) [spigot.jar:git-Paper-717]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [spigot.jar:git-Paper-717]
        at org.bukkit.craftbukkit.v1_9_R1.CraftServer.loadPlugin(CraftServer.java:357) [spigot.jar:git-Paper-717]
        at org.bukkit.craftbukkit.v1_9_R1.CraftServer.enablePlugins(CraftServer.java:317) [spigot.jar:git-Paper-717]
        at net.minecraft.server.v1_9_R1.MinecraftServer.t(MinecraftServer.java:414) [spigot.jar:git-Paper-717]
        at net.minecraft.server.v1_9_R1.MinecraftServer.l(MinecraftServer.java:379) [spigot.jar:git-Paper-717]
        at net.minecraft.server.v1_9_R1.MinecraftServer.a(MinecraftServer.java:333) [spigot.jar:git-Paper-717]
        at net.minecraft.server.v1_9_R1.DedicatedServer.init(DedicatedServer.java:273) [spigot.jar:git-Paper-717]
        at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:573) [spigot.jar:git-Paper-717]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
```

Is this a version problem?

**Comment by xXKeyleXx** [comment]
Yes I think so. I used the 1.10 version of NCP. But I will fix it for older versions.

**Comment by Nachodiazv** [comment]
Ah its OK I updated NCP and works fine. Sorry for wasting your time.
