### ISSUE TITLE
Error on petcall

### ISSUE THREAD

**Issue by zenandreas** [xXKeyleXx/MyPet#897]
`[11:56:50 INFO]: ZenAndreas issued server command: /petcall

org.bukkit.command.CommandException: Unhandled exception executing command 'petcall' in plugin MyPet v2.2.6
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[dev1.jar:git-Spigot-7745d45-02d704b]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[dev1.jar:git-Spigot-7745d45-02d704b]
        at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchCommand(CraftServer.java:646) ~[dev1.jar:git-Spigot-7745d45-02d704b]
        at net.minecraft.server.v1_10_R1.PlayerConnection.handleCommand(PlayerConnection.java:1351) [dev1.jar:git-Spigot-7745d45-02d704b]
        at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1186) [dev1.jar:git-Spigot-7745d45-02d704b]
        at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [dev1.jar:git-Spigot-7745d45-02d704b]
        at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [dev1.jar:git-Spigot-7745d45-02d704b]
        at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [dev1.jar:git-Spigot-7745d45-02d704b]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_72]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_72]
        at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [dev1.jar:git-Spigot-7745d45-02d704b]
        at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:737) [dev1.jar:git-Spigot-7745d45-02d704b]
        at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:399) [dev1.jar:git-Spigot-7745d45-02d704b]
        at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:673) [dev1.jar:git-Spigot-7745d45-02d704b]
        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:572) [dev1.jar:git-Spigot-7745d45-02d704b]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]
Caused by: java.lang.NoClassDefFoundError: Could not initialize class de.Keyle.MyPet.compat.v1_10_R1.entity.types.EntityMyWolf
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_72]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_72]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_72]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_72]
        at de.Keyle.MyPet.compat.v1_10_R1.entity.EntityRegistry.createMinecraftEntity(EntityRegistry.java:94) ~[?:?]
        at de.Keyle.MyPet.entity.MyPet.createEntity(MyPet.java:442) ~[?:?]
        at de.Keyle.MyPet.commands.CommandCall.onCommand(CommandCall.java:44) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[dev1.jar:git-Spigot-7745d45-02d704b]
        ... 15 more
`

**Comment by xXKeyleXx** [comment]
MyPet build?
Spigot build?

Or post the whole log.

**Comment by zenandreas** [comment]
All on latest builds.

http://pastebin.com/asJggqgG

**Comment by zenandreas** [comment]
Did i do anything wrong?

**Comment by xXKeyleXx** [comment]
I guess something went wrong when the plugin was loaded. It misses a class that is 100% there (when you downloaded it from the official source. Did this happen only once?

**Comment by zenandreas** [comment]
It happens all the time i can t use the plugin. Would the premium version do better i wanted to purchase it bit apparently cant use it

**Comment by xXKeyleXx** [comment]
Do you use another plugin that uses custom entities?

**Comment by zenandreas** [comment]
I am using UltraCosmetics and a spawning plugin. I've noticed that the first time i login after server restart the pet spawns , after despawning it and taming a new pet, this happens.
