### ISSUE TITLE
Pferd Dublicating bug

### ISSUE THREAD

**Issue by Sprungente** [xXKeyleXx/MyPet#925]
Einige Spieler berichten mir, dass wenn sie /petrelease Name ein Pferd freigeben wollen, dass es nicht freigegeben wird, sondern ein Pferdexemplar spawnt. Somit glitchen die Spieler aktuell massenweise Pferde bei sich.

**Comment by Sprungente** [comment]
```
[20:40:31] [Server thread/INFO]: easyzocker533 issued server command: /petrelease Skelett
[20:40:31] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'petrelease' in plugin MyPet v2.3.2
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot1110.jar:git-Spigot-31fef09-78c7614]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot1110.jar:git-Spigot-31fef09-78c7614]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:649) ~[spigot1110.jar:git-Spigot-31fef09-78c7614]
	at net.minecraft.server.v1_11_R1.PlayerConnection.handleCommand(PlayerConnection.java:1335) [spigot1110.jar:git-Spigot-31fef09-78c7614]
	at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1170) [spigot1110.jar:git-Spigot-31fef09-78c7614]
	at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot1110.jar:git-Spigot-31fef09-78c7614]
	at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot1110.jar:git-Spigot-31fef09-78c7614]
	at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot1110.jar:git-Spigot-31fef09-78c7614]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_111]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_111]
	at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [spigot1110.jar:git-Spigot-31fef09-78c7614]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot1110.jar:git-Spigot-31fef09-78c7614]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot1110.jar:git-Spigot-31fef09-78c7614]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [spigot1110.jar:git-Spigot-31fef09-78c7614]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [spigot1110.jar:git-Spigot-31fef09-78c7614]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
Caused by: java.lang.UnsupportedOperationException: Not supported.
	at org.bukkit.craftbukkit.v1_11_R1.entity.CraftSkeleton.setSkeletonType(CraftSkeleton.java:36) ~[spigot1110.jar:git-Spigot-31fef09-78c7614]
	at de.Keyle.MyPet.commands.CommandRelease.onCommand(CommandRelease.java:194) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot1110.jar:git-Spigot-31fef09-78c7614]
	... 15 more
```

**Comment by xXKeyleXx** [comment]
https://mypet-plugin.de/download
I fixed it with a temporary solution

**Comment by Sprungente** [comment]
auch für die Premium-Version?

**Comment by xXKeyleXx** [comment]
Du musst eingeloggt sein und den Premium key aktiviert haben

**Comment by Sprungente** [comment]
Hab auf die neuste Devbuildversion gewechselt. Auch bei Lamas Skelettpferde etc. gibt es das Problem weiterhin

`[13:52:02] [Server thread/INFO]: IchLixbeMichelle issued server command: /petrelease .
[13:52:02] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'petrelease' in plugin MyPet v2.3.2
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot1110.jar:git-Spigot-31fef09-78c7614]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot1110.jar:git-Spigot-31fef09-78c7614]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:649) ~[spigot1110.jar:git-Spigot-31fef09-78c7614]
	at net.minecraft.server.v1_11_R1.PlayerConnection.handleCommand(PlayerConnection.java:1335) [spigot1110.jar:git-Spigot-31fef09-78c7614]
	at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1170) [spigot1110.jar:git-Spigot-31fef09-78c7614]
	at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot1110.jar:git-Spigot-31fef09-78c7614]
	at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot1110.jar:git-Spigot-31fef09-78c7614]
	at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot1110.jar:git-Spigot-31fef09-78c7614]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_111]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_111]
	at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [spigot1110.jar:git-Spigot-31fef09-78c7614]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot1110.jar:git-Spigot-31fef09-78c7614]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot1110.jar:git-Spigot-31fef09-78c7614]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [spigot1110.jar:git-Spigot-31fef09-78c7614]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [spigot1110.jar:git-Spigot-31fef09-78c7614]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 5
	at de.Keyle.MyPet.commands.CommandRelease.onCommand(CommandRelease.java:227) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot1110.jar:git-Spigot-31fef09-78c7614]
	... 15 more`

Dabei ist es egal ob das Pet mit /psa da ist oder nicht

**Comment by xXKeyleXx** [comment]
Bin grad schon dabei das zu fixen

**Comment by Sprungente** [comment]
Hab gerade gesehen, dass es einen neuen Devbuild gegeben hat und gleich ma getestet ob es gefixt wäre (Mypet Premium Buid 428). War ich zu früh?

**Comment by xXKeyleXx** [comment]
ne 428 müsste der richtige sein

**Comment by Sprungente** [comment]
Gut. Das Problem tritt immer noch auf:

`26.11 16:33:47 [Server] INFO Wildestier issued server command: /petrelease Lama
26.11 16:33:47 [Server] ERROR null
26.11 16:33:47 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'petrelease' in plugin MyPet v2.3.2
26.11 16:33:47 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot1110.jar:git-Spigot-f950f8e-2b7808f]
26.11 16:33:47 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot1110.jar:git-Spigot-f950f8e-2b7808f]
26.11 16:33:47 [Server] INFO at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:649) ~[spigot1110.jar:git-Spigot-f950f8e-2b7808f]
26.11 16:33:47 [Server] INFO at net.minecraft.server.v1_11_R1.PlayerConnection.handleCommand(PlayerConnection.java:1335) [spigot1110.jar:git-Spigot-f950f8e-2b7808f]
26.11 16:33:47 [Server] INFO at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1170) [spigot1110.jar:git-Spigot-f950f8e-2b7808f]
26.11 16:33:47 [Server] INFO at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot1110.jar:git-Spigot-f950f8e-2b7808f]
26.11 16:33:47 [Server] INFO at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot1110.jar:git-Spigot-f950f8e-2b7808f]
26.11 16:33:47 [Server] INFO at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot1110.jar:git-Spigot-f950f8e-2b7808f]
26.11 16:33:47 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_111]
26.11 16:33:47 [Server] INFO at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_111]
26.11 16:33:47 [Server] INFO at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [spigot1110.jar:git-Spigot-f950f8e-2b7808f]
26.11 16:33:47 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot1110.jar:git-Spigot-f950f8e-2b7808f]
26.11 16:33:47 [Server] INFO at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot1110.jar:git-Spigot-f950f8e-2b7808f]
26.11 16:33:47 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [spigot1110.jar:git-Spigot-f950f8e-2b7808f]
26.11 16:33:47 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [spigot1110.jar:git-Spigot-f950f8e-2b7808f]
26.11 16:33:47 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
26.11 16:33:47 [Server] INFO Caused by: java.lang.ArrayIndexOutOfBoundsException: 5
26.11 16:33:47 [Server] INFO at de.Keyle.MyPet.compat.v1_11_R1.services.EntityConverterService.convertEntity(EntityConverterService.java:217) ~[?:?]
26.11 16:33:47 [Server] INFO at de.Keyle.MyPet.commands.CommandRelease.onCommand(CommandRelease.java:95) ~[?:?]
26.11 16:33:47 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot1110.jar:git-Spigot-f950f8e-2b7808f]
26.11 16:33:47 [Server] INFO ... 15 more`

**Comment by xXKeyleXx** [comment]
Wie bistn du an nen Lama mit Variant 5 gekommen? Normal ist ein Wert zwischen 0 und 3.
Im aktuellen Build wird das ganze limiteirt. es sollte also wieder klappen

**Comment by Sprungente** [comment]
habs mittels /spawnmob llama 
bekommen ^^

Kann es bestätigen: Fehler behoben. Hattest sicher nen anstrengenden Tag, gönn dir ne Pause :) Vielen Dank für die ganze Arbeit und Fixes
