### ISSUE TITLE
capturehelper Warnung

### ISSUE THREAD

**Issue by Sprungente** [xXKeyleXx/MyPet#927]
Ist mir gerade im Mypetordner ins Auge geflogen. Konnte es noch nicht reproduzieren, aber lass es dich mal wissen:

`11-25-2016 23:29 [WARNING] [MyPet] Task #87 for MyPet v2.3.2 generated an exception
java.lang.NoClassDefFoundError: de/Keyle/MyPet/util/CaptureHelper
	at de.Keyle.MyPet.util.player.MyPetPlayerImpl.schedule(MyPetPlayerImpl.java:511)
	at de.Keyle.MyPet.api.util.Timer$3.run(Timer.java:67)
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71)
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353)
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:730)
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399)
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675)
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574)
	at java.lang.Thread.run(Unknown Source)`

**Comment by xXKeyleXx** [comment]
Der Fehler kann gar nicht auftreten. Ich denke du musst nur mal den Server neustarten.
