### ISSUE TITLE
When releasing a horse it throws an internal error and spawns another horse.

### ISSUE THREAD

**Issue by PsychoGrogan** [xXKeyleXx/MyPet#930]
Please provide the following info.

**Bukkit/Spigot/Bungee Build/Version:**
1.11

**MyPet Build/Version:**
2.2.7

**Do you use the premium version? (this wont change anything for you)**
No

**What is the expected result?**
It's supposed to release the horse

**What happens instead of that?**
The horse remains as a pet, and spawns another untamed horse at it's place.

**Error:**
```
`04.12 15:12:18 [Server] INFO [PsychoGrogan: Stopping the server]
04.12 15:10:10 [Server] INFO ... 15 more
04.12 15:10:10 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[Spigot111.jar:git-Spigot-f950f8e-2b7808f]
04.12 15:10:10 [Server] INFO at de.Keyle.MyPet.commands.CommandRelease.onCommand(CommandRelease.java:209) ~[?:?]
04.12 15:10:10 [Server] INFO at org.bukkit.craftbukkit.v1_11_R1.entity.CraftAbstractHorse.setVariant(CraftAbstractHorse.java:26) ~[Spigot111.jar:git-Spigot-f950f8e-2b7808f]
04.12 15:10:10 [Server] INFO Caused by: java.lang.UnsupportedOperationException: Not supported.
04.12 15:10:10 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
04.12 15:10:10 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [Spigot111.jar:git-Spigot-f950f8e-2b7808f]
04.12 15:10:10 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [Spigot111.jar:git-Spigot-f950f8e-2b7808f]
04.12 15:10:10 [Server] INFO at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [Spigot111.jar:git-Spigot-f950f8e-2b7808f]
04.12 15:10:10 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:739) [Spigot111.jar:git-Spigot-f950f8e-2b7808f]
04.12 15:10:10 [Server] INFO at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [Spigot111.jar:git-Spigot-f950f8e-2b7808f]
04.12 15:10:10 [Server] INFO at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_111]
04.12 15:10:10 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_111]
04.12 15:10:10 [Server] INFO at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [Spigot111.jar:git-Spigot-f950f8e-2b7808f]
04.12 15:10:10 [Server] INFO at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [Spigot111.jar:git-Spigot-f950f8e-2b7808f]
04.12 15:10:10 [Server] INFO at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [Spigot111.jar:git-Spigot-f950f8e-2b7808f]
04.12 15:10:10 [Server] INFO at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1170) [Spigot111.jar:git-Spigot-f950f8e-2b7808f]
04.12 15:10:10 [Server] INFO at net.minecraft.server.v1_11_R1.PlayerConnection.handleCommand(PlayerConnection.java:1335) [Spigot111.jar:git-Spigot-f950f8e-2b7808f]
04.12 15:10:10 [Server] INFO at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:649) ~[Spigot111.jar:git-Spigot-f950f8e-2b7808f]
04.12 15:10:10 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[Spigot111.jar:git-Spigot-f950f8e-2b7808f]
04.12 15:10:10 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[Spigot111.jar:git-Spigot-f950f8e-2b7808f]
04.12 15:10:10 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'petrelease' in plugin MyPet v2.2.7
04.12 15:10:10 [Server] ERROR null
04.12 15:09:56 [Server] INFO ... 15 more
04.12 15:09:56 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[Spigot111.jar:git-Spigot-f950f8e-2b7808f]
04.12 15:09:56 [Server] INFO at de.Keyle.MyPet.commands.CommandRelease.onCommand(CommandRelease.java:209) ~[?:?]
04.12 15:09:56 [Server] INFO at org.bukkit.craftbukkit.v1_11_R1.entity.CraftAbstractHorse.setVariant(CraftAbstractHorse.java:26) ~[Spigot111.jar:git-Spigot-f950f8e-2b7808f]
04.12 15:09:56 [Server] INFO Caused by: java.lang.UnsupportedOperationException: Not supported.
04.12 15:09:56 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
04.12 15:09:56 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [Spigot111.jar:git-Spigot-f950f8e-2b7808f]
04.12 15:09:56 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [Spigot111.jar:git-Spigot-f950f8e-2b7808f]
04.12 15:09:56 [Server] INFO at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [Spigot111.jar:git-Spigot-f950f8e-2b7808f]
04.12 15:09:56 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:739) [Spigot111.jar:git-Spigot-f950f8e-2b7808f]
04.12 15:09:56 [Server] INFO at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [Spigot111.jar:git-Spigot-f950f8e-2b7808f]
04.12 15:09:56 [Server] INFO at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_111]
04.12 15:09:56 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_111]
04.12 15:09:56 [Server] INFO at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [Spigot111.jar:git-Spigot-f950f8e-2b7808f]
04.12 15:09:56 [Server] INFO at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [Spigot111.jar:git-Spigot-f950f8e-2b7808f]
04.12 15:09:56 [Server] INFO at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [Spigot111.jar:git-Spigot-f950f8e-2b7808f]
04.12 15:09:56 [Server] INFO at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1170) [Spigot111.jar:git-Spigot-f950f8e-2b7808f]
04.12 15:09:56 [Server] INFO at net.minecraft.server.v1_11_R1.PlayerConnection.handleCommand(PlayerConnection.java:1335) [Spigot111.jar:git-Spigot-f950f8e-2b7808f]
04.12 15:09:56 [Server] INFO at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:649) ~[Spigot111.jar:git-Spigot-f950f8e-2b7808f]
04.12 15:09:56 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[Spigot111.jar:git-Spigot-f950f8e-2b7808f]
04.12 15:09:56 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[Spigot111.jar:git-Spigot-f950f8e-2b7808f]
04.12 15:09:56 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'petrelease' in plugin MyPet v2.2.7
04.12 15:09:56 [Server] ERROR null`
```

**Comment by xXKeyleXx** [comment]
Please use the latest dev build: https://mypet-plugin.de/download
