### ISSUE TITLE
MyPet server stop error

### ISSUE THREAD

**Issue by andris155** [xXKeyleXx/MyPet#933]
**Bukkit/Spigot/Bungee Build/Version:**
This server is running Paper version git-Paper-962 (MC: 1.11) (Implementing API version 1.11-R0.1-SNAPSHOT)
**MyPet Build/Version:**
MyPet-Premium 2.3.2
**Do you use the premium version? (this wont change anything for you)**
yes
**What is the expected result?**
Stop server
**What happens instead of that?**
Write error
**Error:**
```
[15:09:09] [Server thread/INFO]: [[0;32;22mMyPet[m] [mDisabling MyPet v2.3.2[m
[15:09:10] [Async Chat Thread - #45/INFO]: [Elit]HELLCAT: MCWIKIN azt írja hogy 300 élete van
[15:09:11] [Server thread/WARN]: java.lang.IllegalAccessException: Can not set static final net.minecraft.server.v1_11_R1.RegistryMaterials field net.minecraft.server.v1_11_R1.EntityTypes.b to net.minecraft.server.v1_11_R1.RegistryMaterials
[15:09:11] [Server thread/WARN]: 	at sun.reflect.UnsafeFieldAccessorImpl.throwFinalFieldIllegalAccessException(UnsafeFieldAccessorImpl.java:76)
[15:09:11] [Server thread/WARN]: 	at sun.reflect.UnsafeFieldAccessorImpl.throwFinalFieldIllegalAccessException(UnsafeFieldAccessorImpl.java:80)
[15:09:11] [Server thread/WARN]: 	at sun.reflect.UnsafeQualifiedStaticObjectFieldAccessorImpl.set(UnsafeQualifiedStaticObjectFieldAccessorImpl.java:77)
[15:09:11] [Server thread/WARN]: 	at java.lang.reflect.Field.set(Field.java:764)
[15:09:11] [Server thread/WARN]: 	at de.Keyle.MyPet.compat.v1_11_R1.entity.EntityRegistry.unregisterEntityTypes(EntityRegistry.java:161)
[15:09:11] [Server thread/WARN]: 	at de.Keyle.MyPet.MyPetPlugin.onDisable(MyPetPlugin.java:94)
[15:09:11] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:273)
[15:09:11] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:344)
[15:09:11] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:427)
[15:09:11] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:420)
[15:09:11] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.disablePlugins(CraftServer.java:346)
[15:09:11] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.stop(MinecraftServer.java:477)
[15:09:11] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:684)
[15:09:11] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[15:09:12] [Async Chat Thread - #45/INFO]: [Elit]HELLCAT: Naa mind1
[15:09:12] [Server thread/INFO]: [SurvivalGames] Disabling SurvivalGames vBeta 1.9.5
```

**Comment by xXKeyleXx** [comment]
This is already fixed in the latest dev build:
https://mypet-plugin.de/changelog/MyPet-Premium
