### ISSUE TITLE
Issue with the plugin

### ISSUE THREAD

**Issue by WhispTheFox** [xXKeyleXx/MyPet#944]
Please provide the following info.

**Bukkit/Spigot/Bungee Build/Version:**
Spigot for 1.11.2
**MyPet Build/Version:**
Version 2.3.3 and also with 2.3.4 beta
**Do you use the premium version? (this wont change anything for you)**
yes, I have premium.
**What is the expected result?**
The pet is tamed when it is hit with the lead item, and that commands run.
**What happens instead of that?**
I get an error seen below when I try to tame a pet with the lead, and when I run the commands nothing happens.
**Error:**
[01:56:29 ERROR]: Could not pass event EntityDamageByEntityEvent to MyPet v2.3.4
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-7d78b81-746cf0f]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-7d78b81-746cf0f]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-7d78b81-746cf0f]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-7d78b81-746cf0f]
	at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:90) [spigot.jar:git-Spigot-7d78b81-746cf0f]
	at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:575) [spigot.jar:git-Spigot-7d78b81-746cf0f]
	at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:480) [spigot.jar:git-Spigot-7d78b81-746cf0f]
	at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:607) [spigot.jar:git-Spigot-7d78b81-746cf0f]
	at net.minecraft.server.v1_11_R1.EntityLiving.damageEntity0(EntityLiving.java:1308) [spigot.jar:git-Spigot-7d78b81-746cf0f]
	at net.minecraft.server.v1_11_R1.EntityLiving.damageEntity(EntityLiving.java:854) [spigot.jar:git-Spigot-7d78b81-746cf0f]
	at net.minecraft.server.v1_11_R1.EntityWolf.damageEntity(EntityWolf.java:232) [spigot.jar:git-Spigot-7d78b81-746cf0f]
	at net.minecraft.server.v1_11_R1.EntityHuman.attack(EntityHuman.java:1023) [spigot.jar:git-Spigot-7d78b81-746cf0f]
	at net.minecraft.server.v1_11_R1.EntityPlayer.attack(EntityPlayer.java:1141) [spigot.jar:git-Spigot-7d78b81-746cf0f]
	at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1568) [spigot.jar:git-Spigot-7d78b81-746cf0f]
	at net.minecraft.server.v1_11_R1.PacketPlayInUseEntity.a(SourceFile:69) [spigot.jar:git-Spigot-7d78b81-746cf0f]
	at net.minecraft.server.v1_11_R1.PacketPlayInUseEntity.a(SourceFile:13) [spigot.jar:git-Spigot-7d78b81-746cf0f]
	at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-7d78b81-746cf0f]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_111]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_111]
	at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [spigot.jar:git-Spigot-7d78b81-746cf0f]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot.jar:git-Spigot-7d78b81-746cf0f]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot.jar:git-Spigot-7d78b81-746cf0f]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [spigot.jar:git-Spigot-7d78b81-746cf0f]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [spigot.jar:git-Spigot-7d78b81-746cf0f]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.lang.NullPointerException
	at de.Keyle.MyPet.listeners.EntityListener.on(EntityListener.java:567) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_111]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_111]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_111]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot.jar:git-Spigot-7d78b81-746cf0f]
	... 24 more
[01:56:29 WARN]: [MyPet] Plugin MyPet v2.3.4 generated an exception while executing task 304
java.lang.NullPointerException
	at de.Keyle.MyPet.repository.types.SqLiteRepository$14.run(SqLiteRepository.java:934) ~[?:?]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-7d78b81-746cf0f]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot.jar:git-Spigot-7d78b81-746cf0f]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_111]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
>

**Comment by xXKeyleXx** [comment]
The plugin seems to have problems with the SQLite database or library.
Does this still happen when you restart the server?

**Comment by WhispTheFox** [comment]
Yes, it does.

On Dec 28, 2016 5:39 AM, Sebastian Comans <notifications@github.com> wrote:

The plugin seems to have problems with the SQLite database or library.
Does this still happen when you restart the server?

**Comment by zerafox** [comment]
Spoke with another user on Discord, who also had startup errors relating to the SQLite database.
Here is their errorlog: http://pastebin.com/1EFbTd8h

They're using 2.3.4 Premium MyPet with Spigot 1.11.2

**Comment by WhispTheFox** [comment]
So will you be able to fix the problem?

On Jan 4, 2017 9:09 PM, Foxtail <notifications@github.com> wrote:

Spoke with another user on Discord, who also had startup errors relating to the SQLite database.
Here is their errorlog: http://pastebin.com/1EFbTd8h

They're using 2.3.4 Premium MyPet with Spigot 1.11.2

**Comment by zerafox** [comment]
You wouldn't happen to be using a version of LWC on your server would you?

**Comment by WhispTheFox** [comment]
I am actually. Is that attributing to the cause of the problem?

On Jan 5, 2017 12:21 AM, Foxtail <notifications@github.com> wrote:

You wouldn't happen to be using a version of LWC on your server would you?

**Comment by zerafox** [comment]
It caused the error for the user I mentioned earlier, uninstall LWC and see if that resolves your problem.
LWC is SO incredibly outdated these days I wouldn't be surprised if it's causing conflicts with other plugins.

Do let us know if removing LWC resolves your error/problem.

**Comment by zerafox** [comment]
Glad to hear it was just a conflict issue with LWC.
I do hope you are able to find a more-up-to-date replacement for it though. Good Luck

**Comment by xXKeyleXx** [comment]
could you attach/upload your LWC version so I can check what causes the problem please

**Comment by WhispTheFox** [comment]
I think I have a backup of my server somewhere on my computer so I can pull it from there, but I already deleted the copy that was in my server. I believe the build I was using was for Minecraft 1.5 though, so it was very out of date.

On Jan 5, 2017 5:24 PM, Sebastian Comans <notifications@github.com> wrote:

could you attach/upload your LWC version so I can check what causes the problem please
