### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Caperuto** [xXKeyleXx/MyPet#965]
what is it?

[03:43:22] [Server thread/INFO]: [MyPet] Loading MyPet v2.3.0
[03:43:22] [Server thread/INFO]: Level: INFO
[03:43:22] [Server thread/WARN]: [[0;32;22mMyPet[m] [mError occured while creating the de.Keyle.MyPet.api.util.service.types.EntityConverterService service.[m
[03:43:22] [Server thread/WARN]: java.lang.InstantiationException
[03:43:22] [Server thread/WARN]: 	at sun.reflect.InstantiationExceptionConstructorAccessorImpl.newInstance(InstantiationExceptionConstructorAccessorImpl.java:48)
[03:43:22] [Server thread/WARN]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[03:43:22] [Server thread/WARN]: 	at java.lang.Class.newInstance(Class.java:442)
[03:43:22] [Server thread/WARN]: 	at de.Keyle.MyPet.api.util.service.ServiceManager.registerService(ServiceManager.java:59)
[03:43:22] [Server thread/WARN]: 	at de.Keyle.MyPet.compat.v1_7_R4.CompatManager.init(CompatManager.java:12)
[03:43:22] [Server thread/WARN]: 	at de.Keyle.MyPet.MyPetPlugin.onLoad(MyPetPlugin.java:125)
[03:43:22] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugins(CraftServer.java:374)
[03:43:22] [Server thread/WARN]: 	at net.minecraft.server.v1_7_R4.DedicatedServer.init(DedicatedServer.java:169)
[03:43:22] [Server thread/WARN]: 	at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:494)
[03:43:22] [Server thread/WARN]: 	at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628)

**Comment by zerafox** [comment]
Where is the rest of the information you were asked for when you opened to make a Github ticket?
Did you just delete everything and paste an errorlog? x.x
Where's your server version? MyPet version? Etc?

**Comment by Caperuto** [comment]
Sorry, I do not know how to speak English.
I'll send the information

MyPet v2.2.9

Spigot version
http://prntscr.com/e12z49

log mypet
01-27-2017 03:46 [WARNING] [MyPet] Error occured while creating the de.Keyle.MyPet.api.util.service.types.EntityConverterService service.
01-27-2017 03:46 [WARNING] [MyPet] Error occured while enabling WorldGuard (6.1.3-SNAPSHOT;c904242) hook.
01-27-2017 03:46 [INFO] [MyPet] Enabling MyPet v2.2.9
01-27-2017 03:46 [INFO] [MyPet] Citizens (2.0.13-SNAPSHOT (build 1186)) hook activated.
01-27-2017 03:46 [INFO] [MyPet] PlaceholderAPI (2.6.0) hook activated.
01-27-2017 03:46 [INFO] [MyPet] ProtocolLib (3.7.0) hook activated.
01-27-2017 03:46 [INFO] [MyPet] Vault (1.5.6-b49) hook activated.
01-27-2017 03:46 [INFO] [MyPet] Compat mode for v1_7_R4 loaded.
01-27-2017 03:46 [INFO] [MyPet] Default skilltree file created (default.st).
01-27-2017 03:46 [INFO] [MyPet] No groups found. Everything will be in 'default' group.
01-27-2017 03:46 [INFO] [MyPet] --- Loading WorldGroups ---------------------------
01-27-2017 03:46 [INFO] [MyPet] added world to 'default' group.
01-27-2017 03:46 [INFO] [MyPet] added evento to 'default' group.
01-27-2017 03:46 [INFO] [MyPet] added eventosemclan to 'default' group.
01-27-2017 03:46 [INFO] [MyPet] added plotworld to 'default' group.
01-27-2017 03:46 [INFO] [MyPet] -------------------------------------------------
01-27-2017 03:46 [INFO] [MyPet] version 2.2.9-b1121 ENABLED

**Comment by xXKeyleXx** [comment]
I'm pretty sure MyPet isn't the cause of this problem but a casualty of some other problem. Does this happen on every server start?

**Comment by Caperuto** [comment]
Yes. And when I type / petbeacon an internal error occurs


[03:21:43] [Server thread/INFO]: Mechamadeninguem issued server command: /petbeacon
[03:21:43] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'petbeacon' in plugin MyPet v2.2.9
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.7.x-1.8.x.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) ~[spigot-1.7.x-1.8.x.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:767) ~[spigot-1.7.x-1.8.x.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	at net.minecraft.server.v1_7_R4.PlayerConnection.handleCommand(PlayerConnection.java:1043) [spigot-1.7.x-1.8.x.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	at net.minecraft.server.v1_7_R4.PlayerConnection.a(PlayerConnection.java:880) [spigot-1.7.x-1.8.x.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	at net.minecraft.server.v1_7_R4.PacketPlayInChat.a(PacketPlayInChat.java:28) [spigot-1.7.x-1.8.x.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	at net.minecraft.server.v1_7_R4.PacketPlayInChat.handle(PacketPlayInChat.java:65) [spigot-1.7.x-1.8.x.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	at net.minecraft.server.v1_7_R4.NetworkManager.a(NetworkManager.java:186) [spigot-1.7.x-1.8.x.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	at net.minecraft.server.v1_7_R4.ServerConnection.c(ServerConnection.java:81) [spigot-1.7.x-1.8.x.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:734) [spigot-1.7.x-1.8.x.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289) [spigot-1.7.x-1.8.x.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584) [spigot-1.7.x-1.8.x.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490) [spigot-1.7.x-1.8.x.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [spigot-1.7.x-1.8.x.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
Caused by: java.lang.NoClassDefFoundError: com/google/common/io/BaseEncoding
	at de.Keyle.MyPet.api.util.inventory.meta.SkullMeta.applyTo(SkullMeta.java:121) ~[?:?]
	at de.Keyle.MyPet.compat.v1_7_R4.util.iconmenu.IconMenuInventory.createItemStack(IconMenuInventory.java:185) ~[?:?]
	at de.Keyle.MyPet.compat.v1_7_R4.util.iconmenu.IconMenuInventory.open(IconMenuInventory.java:80) ~[?:?]
	at de.Keyle.MyPet.api.util.inventory.IconMenu.open(IconMenu.java:92) ~[?:?]
	at de.Keyle.MyPet.skill.skills.Beacon.activate(Beacon.java:371) ~[?:?]
	at de.Keyle.MyPet.commands.CommandBeacon.onCommand(CommandBeacon.java:57) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.7.x-1.8.x.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	... 13 more
Caused by: java.lang.ClassNotFoundException: com.google.common.io.BaseEncoding
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_121]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot-1.7.x-1.8.x.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.7.x-1.8.x.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_121]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_121]
	at de.Keyle.MyPet.api.util.inventory.meta.SkullMeta.applyTo(SkullMeta.java:121) ~[?:?]
	at de.Keyle.MyPet.compat.v1_7_R4.util.iconmenu.IconMenuInventory.createItemStack(IconMenuInventory.java:185) ~[?:?]
	at de.Keyle.MyPet.compat.v1_7_R4.util.iconmenu.IconMenuInventory.open(IconMenuInventory.java:80) ~[?:?]
	at de.Keyle.MyPet.api.util.inventory.IconMenu.open(IconMenu.java:92) ~[?:?]
	at de.Keyle.MyPet.skill.skills.Beacon.activate(Beacon.java:371) ~[?:?]
	at de.Keyle.MyPet.commands.CommandBeacon.onCommand(CommandBeacon.java:57) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.7.x-1.8.x.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	... 13 more
