### ISSUE TITLE
Error MyPet-Premium

### ISSUE THREAD

**Issue by DUDOZ** [xXKeyleXx/MyPet#971]
Please provide the following info.

**Bukkit/Spigot/Bungee Build/Version:**

**MyPet Build/Version:**

**Do you use the premium version? (this wont change anything for you)**

**What is the expected result?**

**What happens instead of that?**

**Error:**

**Comment by DUDOZ** [comment]
PapherSpigot 1.8.8

MyPet-Premium 2.3.4

Error:
[15:01:47] [Server thread/ERROR]: Could not pass event MyPetLevelUpEvent to MyPet v2.3.4
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[Spigot.jar:git-PaperSpigot-83b7006-039621d]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[Spigot.jar:git-PaperSpigot-83b7006-039621d]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[Spigot.jar:git-PaperSpigot-83b7006-039621d]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [Spigot.jar:git-PaperSpigot-83b7006-039621d]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) [Spigot.jar:git-PaperSpigot-83b7006-039621d]
	at de.Keyle.MyPet.api.skill.MyPetExperience.addExp(MyPetExperience.java:113) [MyPet.jar:?]
	at de.Keyle.MyPet.listeners.EntityListener.on(EntityListener.java:997) [MyPet.jar:?]
	at sun.reflect.GeneratedMethodAccessor414.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) [Spigot.jar:git-PaperSpigot-83b7006-039621d]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) [Spigot.jar:git-PaperSpigot-83b7006-039621d]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [Spigot.jar:git-PaperSpigot-83b7006-039621d]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [Spigot.jar:git-PaperSpigot-83b7006-039621d]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) [Spigot.jar:git-PaperSpigot-83b7006-039621d]
	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:378) [Spigot.jar:git-PaperSpigot-83b7006-039621d]
	at net.minecraft.server.v1_8_R3.EntityLiving.die(EntityLiving.java:884) [Spigot.jar:git-PaperSpigot-83b7006-039621d]
	at net.minecraft.server.v1_8_R3.EntityLiving.damageEntity(EntityLiving.java:822) [Spigot.jar:git-PaperSpigot-83b7006-039621d]
	at de.Keyle.MyPet.compat.v1_8_R3.entity.EntityMyPet.attack(EntityMyPet.java:347) [MyPet.jar:?]
	at de.Keyle.MyPet.compat.v1_8_R3.entity.ai.attack.MeleeAttack.tick(MeleeAttack.java:115) [MyPet.jar:?]
	at de.Keyle.MyPet.api.entity.ai.AIGoalSelector.tick(AIGoalSelector.java:125) [MyPet.jar:?]
	at de.Keyle.MyPet.compat.v1_8_R3.entity.EntityMyPet.doMyPetTick(EntityMyPet.java:960) [MyPet.jar:?]
	at de.Keyle.MyPet.compat.v1_8_R3.entity.EntityMyPet.m(EntityMyPet.java:895) [MyPet.jar:?]
	at net.minecraft.server.v1_8_R3.EntityLiving.t_(EntityLiving.java:1495) [Spigot.jar:git-PaperSpigot-83b7006-039621d]
	at net.minecraft.server.v1_8_R3.EntityInsentient.t_(EntityInsentient.java:194) [Spigot.jar:git-PaperSpigot-83b7006-039621d]
	at de.Keyle.MyPet.compat.v1_8_R3.entity.EntityMyPet.t_(EntityMyPet.java:1074) [MyPet.jar:?]
	at net.minecraft.server.v1_8_R3.World.entityJoinedWorld(World.java:1642) [Spigot.jar:git-PaperSpigot-83b7006-039621d]
	at net.minecraft.server.v1_8_R3.World.g(World.java:1609) [Spigot.jar:git-PaperSpigot-83b7006-039621d]
	at net.minecraft.server.v1_8_R3.World.tickEntities(World.java:1446) [Spigot.jar:git-PaperSpigot-83b7006-039621d]
	at net.minecraft.server.v1_8_R3.WorldServer.tickEntities(WorldServer.java:600) [Spigot.jar:git-PaperSpigot-83b7006-039621d]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:844) [Spigot.jar:git-PaperSpigot-83b7006-039621d]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [Spigot.jar:git-PaperSpigot-83b7006-039621d]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [Spigot.jar:git-PaperSpigot-83b7006-039621d]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [Spigot.jar:git-PaperSpigot-83b7006-039621d]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.lang.NoSuchMethodError: org.bukkit.World.playSound(Lorg/bukkit/Location;Ljava/lang/String;FF)V
	at de.Keyle.MyPet.listeners.LevelUpListener.on(LevelUpListener.java:103) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor462.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[Spigot.jar:git-PaperSpigot-83b7006-039621d]
	... 34 more
