### ISSUE TITLE
WARN: Establishing SSL connection without server's identity verification is not recommended.

### ISSUE THREAD

**Issue by PsychoLynx** [xXKeyleXx/MyPet#980]
Please provide the following info.

**Bukkit/Spigot/Bungee Build/Version:** TacoSpigot b#88 / Hexacord b#129

**MyPet Build/Version:** 2.3.4

**Do you use the premium version? (this wont change anything for you)**  Yes

**What is the expected result?** If the argument ?useSLL=false is added to the MySQL database name, it won't spam the server console with the below message. Currently adding the argument to the config makes it impossible to connect to the database with the following error:

[11:32:11] [Server thread/WARN]: RepositoryInitException{exception=de.Keyle.MyPet.util.hikari.pool.HikariPool$PoolInitializationException: Exception during pool initialization: HikariPool-0 - Connection is not available, request timed out after 30000ms.}
[11:32:11] [Server thread/WARN]:     at de.Keyle.MyPet.repository.types.MySqlRepository.init(MySqlRepository.java:92)
[11:32:11] [Server thread/WARN]:     at de.Keyle.MyPet.MyPetPlugin.onEnable(MyPetPlugin.java:277)
[11:32:11] [Server thread/WARN]:     at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271)
[11:32:11] [Server thread/WARN]:     at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316)
[11:32:11] [Server thread/WARN]:     at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407)
[11:32:11] [Server thread/WARN]:     at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:378)
[11:32:11] [Server thread/WARN]:     at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:328)
[11:32:11] [Server thread/WARN]:     at net.minecraft.server.v1_11_R1.MinecraftServer.t(MinecraftServer.java:437)
[11:32:11] [Server thread/WARN]:     at net.minecraft.server.v1_11_R1.MinecraftServer.l(MinecraftServer.java:398)
[11:32:11] [Server thread/WARN]:     at net.minecraft.server.v1_11_R1.MinecraftServer.a(MinecraftServer.java:336)
[11:32:11] [Server thread/WARN]:     at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:276)
[11:32:11] [Server thread/WARN]:     at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:603)
[11:32:11] [Server thread/WARN]:     at java.lang.Thread.run(Unknown Source)

**What happens instead of that?** The plugin seemingly connects to the MySQL database but the server console is spammed with the following message:

**Error:**
[Hikari connection adder (pool HikariPool-0)/WARN]: Sun Feb 26 11:16:31 EET 2017 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.

**Comment by xXKeyleXx** [comment]
Please try the latest dev build: https://mypet-plugin.de/download

**Comment by PsychoLynx** [comment]
Seems to work in the lates dev-build :)

**Comment by xXKeyleXx** [comment]
Great!
