### ISSUE TITLE
default install on spigot - kick if try get a pet

### ISSUE THREAD

**Issue by BabelSolea** [xXKeyleXx/MyPet#984]
Please provide the following info.

**Bukkit/Spigot/Bungee Build/Version:**
Spigot 1.11.2 latest
**MyPet Build/Version:**

**Do you use the premium version? (this wont change anything for you)**
nope
**What is the expected result?**
get a pet with default pet-config flag LowHP
**What happens instead of that?**
kick from server and cant connect - join/leave with error
**Error:**
log.log error:
Internal Exception: io.netty.handler.codec.EncoderException: java.lang.ArrayIndexOutOfBoundsException: -1

1. spawn pig from egg
2. take lead and tame pig
3. dmg pig to 1/10 hp
4. kicked with error
5. reconnect to server
6. kicked with error

i found what that probably happends cuz of worldguard latest build.

found thats:

```
[12:34:24 WARN]: [MyPet] Error occured while enabling WorldGuard (6.1.3-SNAPSHOT;c904242) hook.
[12:34:24 WARN]: java.lang.IllegalStateException: New flags cannot be registered at this time
[12:34:24 WARN]: 	at com.sk89q.worldguard.protection.flags.registry.SimpleFlagRegistry.register(SimpleFlagRegistry.java:57)
[12:34:24 WARN]: 	at de.Keyle.MyPet.util.hooks.WorldGuardHook.<init>(WorldGuardHook.java:52)
[12:34:24 WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[12:34:24 WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[12:34:24 WARN]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[12:34:24 WARN]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[12:34:24 WARN]: 	at java.lang.Class.newInstance(Class.java:442)
[12:34:24 WARN]: 	at de.Keyle.MyPet.api.util.hooks.PluginHookManager.registerHook(PluginHookManager.java:67)
[12:34:24 WARN]: 	at de.Keyle.MyPet.MyPetPlugin.registerHooks(MyPetPlugin.java:409)
[12:34:24 WARN]: 	at de.Keyle.MyPet.MyPetPlugin.onLoad(MyPetPlugin.java:129)
[12:34:24 WARN]: 	at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:362)
[12:34:24 WARN]: 	at com.rylinaux.plugman.command.LoadCommand.execute(LoadCommand.java:114)
[12:34:24 WARN]: 	at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:95)
[12:34:24 WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[12:34:24 WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[12:34:24 WARN]: 	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:650)
[12:34:24 WARN]: 	at net.minecraft.server.v1_11_R1.PlayerConnection.handleCommand(PlayerConnection.java:1344)
[12:34:24 WARN]: 	at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1179)
[12:34:24 WARN]: 	at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
[12:34:24 WARN]: 	at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
[12:34:24 WARN]: 	at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[12:34:24 WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[12:34:24 WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[12:34:24 WARN]: 	at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46)
[12:34:24 WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:747)
[12:34:24 WARN]: 	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399)
[12:34:24 WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678)
[12:34:24 WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576)
[12:34:24 WARN]: 	at java.lang.Thread.run(Thread.java:745)
[12:34:24 INFO]: [MyPet] Enabling MyPet v2.2.9
[12:34:29 INFO]: [MyPet] Citizens (2.0.21-SNAPSHOT (build 1461)) hook activated.
[12:34:29 INFO]: [MyPet] NoCheatPlus (3.15.0-SNAPSHOT-sMD5NET-b1046) hook activated.
[12:34:29 INFO]: [MyPet] PlaceholderAPI (2.6.0) hook activated.
[12:34:29 INFO]: [MyPet] ProtocolLib (4.2.0) hook activated.
[12:34:29 INFO]: [MyPet] Vault (1.5.6-b49) hook activated.
[12:34:29 INFO]: [MyPet] Compat mode for v1_11_R1 loaded.
[12:34:29 INFO]: [MyPet] Default skilltree file created (default.st).
[12:34:31 INFO]: [MyPet] No groups found. Everything will be in 'default' group.
[12:34:31 INFO]: [MyPet] --- Loading WorldGroups ---------------------------
[12:34:31 INFO]: [MyPet] added world to 'default' group.
[12:34:31 INFO]: [MyPet] added world_nether to 'default' group.
[12:34:31 INFO]: [MyPet] added world_the_end to 'default' group.
[12:34:31 INFO]: [MyPet] -------------------------------------------------
[12:34:31 INFO]: [MyPet] version 2.2.9-b1121 ENABLED
[12:34:31 INFO]: [NoCheatPlus] Added hook: MyPet [1.0].
[12:37:00 INFO]: [ProQuests] Updating top 10 players...
[12:42:26 INFO]: BabelSolea lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.ArrayIndexOutOfBoundsException: -1
[12:43:16 INFO]: UUID of player BabelSolea is c8b6216e-93ee-33bb-bfe1-8ba020d08116
[12:43:17 INFO]: BabelSolea[/95.27.125.26:11999] logged in with entity id 127143 at ([world]-807.2594161898752, 106.0, 1163.2106919405164)
[12:43:19 INFO]: BabelSolea lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.ArrayIndexOutOfBoundsException: -1
```

**Comment by BabelSolea** [comment]
i trying free version of plugin before use premium..
pls help me configuring plugin to dont have that critical errors and i pay premium =)
(have half plugins what i using is purchaised)

**Comment by BabelSolea** [comment]
ok i think i found what happens:

- i put .jar to plugins folder and load plugin in game from cmd  /plugman load MyPet-2.2.9
that load plugin but not hook WG.

so i shutdown server and launch - all working (i guess...)

=) so i can continue testing plugin to get premium =)

**Comment by xXKeyleXx** [comment]
Sorry I was on vocation until yesterday and I have to catch up with everything that happened ;) 

I don't give any grantee that the plugin works with plugman and I highly doubt that nothing will break when you reload the plugin this way. The WG hook is one thing for example. MyPet is a plugin that depends on the order plugins are loaded and expects it to be the normal way.

**Comment by BabelSolea** [comment]
yeah! I still learning this plugin... so huge and flexy!!! cool!

close issue =)
