### ISSUE TITLE
MyPet - Premium Issue with /petcall

### ISSUE THREAD

**Issue by NathanD2001** [xXKeyleXx/MyPet#989]
Please provide the following info.

**Bukkit/Spigot/Bungee Build/Version:**
Spigot 1.11.2 Version.

**MyPet Build/Version:**
MyPet - Premium Version 2.3.2.

**Do you use the premium version? (this wont change anything for you)**
Yes.

**What is the expected result?**
It should call my pet to me.

**What happens instead of that?**
Says in chat "An internal error has occurred while attempting to perform this command".

**Error:**
[22:16:11 WARN]: [MyPet] Task #619 for MyPet v2.3.2 generated an exception
java.lang.NoSuchMethodError: net.minecraft.server.v1_11_R1.Block.a(Lnet/minecraft/server/v1_11_R1/IBlockData;Lnet/minecraft/server/v1_11_R1/World;Lnet/minecraft/server/v1_11_R1/BlockPosition;Lnet/minecraft/server/v1_11_R1/AxisAlignedBB;Ljava/util/List;Lnet/minecraft/server/v1_11_R1/Entity;)V
        at de.Keyle.MyPet.compat.v1_11_R1.PlatformHelper.getBlockBBsInBB(PlatformHelper.java:139) ~[?:?]
        at de.Keyle.MyPet.compat.v1_11_R1.PlatformHelper.canSpawn(PlatformHelper.java:120) ~[?:?]
        at de.Keyle.MyPet.compat.v1_11_R1.PlatformHelper.canSpawn(PlatformHelper.java:115) ~[?:?]
        at de.Keyle.MyPet.entity.MyPet.createEntity(MyPet.java:489) ~[?:?]
        at de.Keyle.MyPet.util.player.MyPetPlayerImpl.schedule(MyPetPlayerImpl.java:477) ~[?:?]
        at de.Keyle.MyPet.api.util.Timer$3.run(Timer.java:67) ~[?:?]
        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-625bc00-b5f7b6d]
        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot.jar:git-Spigot-625bc00-b5f7b6d]
        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:738) [spigot.jar:git-Spigot-625bc00-b5f7b6d]
        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot.jar:git-Spigot-625bc00-b5f7b6d]
        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot.jar:git-Spigot-625bc00-b5f7b6d]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot.jar:git-Spigot-625bc00-b5f7b6d]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]

**Comment by xXKeyleXx** [comment]
Use the latest version...

**Comment by xXKeyleXx** [comment]
Please provide your Spigot username, otherwise I can't give support.
