### ISSUE TITLE
MySQL connection (help me pls! live server with players!)

### ISSUE THREAD

**Issue by BabelSolea** [xXKeyleXx/MyPet#990]
Please provide the following info.

i want use mysql for MyPet premium but that dont work.
help me make needed changes in configurations to make MySQL work true.

**Bukkit/Spigot/Bungee Build/Version:**

spigot 1.11.2
![image](https://cloud.githubusercontent.com/assets/23665302/24957505/979317bc-1f94-11e7-947b-c69429955c6b.png)

bungeecord
![image](https://cloud.githubusercontent.com/assets/23665302/24957525/a74e05f4-1f94-11e7-96fa-2c46879396e2.png)

**MyPet Build/Version:**

![image](https://cloud.githubusercontent.com/assets/23665302/24957616/f37710ce-1f94-11e7-90d7-25bff2c66329.png)

**Do you use the premium version? (this wont change anything for you)**

yes

**What is the expected result?**

on MySQL mypet database plugin automatically create and manage her data

**What happens instead of that?**

on MySQL mypet database is empry and errors about it in log.log
plugin continue saving data in file pets.db
![image](https://cloud.githubusercontent.com/assets/23665302/24957679/23c031e8-1f95-11e7-977a-7ca238e90f39.png)

**Error:**

**case 1**

config.yml
```
    Type: MySQL
    ConvertFrom: ''
    LoadDelay: 20
    MySQL:
      Database: mypet?useSSL=false
      TablePrefix: mypet_
      Host: localhost
      Password: ***
      User: root
      Port: 3306
      MaxConnections: 16
```

error in log.log with that config:
```
[03:01:50 INFO]: [MyPet] Enabling MyPet v2.3.4
[03:01:51 INFO]: [MyPet] Citizens (2.0.21-SNAPSHOT (build 1461)) hook activated.
[03:01:51 INFO]: [MyPet] NoCheatPlus (3.15.0-SNAPSHOT-sMD5NET-b1046) hook activated.
[03:01:51 INFO]: [MyPet] PlaceholderAPI (2.7.1) hook activated.
[03:01:51 INFO]: [MyPet] ProtocolLib (4.2.0) hook activated.
[03:01:51 INFO]: [MyPet] Vault (1.5.6-b49) hook activated.
[03:01:51 INFO]: [MyPet] WorldGuard (6.1.3-SNAPSHOT;c904242) hook activated.
[03:01:51 INFO]: [MyPet] Compat mode for v1_11_R1 loaded.
[03:02:25 WARN]: RepositoryInitException{exception=de.Keyle.MyPet.util.hikari.pool.HikariPool$PoolInitializationException: Exception during pool initialization: HikariPool-0 - Connection is not available, request timed out after 30000ms.}
[03:02:25 WARN]: 	at de.Keyle.MyPet.repository.types.MySqlRepository.init(MySqlRepository.java:92)
[03:02:25 WARN]: 	at de.Keyle.MyPet.MyPetPlugin.onEnable(MyPetPlugin.java:277)
[03:02:25 WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271)
[03:02:25 WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
[03:02:25 WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[03:02:25 WARN]: 	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:376)
[03:02:25 WARN]: 	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:326)
[03:02:25 WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.t(MinecraftServer.java:421)
[03:02:25 WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.l(MinecraftServer.java:382)
[03:02:25 WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.a(MinecraftServer.java:337)
[03:02:25 WARN]: 	at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:272)
[03:02:25 WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:544)
[03:02:25 WARN]: 	at java.lang.Thread.run(Thread.java:745)
```

**case 2**

config.yml
```
    Type: MySQL
    ConvertFrom: ''
    LoadDelay: 20
    MySQL:
      Database: mypet
      TablePrefix: mypet_
      Host: localhost
      Password: ***
      User: root
      Port: 3306
      MaxConnections: 16
```

error in log.log with that config:
```
[14:11:21 WARN]: Wed Apr 12 14:11:21 CEST 2017 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
[14:11:21 WARN]: Wed Apr 12 14:11:21 CEST 2017 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
```

**Comment by xXKeyleXx** [comment]
That problem was fixed in one of the later dev builds you can download here: https://mypet-plugin.de/download

**Comment by BabelSolea** [comment]
thanks!
i did it and stop/start server

using this way:

    Type: MySQL
    ConvertFrom: ''
    LoadDelay: 20
    MySQL:
      **Database: mypet**
      TablePrefix: mypet_
      Host: localhost
      Password: ***
      User: root
      Port: 3306
      MaxConnections: 16

MySQL created and working but now i have thats spam in log.log:

```
[16:05:01 WARN]: Wed Apr 12 16:05:01 CEST 2017 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
[16:05:01 WARN]: Wed Apr 12 16:05:01 CEST 2017 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
[16:05:01 WARN]: Wed Apr 12 16:05:01 CEST 2017 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
[16:05:01 WARN]: Wed Apr 12 16:05:01 CEST 2017 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
[16:05:01 WARN]: Wed Apr 12 16:05:01 CEST 2017 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
[16:05:01 WARN]: Wed Apr 12 16:05:01 CEST 2017 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
[16:05:01 WARN]: Wed Apr 12 16:05:01 CEST 2017 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
[16:05:01 WARN]: Wed Apr 12 16:05:01 CEST 2017 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
[16:05:01 WARN]: Wed Apr 12 16:05:01 CEST 2017 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
[16:05:01 WARN]: Wed Apr 12 16:05:01 CEST 2017 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
[16:05:01 WARN]: Wed Apr 12 16:05:01 CEST 2017 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
[16:05:01 WARN]: Wed Apr 12 16:05:01 CEST 2017 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
[16:05:01 WARN]: Wed Apr 12 16:05:01 CEST 2017 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
[16:05:01 WARN]: Wed Apr 12 16:05:01 CEST 2017 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
[16:05:01 WARN]: Wed Apr 12 16:05:01 CEST 2017 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
[16:05:01 WARN]: Wed Apr 12 16:05:01 CEST 2017 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
```

how i can change config to stop that spam?

**Comment by BabelSolea** [comment]
anyway now i can use plugin to all players
thanks for tip :3
